const FC_BIOQ1_B901 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que são aminoácidos?", es: "¿Qué son los aminoácidos?" }, answer: { pt: "Monômeros que formam proteínas, compostos por grupo amino (-NH₂), grupo carboxila (-COOH), hidrogênio e cadeia lateral (R).", es: "Monómeros de proteínas con grupo amino, carboxilo, H y R." }, difficulty: "facil" },
    { id: 2, question: { pt: "Quantos aminoácidos padrão existem?", es: "¿Cuántos aminoácidos estándar existen?" }, answer: { pt: "20 aminoácidos padrão codificados pelo código genético.", es: "20 aminoácidos estándar." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que define um aminoácido essencial?", es: "¿Qué define a un aminoácido esencial?" }, answer: { pt: "Aminoácido que o organismo não consegue sintetizar e deve ser obtido pela dieta.", es: "El cuerpo no puede sintetizarlo." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que é uma ligação peptídica?", es: "¿Qué es un enlace peptídico?" }, answer: { pt: "Ligação covalente entre o grupo amino de um aminoácido e o grupo carboxila de outro, com liberação de H₂O.", es: "Enlace entre amino y carboxilo." }, difficulty: "facil" },
    { id: 5, question: { pt: "O que é o ponto isoelétrico (pI)?", es: "¿Qué es el punto isoeléctrico (pI)?" }, answer: { pt: "pH no qual o aminoácido tem carga líquida zero (forma de zwitteríon).", es: "pH con carga neta cero." }, difficulty: "facil" },
    { id: 6, question: { pt: "O que é um zwitteríon?", es: "¿Qué es un zwitterión?" }, answer: { pt: "Forma dipolar do aminoácido no pH fisiológico, com NH₃⁺ e COO⁻ simultaneamente.", es: "Forma dipolar con NH₃⁺ y COO⁻." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual a diferença entre estrutura primária e secundária?", es: "¿Primaria vs Secundaria?" }, answer: { pt: "Primária: sequência linear. Secundária: padrões locais (α-hélice, folha-β).", es: "Secuencia vs Plegamiento local." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é a estrutura terciária?", es: "¿Qué es la estructura terciaria?" }, answer: { pt: "Dobramento tridimensional completo da cadeia polipeptídica.", es: "Plegamiento 3D completo." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é estrutura quaternária?", es: "¿Qué es la estructura cuaternaria?" }, answer: { pt: "Associação de duas ou mais cadeias polipeptídicas (subunidades).", es: "Asociación de subunidades." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que é desnaturação proteica?", es: "¿Qué es la desnaturalización?" }, answer: { pt: "Perda da estrutura 3D e função sem quebrar ligações peptídicas.", es: "Pérdida de estructura 3D." }, difficulty: "facil" },
    { id: 11, question: { pt: "Qual aminoácido é o mais simples?", es: "¿Aminoácido más simple?" }, answer: { pt: "Glicina (R = H).", es: "Glicina." }, difficulty: "facil" },
    { id: 12, question: { pt: "Qual a função principal da hemoglobina?", es: "¿Función de la hemoglobina?" }, answer: { pt: "Transporte de O₂ no sangue.", es: "Transporte de O₂." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que são proteínas globulares?", es: "¿Proteínas globulares?" }, answer: { pt: "Proteínas esféricas compactas e geralmente solúveis em água.", es: "Esféricas y solubles." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que são proteínas fibrosa?", es: "¿Proteínas fibrosas?" }, answer: { pt: "Proteínas alongadas e insolúveis com função estrutural.", es: "Alargadas e insolubles." }, difficulty: "facil" },
    { id: 15, question: { pt: "Cite um exemplo de proteína fibrosa.", es: "Ejemplo de proteína fibrosa." }, answer: { pt: "Colágeno ou queratina.", es: "Colágeno o queratina." }, difficulty: "facil" },
    { id: 16, question: { pt: "Qual vitamina é ligada ao colágeno?", es: "¿Vitamina y colágeno?" }, answer: { pt: "Vitamina C (importante para hidroxilação).", es: "Vitamina C." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é um peptídeo?", es: "¿Qué es un péptido?" }, answer: { pt: "Pequena cadeia de aminoácidos (geralmente < 50).", es: "Cadena corta de aminoácidos." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que estabiliza a α-hélice?", es: "¿Qué estabiliza la α-hélice?" }, answer: { pt: "Pontes de hidrogênio intracadeia.", es: "Puentes de hidrógeno." }, difficulty: "facil" },
    { id: 19, question: { pt: "Qual a carga do DNA e por que ele se liga a histonas?", es: "¿Carga del DNA e histonas?" }, answer: { pt: "DNA é negativo; histonas são positivas (ricas em Lisina e Arginina).", es: "DNA negativo, histonas positivas." }, difficulty: "facil" },
    { id: 20, question: { pt: "O que é um domínio proteico?", es: "¿Qué es un dominio?" }, answer: { pt: "Parte da proteína que se dobra independentemente e tem função específica.", es: "Unidad funcional independiente." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Qual a diferença entre aminoácidos L e D?", es: "¿L vs D?" }, answer: { pt: "Refere-se à quiralidade; proteínas humanas usam apenas a forma L.", es: "Quiralidad; humanos usan forma L." }, difficulty: "medio" },
    { id: 22, question: { pt: "O que são aminoácidos anfotéricos?", es: "¿Anfotéricos?" }, answer: { pt: "Substâncias que podem agir como ácido ou base dependendo do pH.", es: "Actúan como ácido o base." }, difficulty: "medio" },
    { id: 23, question: { pt: "Qual aminoácido forma pontes dissulfeto?", es: "¿Puentes disulfuro?" }, answer: { pt: "Cisteína.", es: "Cisteína." }, difficulty: "medio" },
    { id: 24, question: { pt: "O que é o efeito hidrofóbico no dobramento?", es: "¿Efecto hidrofóbico?" }, answer: { pt: "Tendência de cadeias apolares se esconderem no interior da proteína.", es: "Cadenas apolares al interior." }, difficulty: "medio" },
    { id: 25, question: { pt: "O que são chaperonas moleculares?", es: "¿Chaperonas?" }, answer: { pt: "Proteínas que auxiliam o dobramento correto de outras proteínas.", es: "Ayudan al plegamiento." }, difficulty: "medio" },
    { id: 26, question: { pt: "Como a prolina afeta a estrutura secundária?", es: "¿Prolina y estructura?" }, answer: { pt: "Seu anel rígido quebra α-hélices, criando curvas.", es: "Rompe α-hélices." }, difficulty: "medio" },
    { id: 27, question: { pt: "O que é a hemoglobina glicada (HbA1c)?", es: "¿HbA1c?" }, answer: { pt: "Hemoglobina com glicose ligada covalentemente; indica glicemia média de 3 meses.", es: "Glucosa en Hb; control diabetes." }, difficulty: "medio" },
    { id: 28, question: { pt: "Qual a diferença entre mioglobina e hemoglobina?", es: "¿Mioglobina vs Hemoglobina?" }, answer: { pt: "Mioglobina armazena O₂ no músculo (1 subunidade); Hemoglobina transporta no sangue (4 subunidades).", es: "Almacén vs Transporte." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que é cooperatividade na hemoglobina?", es: "¿Cooperatividad?" }, answer: { pt: "Ligação de um O₂ facilita a ligação dos próximos.", es: "Unión de O₂ facilita las demás." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que é o ponto isoelétrico de uma proteína?", es: "¿pI proteico?" }, answer: { pt: "pH onde a carga líquida da proteína inteira é zero; ela é menos solúvel nesse pH.", es: "pH con carga neta cero." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que caracteriza a estrutura supersecundária (motivo)?", es: "¿Motivo proteico?" }, answer: { pt: "Combinação comum de elementos secundários (ex.: mão-EF, meandro-β).", es: "Combinación de estructuras secundarias." }, difficulty: "medio" },
    { id: 32, question: { pt: "Qual o papel das interações de Van der Waals?", es: "¿Van der Waals?" }, answer: { pt: "Atrações fracas entre átomos próximos que estabilizam o núcleo hidrofóbico.", es: "Atracciones débiles." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que é a ponte de sal (ligação iônica)?", es: "¿Puente de sal?" }, answer: { pt: "Atração entre grupos laterais carregados opostamente (ex.: Asp⁻ e Lys⁺).", es: "Atracción entre cargas +/-." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que são holoproteínas e heteroproteínas?", es: "¿Holo vs Hetero?" }, answer: { pt: "Holo: apenas aminoácidos. Hetero: aminoácidos + grupo prostético (não-proteico).", es: "Solo AA vs AA + grupo no proteico." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que é o grupo heme?", es: "¿Grupo hemo?" }, answer: { pt: "Grupo prostético com ferro que se liga ao O₂.", es: "Grupo con Fe para O₂." }, difficulty: "medio" },
    { id: 36, question: { pt: "Como o pH afeta a afinidade da hemoglobina?", es: "¿pH y hemoglobina?" }, answer: { pt: "pH baixo (ácido) diminui a afinidade, liberando mais O₂ (Efeito Bohr).", es: "pH bajo baja afinidad." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é o 2,3-BPG?", es: "¿2,3-BPG?" }, answer: { pt: "Regulador que diminui a afinidade da Hb pelo O₂, facilitando a entrega nos tecidos.", es: "Baja afinidad de la Hb." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que causa a anemia falciforme?", es: "¿Causa de anemia falciforme?" }, answer: { pt: "Substituição de Ácido Glutâmico por Valina na cadeia β da hemoglobina.", es: "Glu por Val en cadena β." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é o colágeno tipo I?", es: "¿Colágeno tipo I?" }, answer: { pt: "Forma fibras grossas em ossos, tendões e pele; mais abundante no corpo.", es: "En huesos y tendones." }, difficulty: "medio" },
    { id: 40, question: { pt: "Qual a função da elastina?", es: "¿Elastina?" }, answer: { pt: "Proporcionar elasticidade a tecidos como pulmões e grandes artérias.", es: "Provee elasticidad." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a geometria da ligação peptídica.", es: "¿Geometría enlace peptídico?" }, answer: { pt: "É plana e rígida devido ao caráter parcial de ligação dupla (ressonância).", es: "Plana y rígida (resonancia)." }, difficulty: "dificil" },
    { id: 42, question: { pt: "O que são ângulos Phi (φ) e Psi (ψ)?", es: "¿Ángulos φ y ψ?" }, answer: { pt: "Ângulos de rotação em torno das ligações N-Cα e Cα-C da cadeia principal.", es: "Ángulos de rotación del Cα." }, difficulty: "dificil" },
    { id: 43, question: { pt: "O que é o gráfico de Ramachandran?", es: "¿Gráfico de Ramachandran?" }, answer: { pt: "Representação dos ângulos φ e ψ permitidos, prevendo estruturas secundárias.", es: "Muestra ángulos permitidos." }, difficulty: "dificil" },
    { id: 44, question: { pt: "O que é o Paradoxo de Levinthal?", es: "¿Paradoja de Levinthal?" }, answer: { pt: "Proteínas não podem testar todas as conformações ao acaso; o dobramento deve ser direcionado.", es: "Plegamiento no es al azar." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que é a anemia falciforme a nível molecular?", es: "¿Nivel molecular falciforme?" }, answer: { pt: "Polimerização de desoxi-HbS formando fibras rígidas que deformam a hemácia.", es: "Polimerización de HbS." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Como o CO afeta a hemoglobina?", es: "¿CO y hemoglobina?" }, answer: { pt: "Liga-se ao mesmo sítio do O₂ com afinidade 200x maior, impedindo o transporte.", es: "Compite con O₂ (200x afinidad)." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é o efeito Haldane?", es: "¿Efecto Haldane?" }, answer: { pt: "A oxigenação da Hb nos pulmões facilita a liberação de CO₂.", es: "O₂ facilita salida de CO₂." }, difficulty: "dificil" },
    { id: 48, question: { pt: "Descreva a estrutura do colágeno.", es: "¿Estructura del colágeno?" }, answer: { pt: "Tripla hélice dextrógira composta por três cadeias polipeptídicas levógiras.", es: "Triple hélice." }, difficulty: "dificil" },
    { id: 49, question: { pt: "O que é a ligação cruzada (cross-link) no colágeno?", es: "¿Ligação cruzada?" }, answer: { pt: "Ligações covalentes entre resíduos de lisina/hidroxilisina que dão força tensil.", es: "Enlaces covalentes de Lys." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é a Osteogênese Imperfeita?", es: "¿Osteogénesis imperfecta?" }, answer: { pt: "Doença genética (ossos de vidro) por mutações que afetam a síntese de colágeno tipo I.", es: "Falla en colágeno tipo I." }, difficulty: "dificil" },
    { id: 51, question: { pt: "O que é o escorbuto a nível bioquímico?", es: "¿Bioquímica escorbuto?" }, answer: { pt: "Falta de Vit C impede prolil-hidroxilase → colágeno sem hidroxiprolina é instável.", es: "Colágeno instable sin Vit C." }, difficulty: "dificil" },
    { id: 52, question: { pt: "O que são príons?", es: "¿Priones?" }, answer: { pt: "Proteínas infecciosas mal dobradas (PrPSc) que induzem proteínas normais (PrPC) a mudar de forma.", es: "Proteínas infecciosas." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é a meta-hemoglobina?", es: "¿Metahemoglobina?" }, answer: { pt: "Forma onde o ferro está no estado férrico (Fe³⁺), incapaz de ligar O₂.", es: "Fe³⁺ en vez de Fe²⁺." }, difficulty: "dificil" },
    { id: 54, question: { pt: "Qual o efeito da altitude na hemoglobina?", es: "¿Altitud y hemoglobina?" }, answer: { pt: "Aumento de 2,3-BPG para facilitar a entrega de O₂ nos tecidos (desvio à direita).", es: "Más 2,3-BPG." }, difficulty: "dificil" },
    { id: 55, question: { pt: "O que é a talassemia?", es: "¿Talasemia?" }, answer: { pt: "Doença hereditária com síntese reduzida ou ausente de uma das cadeias da globina (α ou β).", es: "Falla en síntesis de globina." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é a mioglobina urinária (mioglobinúria)?", es: "¿Mioglobinuria?" }, answer: { pt: "Presença de mioglobina na urina após lesão muscular grave (rabdomiólise); nefrotóxica.", es: "Mioglobina en orina." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Como a ureia desnatura proteínas?", es: "¿Urea y desnaturalización?" }, answer: { pt: "Interrompe as pontes de hidrogênio e desestabiliza o núcleo hidrofóbico.", es: "Rompe puentes de H." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que é a salting-out?", es: "¿Salting-out?" }, answer: { pt: "Precipitação de proteínas em altas concentrações de sal por competição por água.", es: "Precipitación por sal." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Qual a diferença entre mioglobina e hemoglobina?", es: "¿Diferença entre hemoglobina e mioglobina?" }, answer: { pt: "Hemoglobina: 4 subunidades, transporte de O₂ no sangue, cooperatividade. Mioglobina: 1 subunidade, armazenamento de O₂ no músculo.", es: "Hemoglobina: 4 subunidades, transporte. Mioglobina: 1 subunidad, almacenamiento." }, difficulty: "dificil" },
    { id: 60, question: { pt: "O que é a desnaturação por pH extremo?", es: "¿pH y desnaturalización?" }, answer: { pt: "Altera o estado de ionização dos grupos R, quebrando pontes de sal e pontes de H.", es: "Altera ionización de grupos R." }, difficulty: "dificil" }
];

const FC_BIOQ1_B902 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que são enzimas?", es: "¿Qué son las enzimas?" }, answer: { pt: "Catalisadores biológicos (geralmente proteínas) que aceleram reações químicas sem serem consumidos.", es: "Catalizadores biológicos que aceleran reacciones." }, difficulty: "facil" },
    { id: 2, question: { pt: "O que é o sítio ativo?", es: "¿Qué es el sitio activo?" }, answer: { pt: "Região da enzima onde o substrato se liga e a reação ocorre.", es: "Región donde se une el sustrato." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que é energia de ativação?", es: "¿Qué es la energía de activación?" }, answer: { pt: "Energia mínima necessária para iniciar uma reação; enzimas a diminuem.", es: "Energía mínima para iniciar reacción." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que é um substrato?", es: "¿Qué es un sustrato?" }, answer: { pt: "Molécula sobre a qual a enzima atua.", es: "Molécula sobre la cual actúa la enzima." }, difficulty: "facil" },
    { id: 5, question: { pt: "O que é o complexo enzima-substrato (ES)?", es: "¿Complejo ES?" }, answer: { pt: "Intermediário formado pela ligação temporária da enzima ao substrato.", es: "Unión temporal de enzima y sustrato." }, difficulty: "facil" },
    { id: 6, question: { pt: "O que é a especificidade enzimática?", es: "¿Especificidad?" }, answer: { pt: "Capacidade de uma enzima selecionar substratos específicos.", es: "Capacidad de seleccionar sustratos." }, difficulty: "facil" },
    { id: 7, question: { pt: "Como a temperatura alta afeta enzimas?", es: "¿Calor y enzimas?" }, answer: { pt: "Pode causar desnaturação, inativando a enzima.", es: "Puede causar desnaturalización." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é o pH ótimo?", es: "¿pH óptimo?" }, answer: { pt: "pH no qual a enzima apresenta sua atividade máxima.", es: "pH con máxima actividad." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que são coenzimas?", es: "¿Coenzimas?" }, answer: { pt: "Cofatores orgânicos (geralmente vitaminas) necessários para a função enzimática.", es: "Cofactores orgánicos." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que são zimogênios?", es: "¿Zimógenos?" }, answer: { pt: "Precursores inativos de enzimas que precisam ser clivados para ativar.", es: "Precursores inactivos." }, difficulty: "facil" },
    { id: 11, question: { pt: "Dê um exemplo de zimogênio.", es: "Ejemplo de zimógeno." }, answer: { pt: "Pepsinogênio ou tripsinogênio.", es: "Pepsinógeno." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que é a Vmáx?", es: "¿Vmáx?" }, answer: { pt: "Velocidade máxima atingida quando a enzima está saturada de substrato.", es: "Velocidad máxima de saturación." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que é o Km?", es: "¿Km?" }, answer: { pt: "Concentração de substrato onde a velocidade é metade da Vmáx.", es: "Concentración para ½Vmáx." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que indica um Km baixo?", es: "¿Km bajo?" }, answer: { pt: "Alta afinidade da enzima pelo substrato.", es: "Alta afinidad." }, difficulty: "facil" },
    { id: 15, question: { pt: "O que são inibidores?", es: "¿Inhibidores?" }, answer: { pt: "Substâncias que reduzem a velocidade de reações enzimáticas.", es: "Sustancias que frenan la reacción." }, difficulty: "facil" },
    { id: 16, question: { pt: "O que é inibição reversível?", es: "¿Inhibición reversible?" }, answer: { pt: "Inibição onde o inibidor se liga e desliga da enzima.", es: "Unión no permanente." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é inibição irreversível?", es: "¿Inhibición irreversible?" }, answer: { pt: "Inibidor se liga permanentemente (covalentemente) à enzima.", es: "Unión permanente." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que é o modelo 'chave-fechadura'?", es: "¿Llave-cerradura?" }, answer: { pt: "Modelo antigo onde o substrato se encaixa perfeitamente no sítio ativo rígido.", es: "Encaje rígido perfecto." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que são isoenzimas?", es: "¿Isoenzimas?" }, answer: { pt: "Diferentes formas da mesma enzima que catalisam a mesma reação.", es: "Diferentes formas, misma reacción." }, difficulty: "facil" },
    { id: 20, question: { pt: "Cite uma enzima usada no diagnóstico de infarto.", es: "Enzima diagnóstica de infarto." }, answer: { pt: "CK-MB ou Troponina (embora troponina não seja enzima).", es: "CK-MB." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "O que é o encaixe induzido?", es: "¿Ajuste inducido?" }, answer: { pt: "Mudança conformacional da enzima ao se ligar ao substrato para melhorar a catálise.", es: "Cambio de forma al unirse." }, difficulty: "medio" },
    { id: 22, question: { pt: "Como um inibidor competitivo afeta Km e Vmáx?", es: "¿Inhibidor competitivo: Km y Vmáx?" }, answer: { pt: "Aumenta o Km (aparente) e não altera a Vmáx.", es: "Sube Km, Vmáx igual." }, difficulty: "medio" },
    { id: 23, question: { pt: "Como um inibidor não-competitivo afeta Km e Vmáx?", es: "¿No competitivo: Km y Vmáx?" }, answer: { pt: "Não altera o Km e diminui a Vmáx.", es: "Km igual, baja Vmáx." }, difficulty: "medio" },
    { id: 24, question: { pt: "O que é um sítio alostérico?", es: "¿Sitio alostérico?" }, answer: { pt: "Sítio regulatório diferente do sítio ativo onde moduladores se ligam.", es: "Sitio regulador distinto." }, difficulty: "medio" },
    { id: 25, question: { pt: "O que é feedback negativo (retroinibição)?", es: "¿Retroinhibición?" }, answer: { pt: "O produto final de uma via inibe a primeira enzima dessa via.", es: "Producto final inhibe inicio." }, difficulty: "medio" },
    { id: 26, question: { pt: "O que são as Oxidorredutases?", es: "¿Oxidorreductasas?" }, answer: { pt: "Enzimas que catalisam reações de transferência de elétrons (redox).", es: "Catalizan redox." }, difficulty: "medio" },
    { id: 27, question: { pt: "O que são as Transferases?", es: "¿Transferasas?" }, answer: { pt: "Enzimas que transferem grupos (metil, fosfato, etc) de uma molécula a outra.", es: "Transfieren grupos químicos." }, difficulty: "medio" },
    { id: 28, question: { pt: "O que são as Hidrolases?", es: "¿Hidrolasas?" }, answer: { pt: "Enzimas que quebram ligações usando água.", es: "Rompen enlaces con agua." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que são as Liases?", es: "¿Liasas?" }, answer: { pt: "Enzimas que quebram ligações sem água/oxidação, formando duplas ligações.", es: "Rompen enlaces sin agua." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que são as Isomerases?", es: "¿Isomerasas?" }, answer: { pt: "Enzimas que rearranjam a estrutura da molécula (formam isômeros).", es: "Forman isómeros." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que são as Ligases?", es: "¿Ligasas?" }, answer: { pt: "Enzimas que unem duas moléculas com gasto de ATP.", es: "Unen moléculas con ATP." }, difficulty: "medio" },
    { id: 32, question: { pt: "O que é a holoenzima?", es: "¿Holoenzima?" }, answer: { pt: "Enzima completa e ativa (apoenzima + cofator).", es: "Enzima activa completa." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que é a apoenzima?", es: "¿Apoenzima?" }, answer: { pt: "Parte proteica da enzima, inativa sem o cofator.", es: "Parte proteica inactiva." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é o estado de transição?", es: "¿Estado de transición?" }, answer: { pt: "Momento de maior energia onde ligações estão sendo quebradas/formadas.", es: "Punto de máxima energía." }, difficulty: "medio" },
    { id: 35, question: { pt: "Como a concentração da enzima afeta a Vmáx?", es: "¿[Enzima] y Vmáx?" }, answer: { pt: "A Vmáx é diretamente proporcional à concentração da enzima.", es: "Vmáx sube con [E]." }, difficulty: "medio" },
    { id: 36, question: { pt: "O que é inibição por excesso de substrato?", es: "¿Inhibición por sustrato?" }, answer: { pt: "Fenômeno onde concentrações muito altas de substrato reduzem a velocidade.", es: "Mucho sustrato frena reacción." }, difficulty: "medio" },
    { id: 37, question: { pt: "Qual o papel das Quinases?", es: "¿Quinasas?" }, answer: { pt: "Enzimas que adicionam grupos fosfato (fosforilação) a proteínas.", es: "Añaden fosfatos." }, difficulty: "medio" },
    { id: 38, question: { pt: "Qual o papel das Fosfatases?", es: "¿Fosfatasas?" }, answer: { pt: "Enzimas que removem grupos fosfato de proteínas.", es: "Remueven fosfatos." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é a cooperação homotrópica?", es: "¿Cooperación homotrópica?" }, answer: { pt: "Quando o próprio substrato age como modulador alostérico (ex.: O₂ na Hb).", es: "Sustrato como modulador." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é o efeito de proximidade e orientação?", es: "¿Efecto proximidad?" }, answer: { pt: "A enzima aproxima os substratos na posição correta para reagirem.", es: "Alinea sustratos para reacción." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "O que é o kcat (número de turnover)?", es: "¿kcat?" }, answer: { pt: "Número de moléculas de substrato convertidas por sítio ativo por segundo.", es: "Sustratos por enzima/seg." }, difficulty: "dificil" },
    { id: 42, question: { pt: "O que é a eficiência catalítica?", es: "¿Eficiencia catalítica?" }, answer: { pt: "Razão kcat/Km; mede quão bem a enzima atua em baixas [S].", es: "Razón kcat/Km." }, difficulty: "dificil" },
    { id: 43, question: { pt: "O que é a inibição mista?", es: "¿Inhibición mixta?" }, answer: { pt: "Inibidor pode se ligar tanto à enzima livre quanto ao complexo ES.", es: "Se une a E o a ES." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Como o gráfico de Lineweaver-Burk ajuda a identificar inibição competitiva?", es: "¿Lineweaver-Burk competitivo?" }, answer: { pt: "As retas se cruzam no eixo Y (mesma Vmáx).", es: "Cruzan en eje Y." }, difficulty: "dificil" },
    { id: 45, question: { pt: "Como o gráfico de Lineweaver-Burk ajuda a identificar inibição não-competitiva?", es: "¿Lineweaver-Burk no competitivo?" }, answer: { pt: "As retas se cruzam no eixo X (mesmo Km).", es: "Cruzan en eje X." }, difficulty: "dificil" },
    { id: 46, question: { pt: "O que é o gráfico de Hill?", es: "¿Gráfico de Hill?" }, answer: { pt: "Mede o grau de cooperatividade (n > 1: positiva; n < 1: negativa).", es: "Mide cooperatividad." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é a catálise covalente?", es: "¿Catálisis covalente?" }, answer: { pt: "Formação temporária de uma ligação covalente entre enzima e substrato.", es: "Enlace covalente temporal." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que é a catálise ácido-base?", es: "¿Catálisis ácido-base?" }, answer: { pt: "Transferência de prótons (H⁺) para estabilizar o estado de transição.", es: "Transferencia de H⁺." }, difficulty: "dificil" },
    { id: 49, question: { pt: "O que é a catálise por íons metálicos?", es: "¿Catálisis metálica?" }, answer: { pt: "Uso de metais (ex.: Zn²⁺) para orientar substratos ou estabilizar cargas negativas.", es: "Uso de metales en catálisis." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é a inibição por 'suicídio'?", es: "¿Inhibición suicida?" }, answer: { pt: "Inibidor que a própria enzima converte em uma forma que a inativa permanentemente.", es: "Enzima se inactiva al actuar." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Dê um exemplo de inibidor irreversível clínico.", es: "Inhibidor irreversible clínico." }, answer: { pt: "Aspirina (inibe COX) ou Penicilina (inibe transpeptidase).", es: "Aspirina o Penicilina." }, difficulty: "dificil" },
    { id: 52, question: { pt: "O que é o limite de difusão?", es: "¿Límite de difusión?" }, answer: { pt: "Velocidade máxima teórica de uma enzima (encontro instantâneo com substrato).", es: "Velocidad máxima teórica." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é um análogo do estado de transição?", es: "¿Análogo estado transición?" }, answer: { pt: "Molécula que imita o estado de transição e se liga com força extrema à enzima.", es: "Imita estado de transición." }, difficulty: "dificil" },
    { id: 54, question: { pt: "Como a ALT e AST auxiliam no diagnóstico hepático?", es: "¿ALT/AST y diagnóstico?" }, answer: { pt: "Níveis elevados no sangue indicam lesão nos hepatócitos (extravasamento).", es: "Indican lesión hepática." }, difficulty: "dificil" },
    { id: 55, question: { pt: "O que é a ribozima?", es: "¿Ribozima?" }, answer: { pt: "Molécula de RNA com atividade catalítica.", es: "RNA catalítico." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é a quimotripsina?", es: "¿Quimiotripsina?" }, answer: { pt: "Serino-protease que cliva ligações após aminoácidos aromáticos (Phe, Trp, Tyr).", es: "Corta tras AA aromáticos." }, difficulty: "dificil" },
    { id: 57, question: { pt: "O que é a tríade catalítica da quimotripsina?", es: "¿Tríada catalítica?" }, answer: { pt: "Aspartato, Histidina e Serina (trabalham juntas para clivagem).", es: "Asp, His, Ser." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que é a inibição por produto?", es: "¿Inhibición por producto?" }, answer: { pt: "O próprio produto da reação inibe a enzima (forma simples de controle).", es: "Producto frena su enzima." }, difficulty: "dificil" },
    { id: 59, question: { pt: "O que é o modelo MWC (monod-wyman-changeux)?", es: "¿Modelo MWC?" }, answer: { pt: "Modelo de simetria para enzimas alostéricas (Tensed vs Relaxed).", es: "Modelo de alosterismo." }, difficulty: "dificil" },
    { id: 60, question: { pt: "O que é o buraco oxianiônico?", es: "¿Agujero oxianiónico?" }, answer: { pt: "Região na enzima que estabiliza o oxigênio carregado negativamente no estado de transição.", es: "Estabiliza carga negativa." }, difficulty: "dificil" }
];

const FC_BIOQ1_B903 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que é bioenergética?", es: "¿Qué es la bioenergética?" }, answer: { pt: "Estudo das transformações de energia nos sistemas biológicos.", es: "Estudio de las transformações de energia." }, difficulty: "facil" },
    { id: 2, question: { pt: "O que é ΔG (energia livre de Gibbs)?", es: "¿Qué es ΔG?" }, answer: { pt: "Energia disponível para realizar trabalho em uma reação.", es: "Energía para realizar trabajo." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que indica um ΔG negativo?", es: "¿ΔG negativo indica qué?" }, answer: { pt: "A reação é espontânea (exergônica).", es: "Reacción espontánea." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que indica um ΔG positivo?", es: "¿ΔG positivo indica qué?" }, answer: { pt: "A reação não é espontânea (endergônica).", es: "Reacción no espontánea." }, difficulty: "facil" },
    { id: 5, question: { pt: "O que é o ATP?", es: "¿Qué es el ATP?" }, answer: { pt: "Adenosina Trifosfato, a principal moeda energética da célula.", es: "Principal moneda energética." }, difficulty: "facil" },
    { id: 6, question: { pt: "Onde ocorre a maior produção de ATP na célula?", es: "¿Dónde se produce más ATP?" }, answer: { pt: "Na mitocôndria.", es: "En la mitocondria." }, difficulty: "facil" },
    { id: 7, question: { pt: "O que é oxidação?", es: "¿Qué es oxidación?" }, answer: { pt: "Perda de elétrons por uma molécula.", es: "Pérdida de electrones." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é redução?", es: "¿Qué es reducción?" }, answer: { pt: "Ganho de elétrons por uma molécula.", es: "Ganancia de electrones." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é o NAD⁺?", es: "¿Qué es el NAD⁺?" }, answer: { pt: "Um transportador de elétrons (coenzima) derivado da niacina.", es: "Transportador de electrones." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que é o FAD?", es: "¿Qué es el FAD?" }, answer: { pt: "Transportador de elétrons derivado da riboflavina.", es: "Transportador de electrones." }, difficulty: "facil" },
    { id: 11, question: { pt: "O que é acoplamento energético?", es: "¿Acoplamiento energético?" }, answer: { pt: "Uso de energia de uma reação exergônica para mover uma endergônica.", es: "Uso de energía exergónica para endergónica." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que é a cadeia de transporte de elétrons?", es: "¿Cadena de electrones?" }, answer: { pt: "Série de complexos na membrana mitocondrial que transferem elétrons para gerar ATP.", es: "Complejos que generan ATP." }, difficulty: "facil" },
    { id: 13, question: { pt: "Qual o aceptor final de elétrons na respiração aeróbica?", es: "¿Aceptor final de electrones?" }, answer: { pt: "Oxigênio (O₂).", es: "Oxígeno." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que é a ATP sintase?", es: "¿ATP sintasa?" }, answer: { pt: "Enzima que usa o gradiente de prótons para sintetizar ATP.", es: "Sintetiza ATP con gradiente de H⁺." }, difficulty: "facil" },
    { id: 15, question: { pt: "O que é calor?", es: "¿Qué es el calor?" }, answer: { pt: "Energia dissipada que não pode ser usada para trabalho biológico.", es: "Energía no útil para trabajo." }, difficulty: "facil" },
    { id: 16, question: { pt: "O que é metabolismo?", es: "¿Qué es metabolismo?" }, answer: { pt: "Conjunto de todas as reações químicas do organismo.", es: "Reacciones químicas del cuerpo." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é catabolismo?", es: "¿Catabolismo?" }, answer: { pt: "Fase de degradação de moléculas para liberar energia.", es: "Degradación para liberar energía." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que é anabolismo?", es: "¿Anabolismo?" }, answer: { pt: "Fase de síntese de moléculas complexas com gasto de energia.", es: "Síntesis con gasto de energía." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que é a hidrólise do ATP?", es: "¿Hidrólisis del ATP?" }, answer: { pt: "Quebra do ATP em ADP + Pi, liberando energia.", es: "ATP → ADP + Pi + energía." }, difficulty: "facil" },
    { id: 20, question: { pt: "O que é potencial de oxirredução (E)?", es: "¿Potencial redox?" }, answer: { pt: "Tendência de uma molécula ganhar ou perder elétrons.", es: "Tendencia a ganar/perder electrones." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Quantos ATPs o NADH gera aproximadamente?", es: "¿ATP por NADH?" }, answer: { pt: "Cerca de 2,5 ATPs.", es: "~2,5 ATPs." }, difficulty: "medio" },
    { id: 22, question: { pt: "Quantos ATPs o FADH₂ gera aproximadamente?", es: "¿ATP por FADH₂?" }, answer: { pt: "Cerca de 1,5 ATPs.", es: "~1,5 ATPs." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que é a força próton-motriz?", es: "¿Fuerza protón-motriz?" }, answer: { pt: "Energia armazenada no gradiente eletroquímico de H⁺ através da membrana.", es: "Energía en gradiente de H⁺." }, difficulty: "medio" },
    { id: 24, question: { pt: "Qual o papel do Complexo I?", es: "¿Papel del Complejo I?" }, answer: { pt: "NADH desidrogenase; transfere elétrons do NADH para a ubiquinona.", es: "NADH a ubiquinona." }, difficulty: "medio" },
    { id: 25, question: { pt: "Qual o papel do Complexo II?", es: "¿Papel del Complejo II?" }, answer: { pt: "Succinato desidrogenase; transfere elétrons do FADH₂ para a ubiquinona.", es: "FADH₂ a ubiquinona." }, difficulty: "medio" },
    { id: 26, question: { pt: "O que é a ubiquinona (Coenzima Q)?", es: "¿Ubiquinona?" }, answer: { pt: "Transportador lipossolúvel móvel de elétrons entre complexos I/II e III.", es: "Transportador móvil de electrones." }, difficulty: "medio" },
    { id: 27, question: { pt: "O que é o citocromo c?", es: "¿Citocromo c?" }, answer: { pt: "Pequena proteína que transporta elétrons do complexo III para o IV.", es: "Transportador entre III y IV." }, difficulty: "medio" },
    { id: 28, question: { pt: "O que acontece no Complexo IV?", es: "¿Qué pasa en el IV?" }, answer: { pt: "Citocromo c oxidase; transfere elétrons para o O₂, formando H₂O.", es: "Electrones al O₂ → H₂O." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que são desacopladores (ex.: DNP)?", es: "¿Desacopladores?" }, answer: { pt: "Substâncias que dissipam o gradiente de H⁺, gerando calor em vez de ATP.", es: "Generan calor, no ATP." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que é a termogenina?", es: "¿Termogenina?" }, answer: { pt: "Desacoplador natural no tecido adiposo marrom usado para gerar calor.", es: "Genera calor en grasa parda." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que é a fosforilação a nível de substrato?", es: "¿Fosforilación sustrato?" }, answer: { pt: "Formação de ATP direta sem usar a cadeia respiratória (ex.: glicólise).", es: "ATP sin cadena respiratoria." }, difficulty: "medio" },
    { id: 32, question: { pt: "O que é o ΔG'°?", es: "¿ΔG'°?" }, answer: { pt: "Variação de energia livre padrão em condições bioquímicas (pH 7).", es: "ΔG estándar a pH 7." }, difficulty: "medio" },
    { id: 33, question: { pt: "Por que a hidrólise do ATP libera tanta energia?", es: "¿Por qué el ATP libera energía?" }, answer: { pt: "Repulsão eletrostática entre fosfatos e estabilização por ressonância do Pi.", es: "Repulsión entre fosfatos." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é a adenilato quinase?", es: "¿Adenilato quinasa?" }, answer: { pt: "Enzima que mantém o equilíbrio: 2 ADP ↔ ATP + AMP.", es: "Equilibra nucleótidos." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que é a carga energética celular?", es: "¿Carga energética?" }, answer: { pt: "Índice que mede o 'status' de energia (razão entre ATP/ADP/AMP).", es: "Status de energía celular." }, difficulty: "medio" },
    { id: 36, question: { pt: "Como o NADH entra na mitocôndria?", es: "¿NADH a mitocondria?" }, answer: { pt: "Via lançadeiras (Malato-Aspartato ou Glicerol-3-Fosfato).", es: "Usa lanzaderas." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é o potencial de transferência de fosfato?", es: "¿Potencial transferencia?" }, answer: { pt: "Tendência de uma molécula doar seu grupo fosfato para o ADP.", es: "Tendencia a donar fosfato." }, difficulty: "medio" },
    { id: 38, question: { pt: "Cite uma molécula com potencial de transferência maior que o ATP.", es: "Molécula > ATP." }, answer: { pt: "Fosfoenolpiruvato (PEP) ou 1,3-bisfosfoglicerato.", es: "Fosfoenolpiruvato." }, difficulty: "medio" },
    { id: 39, question: { pt: "Qual a importância da Creatina Fosfato?", es: "¿Creatina Fosfato?" }, answer: { pt: "Reserva rápida de energia no músculo; doa fosfato para o ADP.", es: "Reserva rápida de ATP." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é a mitocôndria?", es: "¿Qué es la mitocondria?" }, answer: { pt: "Organela de dupla membrana onde ocorre o ciclo de Krebs e a fosforilação oxidativa.", es: "Central energética celular." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "O que é a teoria quimiosmótica de Mitchell?", es: "¿Teoría quimiosmótica?" }, answer: { pt: "O transporte de elétrons cria um gradiente de H⁺ que aciona a síntese de ATP.", es: "Gradiente de H⁺ mueve ATP sintasa." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Descreva a estrutura da ATP sintase (F0F1).", es: "¿Estructura ATP sintasa?" }, answer: { pt: "F0 é o canal de H⁺ na membrana; F1 é a cabeça catalítica que gira.", es: "F0 canal; F1 cabeza catalítica." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Como o cianeto mata?", es: "¿Cianuro?" }, answer: { pt: "Bloqueia o Complexo IV, impedindo a respiração celular.", es: "Inhibe Complejo IV." }, difficulty: "dificil" },
    { id: 44, question: { pt: "O que é o mecanismo de catálise por rotação?", es: "¿Catálisis por rotación?" }, answer: { pt: "O fluxo de H⁺ faz a subunidade γ girar, mudando a forma de β para sintetizar ATP.", es: "Giro genera síntesis de ATP." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que é a lançadeira Malato-Aspartato?", es: "¿Malato-Aspartato?" }, answer: { pt: "Lançadeira mais eficiente (coração/fígado) que rende 2,5 ATPs por NADH.", es: "Lanzadera eficiente (2,5 ATP)." }, difficulty: "dificil" },
    { id: 46, question: { pt: "O que é a lançadeira Glicerol-3-Fosfato?", es: "¿Glicerol-3-Fosfato?" }, answer: { pt: "Lançadeira menos eficiente (músculo) que rende 1,5 ATPs por NADH.", es: "Lanzadera (1,5 ATP)." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é a translocase de nucleotídeos de adenina?", es: "¿Translocase?" }, answer: { pt: "Antitransporte que tira ATP da mitocôndria e coloca ADP para dentro.", es: "Saca ATP, mete ADP." }, difficulty: "dificil" },
    { id: 48, question: { pt: "Como a oligomicina afeta a mitocôndria?", es: "¿Oligomicina?" }, answer: { pt: "Inibe a subunidade F0 da ATP sintase, bloqueando o fluxo de H⁺.", es: "Inhibe subunidad F0." }, difficulty: "dificil" },
    { id: 49, question: { pt: "O que é o Ciclo de Krebs (relação energética)?", es: "¿Krebs y energía?" }, answer: { pt: "Gera NADH e FADH₂ que alimentam a cadeia de transporte de elétrons.", es: "Genera NADH/FADH₂ para cadena." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é o controle respiratório?", es: "¿Control respiratorio?" }, answer: { pt: "Regulação da taxa de respiração pela disponibilidade de ADP.", es: "Regulación por ADP." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Qual a função dos centros Ferro-Enxofre (Fe-S)?", es: "¿Centros Fe-S?" }, answer: { pt: "Atuam como transportadores de elétrons únicos dentro dos complexos respiratórios.", es: "Transporte de electrones único." }, difficulty: "dificil" },
    { id: 52, question: { pt: "O que é o radical superóxido na mitocôndria?", es: "¿Superóxido?" }, answer: { pt: "Subproduto tóxico (ROS) formado quando elétrons escapam da cadeia.", es: "Subproducto tóxico (ROS)." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é a Apoptose e a mitocôndria?", es: "¿Apoptosis y mitocondria?" }, answer: { pt: "A liberação de citocromo c no citosol ativa a cascata de morte celular.", es: "Citocromo c activa muerte celular." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é a Termodinâmica (1ª Lei)?", es: "¿1ª Ley Termodinámica?" }, answer: { pt: "A energia não se cria nem se destrói, apenas se transforma.", es: "Energía se conserva." }, difficulty: "dificil" },
    { id: 55, question: { pt: "O que é a Termodinâmica (2ª Lei)?", es: "¿2ª Ley Termodinámica?" }, answer: { pt: "Processos espontâneos aumentam a entropia (desordem) do universo.", es: "Entropía aumenta." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é o ΔE'° (potencial de redução padrão)?", es: "¿ΔE'°?" }, answer: { pt: "Medida da afinidade por elétrons sob condições padrão.", es: "Afinidad por electrones." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Relacione ΔG e ΔE.", es: "¿Relación ΔG y ΔE?" }, answer: { pt: "ΔG = -nFΔE. Um ΔE positivo gera um ΔG negativo (espontâneo).", es: "ΔG = -nFΔE." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que é o complexo III?", es: "¿Complexo III?" }, answer: { pt: "Citocromo bc1; bombeia H⁺ e transfere elétrons da ubiquinona para o citocromo c.", es: "UQH₂ a citocromo c." }, difficulty: "dificil" },
    { id: 59, question: { pt: "O que é o Ciclo Q?", es: "¿Ciclo Q?" }, answer: { pt: "Mecanismo no Complexo III para transferir elétrons de 2 em 2 para o citocromo c (1 por 1).", es: "Transferencia de electrones en III." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Por que o Complexo II não bombeia H⁺?", es: "¿Por qué el II no bombea H⁺?" }, answer: { pt: "A variação de energia livre é insuficiente para mover prótons através da membrana.", es: "Energía insuficiente." }, difficulty: "dificil" }
];

const FC_BIOQ1_B904 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que são carboidratos?", es: "¿Qué son los carbohidratos?" }, answer: { pt: "Biomoléculas de C, H e O; principal fonte de energia rápida.", es: "Biomoléculas de C, H, O." }, difficulty: "facil" },
    { id: 2, question: { pt: "Qual a unidade básica dos carboidratos?", es: "¿Unidad básica?" }, answer: { pt: "Monossacarídeos.", es: "Monosacáridos." }, difficulty: "facil" },
    { id: 3, question: { pt: "Cite 3 monossacarídeos importantes.", es: "Cite 3 monosacáridos." }, answer: { pt: "Glicose, Frutose e Galactose.", es: "Glucosa, Fructosa, Galactosa." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que é um dissacarídeo?", es: "¿Qué es un disacárido?" }, answer: { pt: "União de dois monossacarídeos por ligação glicosídica.", es: "Unión de dos monosacáridos." }, difficulty: "facil" },
    { id: 5, question: { pt: "Qual o açúcar do leite?", es: "¿Azúcar de la leche?" }, answer: { pt: "Lactose.", es: "Lactosa." }, difficulty: "facil" },
    { id: 6, question: { pt: "Qual o açúcar de mesa?", es: "¿Azúcar de mesa?" }, answer: { pt: "Sacarose.", es: "Sacarosa." }, difficulty: "facil" },
    { id: 7, question: { pt: "O que é o glicogênio?", es: "¿Qué es el glucógeno?" }, answer: { pt: "Polissacarídeo de reserva de glicose em animais (fígado e músculos).", es: "Reserva de glucosa animal." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é o amido?", es: "¿Qué es el almidón?" }, answer: { pt: "Polissacarídeo de reserva de glicose em plantas.", es: "Reserva de glucosa vegetal." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é a glicólise?", es: "¿Qué es la glucólisis?" }, answer: { pt: "Quebra da glicose em piruvato para gerar energia (ATP).", es: "Degradación de glucosa." }, difficulty: "facil" },
    { id: 10, question: { pt: "Onde ocorre a glicólise?", es: "¿Dónde ocurre la glucólisis?" }, answer: { pt: "No citosol (citoplasma).", es: "En el citosol." }, difficulty: "facil" },
    { id: 11, question: { pt: "A glicólise precisa de oxigênio?", es: "¿Glucólisis requiere O₂?" }, answer: { pt: "Não, é um processo anaeróbico.", es: "No, es anaeróbica." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que é a gliconeogênese?", es: "¿Gluconeogénesis?" }, answer: { pt: "Síntese de glicose a partir de compostos não-carboidratos.", es: "Síntesis de glucosa." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que é a glicogênese?", es: "¿Glucogénesis?" }, answer: { pt: "Síntese de glicogênio a partir de glicose.", es: "Síntesis de glucógeno." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que é a glicogenólise?", es: "¿Glucogenólisis?" }, answer: { pt: "Quebra do glicogênio para liberar glicose.", es: "Degradación de glucógeno." }, difficulty: "facil" },
    { id: 15, question: { pt: "Qual hormônio reduz a glicemia?", es: "¿Qué hormona baja la glucemia?" }, answer: { pt: "Insulina.", es: "Insulina." }, difficulty: "facil" },
    { id: 16, question: { pt: "Qual hormônio aumenta a glicemia?", es: "¿Qué hormona sube la glucemia?" }, answer: { pt: "Glucagon.", es: "Glucagón." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é uma aldose?", es: "¿Qué es una aldosa?" }, answer: { pt: "Carboidrato com grupo funcional aldeído.", es: "Carbohidrato con aldehído." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que é uma cetose?", es: "¿Qué es una cetosa?" }, answer: { pt: "Carboidrato com grupo funcional cetona.", es: "Carbohidrato con cetona." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que é a celulose?", es: "¿Qué es la celulosa?" }, answer: { pt: "Polissacarídeo estrutural de plantas; não digerível por humanos.", es: "Fibra vegetal no digerible." }, difficulty: "facil" },
    { id: 20, question: { pt: "O que é um isômero?", es: "¿Qué es un isómero?" }, answer: { pt: "Moléculas com mesma fórmula química mas arranjos diferentes.", es: "Misma fórmula, diferente forma." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Qual a diferença entre glicose e galactose?", es: "¿Glucosa vs Galactosa?" }, answer: { pt: "São epímeros no carbono 4.", es: "Epímeros en C4." }, difficulty: "medio" },
    { id: 22, question: { pt: "O que é um epímero?", es: "¿Qué es un epímero?" }, answer: { pt: "Isômeros que diferem na configuração de apenas um carbono quiral.", es: "Difieren en un solo carbono." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que é um anômero?", es: "¿Qué es un anómero?" }, answer: { pt: "Isômero que se forma na ciclização (formas alfa e beta).", es: "Formas α y β tras ciclación." }, difficulty: "medio" },
    { id: 24, question: { pt: "Qual a enzima inicial da glicólise?", es: "¿Enzima inicial?" }, answer: { pt: "Hexoquinase (ou Glicoquinase no fígado).", es: "Hexoquinasa/Glucoquinasa." }, difficulty: "medio" },
    { id: 25, question: { pt: "O que é a PFK-1?", es: "¿Qué es PFK-1?" }, answer: { pt: "Fosfofrutoquinase-1; a principal enzima reguladora da glicólise.", es: "Principal reguladora glucólisis." }, difficulty: "medio" },
    { id: 26, question: { pt: "Qual o saldo líquido de ATP na glicólise?", es: "¿Saldo ATP glucólisis?" }, answer: { pt: "2 ATPs por molécula de glicose.", es: "2 ATPs." }, difficulty: "medio" },
    { id: 27, question: { pt: "Quantos NADHs são gerados na glicólise?", es: "¿NADH en glucólisis?" }, answer: { pt: "2 NADHs.", es: "2 NADHs." }, difficulty: "medio" },
    { id: 28, question: { pt: "O que é o Ciclo de Cori?", es: "¿Ciclo de Cori?" }, answer: { pt: "Reciclagem de lactato muscular em glicose no fígado.", es: "Lactato → Glucosa (hígado)." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que é a via das pentoses-fosfato?", es: "¿Vía de las pentosas?" }, answer: { pt: "Via que gera NADPH e ribose-5-fosfato.", es: "Genera NADPH y ribosa." }, difficulty: "medio" },
    { id: 30, question: { pt: "Qual a importância do NADPH?", es: "¿Importancia NADPH?" }, answer: { pt: "Usado em biossínteses redutoras e defesa contra radicais livres.", es: "Biosíntesis y defensa antioxidante." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que é a glicação?", es: "¿Qué es la glicación?" }, answer: { pt: "Ligação não enzimática de glicose a proteínas (ex.: HbA1c).", es: "Glucosa + proteínas (no enzimático)." }, difficulty: "medio" },
    { id: 32, question: { pt: "Qual a função da amilase?", es: "¿Amilasa?" }, answer: { pt: "Enzima que inicia a digestão do amido (salivar e pancreática).", es: "Digiere almidón." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que é a intolerância à lactose?", es: "¿Intolerancia lactosa?" }, answer: { pt: "Deficiência da enzima lactase, impedindo quebra de lactose.", es: "Falta de lactasa." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é a sacarose quimicamente?", es: "¿Sacarosa química?" }, answer: { pt: "Glicose + Frutose.", es: "Glucosa + Fructosa." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que é a maltose?", es: "¿Maltose?" }, answer: { pt: "Glicose + Glicose.", es: "Glucosa + Glucosa." }, difficulty: "medio" },
    { id: 36, question: { pt: "O que é o GLUT4?", es: "¿GLUT4?" }, answer: { pt: "Transportador de glicose dependente de insulina no músculo e gordura.", es: "Transportador insulino-dependiente." }, difficulty: "medio" },
    { id: 37, question: { pt: "Qual a diferença entre amilose e amilopectina?", es: "¿Amilosa vs Amilopectina?" }, answer: { pt: "Amilose é linear; amilopectina é ramificada.", es: "Linear vs Ramificada." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que é a mutarotação?", es: "¿Mutarrotación?" }, answer: { pt: "Interconversão entre os anômeros alfa e beta em solução.", es: "Interconversión α y β." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é um açúcar redutor?", es: "¿Azúcar reductor?" }, answer: { pt: "Açúcar que possui grupo aldeído ou cetona livre (capaz de reduzir agentes).", es: "Capaz de reducir agentes." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é a frutose?", es: "¿Frutosa?" }, answer: { pt: "Uma cetose de 6 carbonos (açúcar das frutas).", es: "Cetosa de las frutas." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "O que é a Frutose-2,6-bisfosfato?", es: "¿Fru-2,6-BP?" }, answer: { pt: "O mais potente ativador alostérico da PFK-1.", es: "Activador potente de PFK-1." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Qual o efeito da adrenalina na glicogenólise muscular?", es: "¿Adrenalina y músculo?" }, answer: { pt: "Estimula a quebra de glicogênio para fornecer energia rápida.", es: "Estimula degradación glucógeno." }, difficulty: "dificil" },
    { id: 43, question: { pt: "O que é a via de sinalização da insulina?", es: "¿Señalización insulina?" }, answer: { pt: "Usa receptores tirosina-quinase para ativar a translocação de GLUT4.", es: "Receptor tirosina quinasa." }, difficulty: "dificil" },
    { id: 44, question: { pt: "O que é a glicogênio fosforilase?", es: "¿Glucógeno fosforilasa?" }, answer: { pt: "Enzima que quebra ligações α(1→4) do glicogênio.", es: "Rompe enlaces α(1→4)." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que é a enzima de desramificação?", es: "¿Enzima desramificante?" }, answer: { pt: "Remove as ramificações α(1→6) do glicogênio.", es: "Rompe enlaces α(1→6)." }, difficulty: "dificil" },
    { id: 46, question: { pt: "O que é a glicogenina?", es: "¿Glucogenina?" }, answer: { pt: "Proteína que serve como iniciador (primer) para a síntese de glicogênio.", es: "Iniciador de glucogénesis." }, difficulty: "dificil" },
    { id: 47, question: { pt: "Qual a função da Glicose-6-Fosfatase?", es: "¿Glucosa-6-fosfatasa?" }, answer: { pt: "No fígado, remove o fosfato permitindo que a glicose saia para o sangue.", es: "Libera glucosa al sangre (hígado)." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que é a deficiência de G6PD?", es: "¿Deficiencia G6PD?" }, answer: { pt: "Causa hemólise por incapacidade de manter o glutation reduzido.", es: "Causa hemólisis (estrés oxidativo)." }, difficulty: "dificil" },
    { id: 49, question: { pt: "O que é a galactosemia?", es: "¿Galactosemia?" }, answer: { pt: "Incapacidade genética de metabolizar galactose; tóxica para o fígado e olhos.", es: "Falla metabólica de galactosa." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é a frutosemia (intolerância hereditária)?", es: "¿Fructosemia?" }, answer: { pt: "Deficiência de aldolase B; causa hipoglicemia grave após ingerir frutose.", es: "Deficiencia aldolasa B." }, difficulty: "dificil" },
    { id: 51, question: { pt: "O que é a síntese de UDP-glicose?", es: "¿Síntesis UDP-glucosa?" }, answer: { pt: "Forma ativada da glicose necessária para a glicogenese.", es: "Forma activa para glucogénesis." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Como a PFK-2 regula a glicólise?", es: "¿PFK-2?" }, answer: { pt: "Produz Frutose-2,6-BP em resposta à insulina.", es: "Produce activador de PFK-1." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é o efeito de Pasteur?", es: "¿Efecto Pasteur?" }, answer: { pt: "Inibição da glicólise pelo oxigênio (troca para respiração aeróbica).", es: "O₂ frena glucólisis." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é a glicólise aeróbica (Efeito Warburg)?", es: "¿Efecto Warburg?" }, answer: { pt: "Glicólise alta em células cancerígenas mesmo com oxigênio.", es: "Glucólisis alta en cáncer." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual o papel do transportador SGLT1?", es: "¿SGLT1?" }, answer: { pt: "Cotransportador Na⁺/glicose no intestino (transporte ativo secundário).", es: "Absorción activa de glucosa." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que são glicosaminoglicanos (GAGs)?", es: "¿GAGs?" }, answer: { pt: "Polissacarídeos longos e carregados (ex.: heparina) da matriz extracelular.", es: "Polisacáridos de la matriz." }, difficulty: "dificil" },
    { id: 57, question: { pt: "O que são proteoglicanos?", es: "¿Proteoglicanos?" }, answer: { pt: "Proteínas ligadas a GAGs; importantes para resistência e lubrificação.", es: "Proteína + GAGs." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que é a fibra dietética solúvel?", es: "¿Fibra soluble?" }, answer: { pt: "Carboidratos como pectina que retardam o esvaziamento gástrico.", es: "Retarda vaciado gástrico." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Qual a função da piruvato quinase?", es: "¿Piruvato quinasa?" }, answer: { pt: "Última enzima da glicólise; gera o segundo ATP por nível de substrato.", es: "Finaliza glucólisis." }, difficulty: "dificil" },
    { id: 60, question: { pt: "O que é a gliconeogênese a partir do glicerol?", es: "¿Gluconeogénesis/glicerol?" }, answer: { pt: "O glicerol das gorduras entra na via como di-hidroxiacetona-fosfato.", es: "Grasas como fuente de glucosa." }, difficulty: "dificil" }
];

const FC_BIOQ1_B905 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que são lipídios?", es: "¿Qué son los lípidos?" }, answer: { pt: "Moléculas orgânicas hidrofóbicas (insolúveis em água).", es: "Moléculas insolubles en agua." }, difficulty: "facil" },
    { id: 2, question: { pt: "Qual a principal função dos lipídios?", es: "¿Función principal?" }, answer: { pt: "Reserva de energia, isolamento térmico e componentes de membranas.", es: "Reserva de energía y membranas." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que é um ácido graxo saturado?", es: "¿Ácido graso saturado?" }, answer: { pt: "Ácido graxo sem duplas ligações entre os carbonos.", es: "Sin dobles enlaces." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que é um ácido graxo insaturado?", es: "¿Ácido graso insaturado?" }, answer: { pt: "Ácido graxo com uma ou mais duplas ligações.", es: "Con dobles enlaces." }, difficulty: "facil" },
    { id: 5, question: { pt: "O que são triacilgliceróis (triglicerídeos)?", es: "¿Qué son los triglicéridos?" }, answer: { pt: "Glicerol ligado a três ácidos graxos; principal forma de reserva de gordura.", es: "Glicerol + 3 ácidos grasos." }, difficulty: "facil" },
    { id: 6, question: { pt: "O que são fosfolipídios?", es: "¿Fosfolípidos?" }, answer: { pt: "Lipídios anfipáticos que formam a bicamada das membranas celulares.", es: "Componentes de membranas." }, difficulty: "facil" },
    { id: 7, question: { pt: "O que significa 'anfipático'?", es: "¿Anfipático?" }, answer: { pt: "Molécula com uma parte hidrofílica (afinidade por água) e outra hidrofóbica.", es: "Parte hidrofílica y parte hidrofóbica." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é o colesterol?", es: "¿Qué es el colesterol?" }, answer: { pt: "Esteroide essencial para membranas e precursor de hormônios e bile.", es: "Esteroide de membranas y hormonas." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é o HDL?", es: "¿HDL?" }, answer: { pt: "Lipoestimulante de alta densidade ('colesterol bom'); remove excesso de colesterol.", es: "Colesterol 'bueno'." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que é o LDL?", es: "¿LDL?" }, answer: { pt: "Lipoestimulante de baixa densidade ('colesterol ruim'); transporta colesterol para tecidos.", es: "Colesterol 'malo'." }, difficulty: "facil" },
    { id: 11, question: { pt: "O que é a beta-oxidação?", es: "¿Beta-oxidación?" }, answer: { pt: "Via metabólica de degradação de ácidos graxos para gerar acetil-CoA.", es: "Degradación de ácidos grasos." }, difficulty: "facil" },
    { id: 12, question: { pt: "Onde ocorre a beta-oxidação?", es: "¿Dónde ocorre?" }, answer: { pt: "Na matriz mitocondrial.", es: "En la matriz mitocondrial." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que são corpos cetônicos?", es: "¿Cuerpos cetónicos?" }, answer: { pt: "Moléculas produzidas pelo fígado durante jejum prolongado (ex.: acetoacetato).", es: "Energía alterna en ayuno." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que é um ácido graxo essencial?", es: "¿Ácido graso essencial?" }, answer: { pt: "Gordura que o corpo não produz e deve vir da dieta (ex.: Ômega-3).", es: "Debe venir de la dieta." }, difficulty: "facil" },
    { id: 15, question: { pt: "O que são micelas?", es: "¿Micelas?" }, answer: { pt: "Agregados esféricos de lipídios em solução aquosa.", es: "Agregados lipídicos en agua." }, difficulty: "facil" },
    { id: 16, question: { pt: "O que é a saponificação?", es: "¿Saponificación?" }, answer: { pt: "Reação de gorduras com base forte para produzir sabão.", es: "Producción de jabón." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que são ceras?", es: "¿Ceras?" }, answer: { pt: "Ésteres de ácidos graxos com álcoois de cadeia longa (impermeabilização).", es: "Lípidos impermeabilizantes." }, difficulty: "facil" },
    { id: 18, question: { pt: "Qual a função do tecido adiposo branco?", es: "¿Tejido adiposo blanco?" }, answer: { pt: "Armazenamento de energia em grandes gotas de gordura.", es: "Reserva de energía." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que são quilomírons?", es: "¿Quilomicrones?" }, answer: { pt: "Lipoproteínas que transportam gorduras da dieta do intestino para o corpo.", es: "Transporte de grasas de dieta." }, difficulty: "facil" },
    { id: 20, question: { pt: "O que é a lipólise?", es: "¿Lipólisis?" }, answer: { pt: "Quebra de triglicerídeos em ácidos graxos e glicerol.", es: "Degradación de grasas." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Como o ácido graxo entra na mitocôndria?", es: "¿Entrada a mitocondria?" }, answer: { pt: "Via lançadeira de Carnitina.", es: "Lanzadera de Carnitina." }, difficulty: "medio" },
    { id: 22, question: { pt: "O que é a Carnitina Palmitoiltransferase I (CPT-I)?", es: "¿CPT-I?" }, answer: { pt: "Enzima que regula a entrada de ácidos graxos na mitocôndria.", es: "Regula entrada a mitocondria." }, difficulty: "medio" },
    { id: 23, question: { pt: "Qual a enzima reguladora da síntese de ácidos graxos?", es: "¿Enzima síntesis grasas?" }, answer: { pt: "Acetil-CoA Carboxilase (ACC).", es: "Acetil-CoA Carboxilasa." }, difficulty: "medio" },
    { id: 24, question: { pt: "O que é o Malonil-CoA?", es: "¿Malonil-CoA?" }, answer: { pt: "Intermediário da síntese de gordura que inibe a beta-oxidação (inibe CPT-I).", es: "Inhibe beta-oxidación." }, difficulty: "medio" },
    { id: 25, question: { pt: "Quais os 3 corpos cetônicos?", es: "3 cuerpos cetónicos." }, answer: { pt: "Acetoacetato, Beta-hidroxibutirato e Acetona.", es: "Acetoacetato, β-hidroxibutirato, acetona." }, difficulty: "medio" },
    { id: 26, question: { pt: "Por que o fígado não usa corpos cetônicos?", es: "¿Por qué el hígado no los usa?" }, answer: { pt: "Falta a enzima tioforase para convertê-los de volta em energia.", es: "Falta enzima tioforasa." }, difficulty: "medio" },
    { id: 27, question: { pt: "O que é a HMG-CoA Redutase?", es: "¿HMG-CoA Reductasa?" }, answer: { pt: "Enzima reguladora da síntese de colesterol (alvo das estatinas).", es: "Regula síntesis colesterol." }, difficulty: "medio" },
    { id: 28, question: { pt: "Qual a função da bile na digestão de gorduras?", es: "¿Función de la bilis?" }, answer: { pt: "Emulsificação das gorduras, aumentando a área para ação da lipase.", es: "Emulsifica grasas." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que é a Lipase Lipoproteica (LPL)?", es: "¿LPL?" }, answer: { pt: "Enzima nos capilares que quebra triglicerídeos de quilomírons e VLDL.", es: "Libera ácidos grasos al tejido." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que é a VLDL?", es: "¿VLDL?" }, answer: { pt: "Lipoproteína de densidade muito baixa; transporta gordura do fígado.", es: "Transporta grasas del hígado." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que é a gordura Trans?", es: "¿Grasa Trans?" }, answer: { pt: "Gordura insaturada com hidrogênios em lados opostos; aumenta risco cardíaco.", es: "Aumenta riesgo cardíaco." }, difficulty: "medio" },
    { id: 32, question: { pt: "O que é o ácido palmítico?", es: "¿Ácido palmítico?" }, answer: { pt: "Ácido graxo saturado de 16 carbonos; produto final da síntese.", es: "Ácido graso de 16C." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que são esfingolipídios?", es: "¿Esfingolípidos?" }, answer: { pt: "Lipídios de membrana com base de esfingosina (comuns no cérebro).", es: "Lípidos del tejido nervioso." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é a esfingomielina?", es: "¿Esfingomielina?" }, answer: { pt: "Esfingolipídio que compõe a bainha de mielina dos neurônios.", es: "En vaina de mielina." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que são eicosanoides?", es: "¿Eicosanoides?" }, answer: { pt: "Sinalizadores derivados do ácido araquidônico (prostaglandinas, leucotrienos).", es: "Señalizadores lipídicos." }, difficulty: "medio" },
    { id: 36, question: { pt: "O que faz a Ciclooxigenase (COX)?", es: "¿COX?" }, answer: { pt: "Enzima que converte ácido araquidônico em prostaglandinas.", es: "Produce prostaglandinas." }, difficulty: "medio" },
    { id: 37, question: { pt: "Qual a função da Vitamina D?", es: "¿Vitamina D?" }, answer: { pt: "Regula o metabolismo de cálcio; sintetizada a partir do colesterol.", es: "Metabolismo de calcio." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que é o ácido araquidônico?", es: "¿Ácido araquidónico?" }, answer: { pt: "Precursor de 20 carbonos para síntese de inflamação.", es: "Precursor de inflamación." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é a aterosclerose?", es: "¿Aterosclerosis?" }, answer: { pt: "Formação de placas de gordura nas artérias.", es: "Placas en arterias." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é a esteatose hepática?", es: "¿Esteatosis?" }, answer: { pt: "Acúmulo excessivo de triglicerídeos no fígado ('fígado gorduroso').", es: "Grasa en el hígado." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Quantos ATPs gera a oxidação do Palmitato (16C)?", es: "¿ATP por Palmitato?" }, answer: { pt: "Cerca de 106-108 ATPs líquidos.", es: "~108 ATPs." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Qual o papel do Citrato na síntese de lipídios?", es: "¿Citrato y síntese?" }, answer: { pt: "Leva o Acetil-CoA da mitocôndria para o citosol.", es: "Lleva Acetil-CoA al citosol." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Como a insulina regula a síntese de gordura?", es: "¿Insulina y síntesis?" }, answer: { pt: "Ativa a Acetil-CoA Carboxilase via desfosforilação.", es: "Activa ACC." }, difficulty: "dificil" },
    { id: 44, question: { pt: "O que é a cetoacidose diabética?", es: "¿Cetoacidosis?" }, answer: { pt: "Acúmulo excessivo de corpos cetônicos que acidificam o sangue (Diabetes Tipo 1).", es: "Acidosis por cuerpos cetónicos." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que são as estatinas?", es: "¿Estatinas?" }, answer: { pt: "Medicamentos que inibem a HMG-CoA redutase para baixar o colesterol.", es: "Inhiben síntesis de colesterol." }, difficulty: "dificil" },
    { id: 46, question: { pt: "O que é a lipoproteína (a)?", es: "¿Lp(a)?" }, answer: { pt: "Variante do LDL que é fator de risco independente para infarto.", es: "Factor de riesgo cardíaco." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é o transporte reverso de colesterol?", es: "¿Transporte reverso?" }, answer: { pt: "Retorno do colesterol dos tecidos para o fígado via HDL.", es: "Tejidos → Hígado (HDL)." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que é o LCAT?", es: "¿LCAT?" }, answer: { pt: "Enzima que esterifica colesterol no HDL.", es: "Esterifica colesterol." }, difficulty: "dificil" },
    { id: 49, question: { pt: "O que é a Doença de Tay-Sachs?", es: "¿Tay-Sachs?" }, answer: { pt: "Erro inato no metabolismo de gangliosídios (esfingolipídios).", es: "Falla en esfingolípidos." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é a Adrenoleucodistrofia?", es: "¿Adrenoleucodistrofia?" }, answer: { pt: "Defeito no transporte de ácidos graxos de cadeia muito longa para o peroxissomo.", es: "Falla en grasas de cadena larga." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Qual a função do NADPH na síntese de ácidos graxos?", es: "¿NADPH en síntesis?" }, answer: { pt: "Fornece elétrons para as reações de redução da Ácido Graxo Sintase.", es: "Donante de electrones." }, difficulty: "dificil" },
    { id: 52, question: { pt: "O que é o complexo Ácido Graxo Sintase (FAS)?", es: "¿FAS?" }, answer: { pt: "Grande complexo multienzimático que constrói a cadeia de carbono.", es: "Sintetiza cadena de grasas." }, difficulty: "dificil" },
    { id: 53, question: { pt: "Qual a função dos ácidos biliares primários?", es: "¿Bilis primaria?" }, answer: { pt: "Derivados do colesterol (Cólico e Quenodesoxicólico) que auxiliam na digestão.", es: "Digestión de lípidos." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é a circulação entero-hepática de sais biliares?", es: "¿Circulación enterohepática?" }, answer: { pt: "Reabsorção de sais biliares no íleo para retorno ao fígado.", es: "Reciclaje de bilis." }, difficulty: "dificil" },
    { id: 55, question: { pt: "O que são as Jangadas Lipídicas (Lipid Rafts)?", es: "¿Lipid Rafts?" }, answer: { pt: "Microdomínios na membrana ricos em colesterol e esfingolipídios.", es: "Microdominios de membrana." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é o tromboxano A2?", es: "¿Tromboxano A2?" }, answer: { pt: "Eicosanoide que promove a agregação plaquetária.", es: "Agregación plaquetaria." }, difficulty: "dificil" },
    { id: 57, question: { pt: "O que é a prostaciclina?", es: "¿Prostaciclina?" }, answer: { pt: "Eicosanoide que inibe a agregação plaquetária (oposto do tromboxano).", es: "Inhibe agregación." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que é a oxidação alfa?", es: "¿Oxidación alfa?" }, answer: { pt: "Via alternativa para ácidos graxos ramificados (ex.: ácido fitânico).", es: "Grasas ramificadas." }, difficulty: "dificil" },
    { id: 59, question: { pt: "O que é a oxidação omega?", es: "¿Oxidación omega?" }, answer: { pt: "Ocorre no retículo endoplasmático quando a beta-oxidação falha.", es: "Vía de emergencia." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Qual a função da Proteína de Transferência de Éster de Colesterol (CETP)?", es: "¿CETP?" }, answer: { pt: "Troca triglicerídeos de VLDL por ésteres de colesterol de HDL.", es: "Intercambio entre lipoproteínas." }, difficulty: "dificil" }
];

// Global flashcard database registration
window.FC_BIOQ1 = {
    B901: FC_BIOQ1_B901,
    B902: FC_BIOQ1_B902,
    B903: FC_BIOQ1_B903,
    B904: FC_BIOQ1_B904,
    B905: FC_BIOQ1_B905
};

if (typeof window !== 'undefined') {
    window.FC_BIOQ1_B901 = FC_BIOQ1_B901;
    window.FC_BIOQ1_B902 = FC_BIOQ1_B902;
    window.FC_BIOQ1_B903 = FC_BIOQ1_B903;
    window.FC_BIOQ1_B904 = FC_BIOQ1_B904;
    window.FC_BIOQ1_B905 = FC_BIOQ1_B905;
}
