// Flashcards — Bioquímica II — S4
// Bloco 1: Metabolismo de Lipídios

const FC_BIOQ2_S4_B1 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "Qual a principal reserva de energia do corpo humano?", es: "¿Cuál es la principal reserva de energía del cuerpo humano?" }, answer: { pt: "Triacilgliceróis (gorduras) armazenados no tecido adiposo.", es: "Triacilgliceroles almacenados en el tejido adiposo." }, difficulty: "facil" },
    { id: 2, question: { pt: "Onde ocorre a beta-oxidação dos ácidos graxos?", es: "¿Dónde ocurre la beta-oxidación de los ácidos grasos?" }, answer: { pt: "Na matriz mitocondrial.", es: "En la matriz mitocondrial." }, difficulty: "facil" },
    { id: 3, question: { pt: "Qual é o produto final de cada ciclo da beta-oxidação?", es: "¿Cuál es el producto final de cada ciclo de beta-oxidación?" }, answer: { pt: "Acetil-CoA, NADH e FADH2.", es: "Acetil-CoA, NADH y FADH2." }, difficulty: "facil" },
    { id: 4, question: { pt: "Qual a função dos sais biliares na digestão de gorduras?", es: "¿Cuál es la función de las sales biliares en la digestión?" }, answer: { pt: "Emulsificar as gorduras para aumentar a área de ação das lipases.", es: "Emulsionar las grasas para aumentar la acción de las lipasas." }, difficulty: "facil" },
    { id: 5, question: { pt: "O que são ácidos graxos essenciais?", es: "¿Qué son los ácidos grasos esenciales?" }, answer: { pt: "Ácidos graxos que o corpo não sintetiza e devem ser obtidos na dieta (ex: Ômega-3 e 6).", es: "Ácidos grasos que el cuerpo no sintetiza (ej: Omega-3 y 6)." }, difficulty: "facil" },
    { id: 6, question: { pt: "Qual lipoproteína é conhecida como 'bom colesterol'?", es: "¿Qué lipoproteína es el 'colesterol bueno'?" }, answer: { pt: "HDL (Lipoproteína de Alta Densidade).", es: "HDL (Lipoproteína de Alta Densidad)." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual lipoproteína é conhecida como 'mau colesterol'?", es: "¿Qué lipoproteína es el 'colesterol malo'?" }, answer: { pt: "LDL (Lipoproteína de Baixa Densidade).", es: "LDL (Lipoproteína de Baja Densidad)." }, difficulty: "facil" },
    { id: 8, question: { pt: "Onde ocorre a síntese de ácidos graxos?", es: "¿Dónde ocurre la síntesis de ácidos grasos?" }, answer: { pt: "No citosol das células, principalmente fígado e tecido adiposo.", es: "En el citosol de las células." }, difficulty: "facil" },
    { id: 9, question: { pt: "Qual hormônio estimula a lipólise (quebra de gordura)?", es: "¿Qué hormona estimula la lipólisis?" }, answer: { pt: "Glucagon e Adrenalina.", es: "Glucagón y Adrenalina." }, difficulty: "facil" },
    { id: 10, question: { pt: "Qual hormônio estimula a lipogênese (formação de gordura)?", es: "¿Qué hormona estimula la lipogénesis?" }, answer: { pt: "Insulina.", es: "Insulina." }, difficulty: "facil" },
    { id: 11, question: { pt: "O que é um triacilglicerol?", es: "¿Qué es un triacilglicerol?" }, answer: { pt: "Uma molécula de glicerol ligada a três ácidos graxos.", es: "Glicerol unido a tres ácidos grasos." }, difficulty: "facil" },
    { id: 12, question: { pt: "Qual a função dos quilomícrons?", es: "¿Cuál es la función de los quilomicrones?" }, answer: { pt: "Transportar lipídios da dieta do intestino para os tecidos periféricos.", es: "Transportar lípidos de la dieta del intestino a los tejidos." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que são corpos cetônicos?", es: "¿Qué son los cuerpos cetónicos?" }, answer: { pt: "Combustíveis alternativos produzidos no fígado a partir do acetil-CoA em jejum prolongado.", es: "Combustibles producidos en el hígado en ayuno prolongado." }, difficulty: "facil" },
    { id: 14, question: { pt: "Onde os corpos cetônicos são sintetizados?", es: "¿Dónde se sintetizan los cuerpos cetónicos?" }, answer: { pt: "No fígado (mitocôndria hepática).", es: "En el hígado." }, difficulty: "facil" },
    { id: 15, question: { pt: "O cérebro pode usar ácidos graxos como energia?", es: "¿El cerebro puede usar ácidos grasos como energía?" }, answer: { pt: "Não, eles não atravessam a barreira hematoencefálica (o cérebro usa glicose ou corpos cetônicos).", es: "No, el cerebro usa glucosa o cuerpos cetónicos." }, difficulty: "facil" },
    { id: 16, question: { pt: "Qual o principal precursor da síntese de colesterol?", es: "¿Cuál es el precursor de la síntesis de colesterol?" }, answer: { pt: "Acetil-CoA.", es: "Acetil-CoA." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é a esteatose hepática?", es: "¿Qué es la esteatosis hepática?" }, answer: { pt: "Acúmulo excessivo de gordura no fígado.", es: "Acumulación de grasa en el hígado." }, difficulty: "facil" },
    { id: 18, question: { pt: "Qual enzima inicia a digestão de lipídios na boca?", es: "¿Qué enzima inicia la digestión de lípidos en la boca?" }, answer: { pt: "Lipase lingual.", es: "Lipasa lingual." }, difficulty: "facil" },
    { id: 19, question: { pt: "O excesso de carboidratos pode virar gordura?", es: "¿El exceso de carbohidratos puede volverse grasa?" }, answer: { pt: "Sim, através da via de síntese de ácidos graxos no citosol.", es: "Sí, mediante la síntesis de ácidos grasos." }, difficulty: "facil" },
    { id: 20, question: { pt: "Qual a principal função do colesterol nas membranas?", es: "¿Cuál es la función del colesterol en las membranas?" }, answer: { pt: "Regular a fluidez da membrana plasmática.", es: "Regular la fluidez de la membrana plasmática." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Qual é a enzima marcapasso da síntese de ácidos graxos?", es: "¿Cuál es la enzima limitante de la síntesis de ácidos grasos?" }, answer: { pt: "Acetil-CoA Carboxilase (ACC).", es: "Acetil-CoA Carboxilasa (ACC)." }, difficulty: "medio" },
    { id: 22, question: { pt: "Qual o papel da Carnitina no metabolismo lipídico?", es: "¿Cuál es el papel de la Carnitina?" }, answer: { pt: "Transportar ácidos graxos de cadeia longa para dentro da mitocôndria.", es: "Transportar ácidos grasos de cadena larga a la mitocondria." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que inibe a enzima CPT-I (Carnitina Palmitoiltransferase I)?", es: "¿Qué inhibe a la CPT-I?" }, answer: { pt: "Malonil-CoA (precursor da síntese de ácidos graxos).", es: "Malonil-CoA." }, difficulty: "medio" },
    { id: 24, question: { pt: "Qual o papel da Lipase Sensível a Hormônio (HSL)?", es: "¿Cuál es el papel de la Lipasa Sensible a Hormonas?" }, answer: { pt: "Mobilizar triacilgliceróis do tecido adiposo durante o jejum.", es: "Movilizar triacilgliceroles del tejido adiposo." }, difficulty: "medio" },
    { id: 25, question: { pt: "Qual a função da Lipoproteína Lipase (LPL)?", es: "¿Cuál es la función de la Lipoproteína Lipasa (LPL)?" }, answer: { pt: "Degradar triacilgliceróis de quilomícrons e VLDL nos capilares dos tecidos.", es: "Degradar triacilgliceroles en capilares." }, difficulty: "medio" },
    { id: 26, question: { pt: "O que é a via de transporte reverso do colesterol?", es: "¿Qué es el transporte reverso de colesterol?" }, answer: { pt: "O transporte de colesterol dos tecidos periféricos de volta ao fígado, realizado pelo HDL.", es: "Transporte de colesterol de tejidos al hígado por el HDL." }, difficulty: "medio" },
    { id: 27, question: { pt: "Qual o papel da enzima HMG-CoA Redutase?", es: "¿Cuál es el papel de la HMG-CoA Reductasa?" }, answer: { pt: "É a enzima marcapasso da síntese de colesterol.", es: "Enzima limitante de la síntesis de colesterol." }, difficulty: "medio" },
    { id: 28, question: { pt: "Quais são os três principais corpos cetônicos?", es: "¿Cuáles son los tres principales cuerpos cetónicos?" }, answer: { pt: "Acetoacetato, 3-hidroxibutirato e Acetona.", es: "Acetoacetato, 3-hidroxibutirato y Acetona." }, difficulty: "medio" },
    { id: 29, question: { pt: "Por que o fígado não consegue utilizar os corpos cetônicos que produz?", es: "¿Por qué el hígado no usa los cuerpos cetónicos que produce?" }, answer: { pt: "Porque carece da enzima tioforase (ß-cetoacil-CoA transferase).", es: "Porque carece de la enzima tioforasa." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que é o ciclo de Randle?", es: "¿Qué es el ciclo de Randle?" }, answer: { pt: "Competição entre glicose e ácidos graxos pela oxidação nos tecidos (inibição mútua).", es: "Competición entre glucosa y ácidos grasos." }, difficulty: "medio" },
    { id: 31, question: { pt: "Qual a função da Apo B-100?", es: "¿Cuál es la función de la Apo B-100?" }, answer: { pt: "Proteína estrutural do VLDL e LDL; reconhecida pelo receptor de LDL.", es: "Proteína estructural de VLDL y LDL." }, difficulty: "medio" },
    { id: 32, question: { pt: "Qual a função da Apo A-I?", es: "¿Cuál es la función de la Apo A-I?" }, answer: { pt: "Principal apoproteína do HDL; ativa a enzima LCAT.", es: "Principal apoproteína del HDL; activa LCAT." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que faz a enzima LCAT (Lecitina-Colesterol Aciltransferase)?", es: "¿Qué hace la enzima LCAT?" }, answer: { pt: "Esterifica o colesterol livre na superfície do HDL para que ele entre no core da partícula.", es: "Esterifica el colesterol en el HDL." }, difficulty: "medio" },
    { id: 34, question: { pt: "Como a insulina regula a Acetil-CoA Carboxilase (ACC)?", es: "¿Cómo regula la insulina a la ACC?" }, answer: { pt: "Através da desfosforilação, ativando a enzima.", es: "Mediante desfosforilación, activándola." }, difficulty: "medio" },
    { id: 35, question: { pt: "Qual cofator é essencial para a Acetil-CoA Carboxilase?", es: "¿Qué cofactor es esencial para la ACC?" }, answer: { pt: "Biotina (Vitamina B7).", es: "Biotina (Vitamina B7)." }, difficulty: "medio" },
    { id: 36, question: { pt: "O que acontece com o excesso de Acetil-CoA na mitocôndria durante o jejum?", es: "¿Qué pasa con el exceso de Acetil-CoA en ayuno?" }, answer: { pt: "É desviado para a síntese de corpos cetônicos (cetogênese).", es: "Se desvía a la síntesis de cuerpos cetónicos." }, difficulty: "medio" },
    { id: 37, question: { pt: "Qual a função do dolicol-fosfato?", es: "¿Cuál es la función del dolicol-fosfato?" }, answer: { pt: "Transportador de oligossacarídeos na síntese de glicoproteínas (derivado da via do mevalonato).", es: "Transportador en la síntesis de glicoproteínas." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que são leucotrienos?", es: "¿Qué son los leucotrienos?" }, answer: { pt: "Mediadores inflamatórios derivados do ácido araquidônico pela via da lipooxigenase.", es: "Mediadores derivados del ácido araquidónico." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que são prostaglandinas?", es: "¿Qué son las prostaglandinas?" }, answer: { pt: "Eicosanoides derivados do ácido araquidônico pela via da ciclooxigenase (COX).", es: "Eicosanoides derivados por la vía COX." }, difficulty: "medio" },
    { id: 40, question: { pt: "Como as estatinas reduzem o colesterol?", es: "¿Cómo las estatinas reducen el colesterol?" }, answer: { pt: "Inibindo competitivamente a enzima HMG-CoA Redutase.", es: "Inhibiendo la HMG-CoA Reductasa." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Como o Acetil-CoA sai da mitocôndria para a síntese de ácidos graxos?", es: "¿Cómo sale el Acetil-CoA para la síntesis?" }, answer: { pt: "Na forma de Citrato (condensação com oxaloacetato), que sai pelo transportador de tricarboxilato.", es: "En forma de Citrato." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Qual enzima cliva o citrato no citosol para regenerar Acetil-CoA?", es: "¿Qué enzima cliva el citrato en el citosol?" }, answer: { pt: "ATP-Citrato Liase.", es: "ATP-Citrato Liasa." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Qual a importância da enzima málica na lipogênese?", es: "¿Importancia de la enzima málica?" }, answer: { pt: "Fornece NADPH necessário para a redução na síntese de ácidos graxos.", es: "Provee NADPH para la síntesis." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Como ocorre a ativação dos ácidos graxos para a oxidação?", es: "¿Cómo se activan los ácidos grasos?" }, answer: { pt: "Ligação ao Coenzima A pela enzima Acil-CoA Sintetase (gasto de 2 ATP equivalents).", es: "Unión a CoA por la Acil-CoA Sintetasa." }, difficulty: "dificil" },
    { id: 45, question: { pt: "Qual a função da proteína desacopladora (UCP-1 ou termogenina)?", es: "¿Función de la termogenina?" }, answer: { pt: "Dissipar o gradiente de prótons na mitocôndria do tecido adiposo marrom para gerar calor.", es: "Generar calor en tejido adiposo marrón." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Qual o defeito molecular na Doença de Tay-Sachs?", es: "¿Defecto en Tay-Sachs?" }, answer: { pt: "Deficiência da Hexosaminidase A, levando ao acúmulo de gangliosídio GM2.", es: "Deficiencia de Hexosaminidasa A." }, difficulty: "dificil" },
    { id: 47, question: { pt: "Qual o defeito molecular na Doença de Gaucher?", es: "¿Defecto en Gaucher?" }, answer: { pt: "Deficiência da Glucocerebrosidase (ß-glicosidase), acúmulo de glicocerebrosídio.", es: "Deficiencia de Glucocerebrosidasa." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que é a adrenoleucodistrofia (ALD)?", es: "¿Qué es la adrenoleucodistrofia?" }, answer: { pt: "Doença peroxissomal ligada ao X; falha no transporte de ácidos graxos de cadeia muito longa (VLCFA).", es: "Falla en el transporte de VLCFA." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Como a oxidação de ácidos graxos de cadeia ímpar difere da cadeia par?", es: "¿Diferencia en cadena impar?" }, answer: { pt: "Produz Propionil-CoA no último ciclo, que é convertido em Succinil-CoA.", es: "Produce Propionil-CoA." }, difficulty: "dificil" },
    { id: 50, question: { pt: "Qual enzima converte Propionil-CoA em Metilmalonil-CoA e qual seu cofator?", es: "¿Qué enzima y cofactor?" }, answer: { pt: "Propionil-CoA Carboxilase; usa Biotina.", es: "Propionil-CoA Carboxilasa; usa Biotina." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Qual enzima converte Metilmalonil-CoA em Succinil-CoA e qual seu cofator?", es: "¿Qué enzima y cofactor?" }, answer: { pt: "Metilmalonil-CoA Mutase; usa Vitamina B12 (Cobalamina).", es: "Metilmalonil-CoA Mutasa; usa Vitamina B12." }, difficulty: "dificil" },
    { id: 52, question: { pt: "O que é a alfa-oxidação e onde ocorre?", es: "¿Qué es alfa-oxidación?" }, answer: { pt: "Oxidação de ácidos graxos ramificados (como ácido fitânico) nos peroxissomos.", es: "Oxidación de ácidos ramificados." }, difficulty: "dificil" },
    { id: 53, question: { pt: "Qual a causa da Doença de Refsum?", es: "¿Causa de la Enfermedad de Refsum?" }, answer: { pt: "Deficiência na alfa-oxidação (Fitanoil-CoA hidroxilase), acúmulo de ácido fitânico.", es: "Deficiencia en alfa-oxidación." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é a omega-oxidação?", es: "¿Qué es omega-oxidación?" }, answer: { pt: "Via alternativa no retículo endoplasmático que produz ácidos dicarboxílicos.", es: "Vía alternativa en el RE." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual o papel do receptor scavenger SR-B1 no HDL?", es: "¿Papel del SR-B1?" }, answer: { pt: "Mediar a captação seletiva de ésteres de colesterol do HDL pelo fígado.", es: "Captación de ésteres de colesterol." }, difficulty: "dificil" },
    { id: 56, question: { pt: "Como a proteína CETP (Proteína de Transferência de Ésteres de Colesterol) atua?", es: "¿Cómo actúa la CETP?" }, answer: { pt: "Troca ésteres de colesterol do HDL por triacilgliceróis do VLDL/LDL.", es: "Intercambia ésteres por triacilgliceroles." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Qual o mecanismo de ação da enzima ACAT (Acil-CoA:Colesterol Aciltransferase)?", es: "¿Mecanismo de la ACAT?" }, answer: { pt: "Esterifica o colesterol dentro das células para armazenamento em gotículas lipídicas.", es: "Esterifica colesterol intracelular." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que caracteriza a Hipercolesterolemia Familiar Tipo IIa?", es: "¿Qué caracteriza la Tipo IIa?" }, answer: { pt: "Defeito funcional nos receptores de LDL, causando níveis altíssimos de LDL plasmático.", es: "Defecto en receptores de LDL." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Como a regulação por SREBP (Sterol Regulatory Element-Binding Protein) funciona?", es: "¿Cómo funciona SREBP?" }, answer: { pt: "Fator de transcrição que ativa genes de síntese de colesterol e receptores de LDL quando os níveis de esteróis estão baixos.", es: "Activa genes cuando esteroles bajan." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Qual a função da proteína PCSK9 no metabolismo do LDL?", es: "¿Función de PCSK9?" }, answer: { pt: "Promover a degradação lisossomal dos receptores de LDL, aumentando o LDL circulante.", es: "Degrada receptores de LDL." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_BIOQ2_S4_B1 = FC_BIOQ2_S4_B1;
}

// Bloco 2: Metabolismo de Aminoácidos e Nitrogênio
const FC_BIOQ2_S4_B2 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que é um aminoácido essencial?", es: "¿Qué es un aminoácido esencial?" }, answer: { pt: "Aquele que o organismo não sintetiza e deve ser obtido na dieta.", es: "Aquel que el organismo no sintetiza." }, difficulty: "facil" },
    { id: 2, question: { pt: "Qual a principal via de excreção do nitrogênio em humanos?", es: "¿Cuál es la principal vía de excreción de nitrógeno?" }, answer: { pt: "Ciclo da Ureia.", es: "Ciclo de la Urea." }, difficulty: "facil" },
    { id: 3, question: { pt: "Onde ocorre o ciclo da ureia?", es: "¿Dónde ocurre el ciclo de la urea?" }, answer: { pt: "Exclusivamente no fígado (mitocôndria e citosol).", es: "En el hígado." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que é a transaminação?", es: "¿Qué es la transaminación?" }, answer: { pt: "Transferência do grupo amino de um aminoácido para um cetoácido.", es: "Transferencia del grupo amino." }, difficulty: "facil" },
    { id: 5, question: { pt: "Quais são as principais transaminases clínicas?", es: "¿Cuáles son las principales transaminasas?" }, answer: { pt: "ALT (TGP) e AST (TGO).", es: "ALT y AST." }, difficulty: "facil" },
    { id: 6, question: { pt: "Qual aminoácido é o principal transportador de nitrogênio no sangue?", es: "¿Qué aminoácido transporta nitrógeno en sangre?" }, answer: { pt: "Glutamina.", es: "Glutamina." }, difficulty: "facil" },
    { id: 7, question: { pt: "O que são aminoácidos glicogênicos?", es: "¿Qué son aminoácidos glucogénicos?" }, answer: { pt: "Aqueles que podem ser convertidos em glicose.", es: "Pueden convertirse en glucosa." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que são aminoácidos cetogênicos?", es: "¿Qué son aminoácidos cetogénicos?" }, answer: { pt: "Aqueles que são convertidos em corpos cetônicos ou acetil-CoA.", es: "Se convierten en cuerpos cetónicos." }, difficulty: "facil" },
    { id: 9, question: { pt: "Qual o principal produto da degradação do grupo amino?", es: "¿Cuál es el producto de la degradación del grupo amino?" }, answer: { pt: "Amônia (NH3), que é tóxica.", es: "Amoníaco (NH3)." }, difficulty: "facil" },
    { id: 10, question: { pt: "A ureia é produzida em qual órgão?", es: "¿Dónde se produce la urea?" }, answer: { pt: "Fígado.", es: "Hígado." }, difficulty: "facil" },
    { id: 11, question: { pt: "Como a ureia é eliminada?", es: "¿Cómo se elimina la urea?" }, answer: { pt: "Pelos rins, na urina.", es: "Por los riñones." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que é o balanço nitrogenado positivo?", es: "¿Qué es balance nitrogenado positivo?" }, answer: { pt: "Ingestão de nitrogênio maior que a excreção (ocorre no crescimento).", es: "Ingesta > excreción." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que é o balanço nitrogenado negativo?", es: "¿Qué es balance nitrogenado negativo?" }, answer: { pt: "Excreção de nitrogênio maior que a ingestão (ocorre na desnutrição ou trauma).", es: "Excreción > ingesta." }, difficulty: "facil" },
    { id: 14, question: { pt: "Qual a função do ácido gástrico na digestão de proteínas?", es: "¿Función del ácido en la digestión proteica?" }, answer: { pt: "Desnaturar proteínas e ativar o pepsinogênio em pepsina.", es: "Desnaturalizar proteínas y activar pepsina." }, difficulty: "facil" },
    { id: 15, question: { pt: "Onde ocorre a maior parte da absorção de aminoácidos?", es: "¿Dónde ocurre la absorción de aminoácidos?" }, answer: { pt: "No intestino delgado.", es: "Intestino delgado." }, difficulty: "facil" },
    { id: 16, question: { pt: "O que é o pool de aminoácidos?", es: "¿Qué es el pool de aminoácidos?" }, answer: { pt: "Reserva temporária de aminoácidos livres no sangue e tecidos.", es: "Reserva de aminoácidos libres." }, difficulty: "facil" },
    { id: 17, question: { pt: "Qual a enzima que inicia a digestão de proteínas no estômago?", es: "¿Qué enzima inicia la digestión en el estómago?" }, answer: { pt: "Pepsina.", es: "Pepsina." }, difficulty: "facil" },
    { id: 18, question: { pt: "Qual o papel das proteases pancreáticas?", es: "¿Papel de las proteasas pancreáticas?" }, answer: { pt: "Quebrar polipeptídeos em oligopeptídeos e aminoácidos no duodeno.", es: "Romper polipéptidos en el duodeno." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que é a uremia?", es: "¿Qué es la uremia?" }, answer: { pt: "Aumento patológico dos níveis de ureia no sangue.", es: "Aumento de urea en sangre." }, difficulty: "facil" },
    { id: 20, question: { pt: "O nitrogênio do corpo humano vem principalmente de onde?", es: "¿De dónde viene el nitrógeno humano?" }, answer: { pt: "Das proteínas da dieta.", es: "De las proteínas de la dieta." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Qual enzima é a marcapasso do ciclo da ureia?", es: "¿Cuál es la enzima limitante del ciclo de la urea?" }, answer: { pt: "Carbamoil-fosfato sintetase I (CPS I).", es: "Carbamoil-fosfato sintetasa I." }, difficulty: "medio" },
    { id: 22, question: { pt: "Qual ativador alostérico é essencial para a CPS I?", es: "¿Qué activador es esencial para CPS I?" }, answer: { pt: "N-acetilglutamato (NAG).", es: "N-acetilglutamato (NAG)." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que é a desaminação oxidativa do glutamato?", es: "¿Qué es la desaminación oxidativa?" }, answer: { pt: "Liberação de amônia do glutamato pela Glutamato Desidrogenase.", es: "Liberación de amoníaco por la Glutamato Deshidrogenasa." }, difficulty: "medio" },
    { id: 24, question: { pt: "Qual o papel do piridoxal-fosfato (Vitamina B6) no metabolismo de aminoácidos?", es: "¿Papel de la Vitamina B6?" }, answer: { pt: "Cofator essencial para todas as reações de transaminação.", es: "Cofactor de las transaminaciones." }, difficulty: "medio" },
    { id: 25, question: { pt: "Descreva o Ciclo da Alanina (Glicose-Alanina).", es: "¿Qué es el Ciclo de la Alanina?" }, answer: { pt: "Transporte de nitrogênio do músculo para o fígado na forma de alanina; o fígado produz glicose e ureia.", es: "Transporte de nitrógeno del músculo al hígado." }, difficulty: "medio" },
    { id: 26, question: { pt: "Qual a causa da Fenilcetonúria (PKU)?", es: "¿Causa de la Fenilcetonuria?" }, answer: { pt: "Deficiência da enzima Fenilalanina Hidroxilase.", es: "Deficiencia de Fenilalanina Hidroxilasa." }, difficulty: "medio" },
    { id: 27, question: { pt: "Qual o tratamento principal para Fenilcetonúria?", es: "¿Tratamiento para PKU?" }, answer: { pt: "Dieta restrita em fenilalanina e suplementada com tirosina.", es: "Dieta baja en fenilalanina." }, difficulty: "medio" },
    { id: 28, question: { pt: "O que é o Albinismo?", es: "¿Qué es el Albinismo?" }, answer: { pt: "Deficiência na síntese de melanina a partir da tirosina (enzima Tirosinase).", es: "Defecto en síntesis de melanina." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que é a Alcaptonúria?", es: "¿Qué es la Alcaptonuria?" }, answer: { pt: "Deficiência da enzima Homogentisato Oxidase; urina escurece ao ar livre.", es: "Deficiencia de Homogentisato Oxidasa." }, difficulty: "medio" },
    { id: 30, question: { pt: "Quais aminoácidos são puramente cetogênicos?", es: "¿Qué aminoácidos son solo cetogénicos?" }, answer: { pt: "Leucina e Lisina.", es: "Leucina y Lisina." }, difficulty: "medio" },
    { id: 31, question: { pt: "Qual o precursor do neurotransmissor Serotonina?", es: "¿Precursor de la Serotonina?" }, answer: { pt: "Triptofano.", es: "Triptófano." }, difficulty: "medio" },
    { id: 32, question: { pt: "Quais são os precursores das Catecolaminas (Dopamina, Adrenalina)?", es: "¿Precursores de Catecolaminas?" }, answer: { pt: "Fenilalanina e Tirosina.", es: "Fenilalanina y Tirosina." }, difficulty: "medio" },
    { id: 33, question: { pt: "Qual aminoácido é precursor do Óxido Nítrico (NO)?", es: "¿Precursor del Óxido Nítrico?" }, answer: { pt: "Arginina.", es: "Arginina." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é a Hiperamonemia?", es: "¿Qué es la Hiperamonemia?" }, answer: { pt: "Acúmulo de amônia no sangue, altamente tóxico para o sistema nervoso.", es: "Exceso de amoníaco en sangre." }, difficulty: "medio" },
    { id: 35, question: { pt: "Como a amônia causa toxicidade cerebral?", es: "¿Cómo el amoníaco daña el cerebro?" }, answer: { pt: "Consumo excessivo de alfa-cetoglutarato para formar glutamato, paralisando o Ciclo de Krebs.", es: "Agota el alfa-cetoglutarato del Ciclo de Krebs." }, difficulty: "medio" },
    { id: 36, question: { pt: "Qual a função da Glutamina Sintetase?", es: "¿Função da Glutamina Sintetase?" }, answer: { pt: "Fixar amônia livre em glutamato para formar glutamina (transporte seguro).", es: "Fija amoníaco en glutamato." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é a Doença da Urina de Xarope de Bordo?", es: "¿Qué es la enfermedad de orina de jarabe de arce?" }, answer: { pt: "Deficiência na desidrogenase de cetoácidos de cadeia ramificada (Leucina, Isoleucina, Valina).", es: "Defecto en aminoácidos ramificados." }, difficulty: "medio" },
    { id: 38, question: { pt: "Qual aminoácido é precursor da Histamina?", es: "¿Precursor de la Histamina?" }, answer: { pt: "Histidina.", es: "Histidina." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é o glutatião (GSH) e quais aminoácidos o compõem?", es: "¿Qué es el glutatión?" }, answer: { pt: "Principal antioxidante celular; composto por Glutamato, Cisteína e Glicina.", es: "Antioxidante celular (Glu-Cis-Gli)." }, difficulty: "medio" },
    { id: 40, question: { pt: "Qual o papel do S-adenosilmetionina (SAM)?", es: "¿Papel del SAM?" }, answer: { pt: "Principal doador de grupos metil nas reações biológicas.", es: "Donador de grupos metilo." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a reação da Ornitina Transcarbamoilase (OTC).", es: "¿Qué hace la OTC?" }, answer: { pt: "Condensa Carbamoil-fosfato com Ornitina para formar Citrulina.", es: "Une Carbamoil-fosfato y Ornitina." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Qual a única enzima do ciclo da ureia que é mitocondrial?", es: "¿Qué enzimas del ciclo son mitocondriales?" }, answer: { pt: "CPS I e Ornitina Transcarbamoilase (OTC).", es: "CPS I y OTC." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Como o Ciclo da Ureia se conecta ao Ciclo de Krebs?", es: "¿Conexión urea-Krebs?" }, answer: { pt: "Através do Fumarato (produzido na quebra do argininosuccinato).", es: "Mediante el Fumarato." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Qual a causa da Homocistinúria?", es: "¿Causa de la Homocistinuria?" }, answer: { pt: "Deficiência da Cistatironina beta-sintetase (necessita de Vit B6).", es: "Deficiencia de Cistatironina beta-sintetasa." }, difficulty: "dificil" },
    { id: 45, question: { pt: "Qual a importância clínica da Homocisteína elevada?", es: "¿Importancia de la Homocisteína?" }, answer: { pt: "Aumenta o risco de doenças cardiovasculares e trombose.", es: "Riesgo cardiovascular y trombosis." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Como o metabolismo de aminoácidos contribui para a regulação do pH renal?", es: "¿Regulación del pH renal?" }, answer: { pt: "A glutaminase renal libera amônia no túbulo para excretar prótons (H+).", es: "Excreción de protones mediante amoníaco." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é a via da cinurenina?", es: "¿Vía de la cinurenina?" }, answer: { pt: "Principal via de degradação do triptofano, produzindo niacina (Vit B3).", es: "Degradación de triptófano a niacina." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que causa a Doença de Hartnup?", es: "¿Qué causa la enfermedad de Hartnup?" }, answer: { pt: "Defeito no transporte intestinal e renal de aminoácidos neutros (especialmente triptofano).", es: "Defecto en transporte de triptófano." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Qual a função da creatina fosfato e quais aminoácidos a formam?", es: "¿Función de la creatina?" }, answer: { pt: "Reserva de energia rápida no músculo; formada por Glicina e Arginina (metionina doa metil).", es: "Reserva de energía muscular." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é o sistema de transporte de aminoácidos via ciclo gama-glutamil?", es: "¿Ciclo gamma-glutamilo?" }, answer: { pt: "Via que usa glutatião para transportar aminoácidos através das membranas.", es: "Usa glutatión para transporte." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Como a deficiência de Vitamina B12 afeta o metabolismo de aminoácidos?", es: "¿Efecto de falta de B12?" }, answer: { pt: "Bloqueia a conversão de homocisteína em metionina (armadilha do folato).", es: "Bloquea conversión de homocisteína." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Qual a função da Carbamoil-fosfato sintetase II (CPS II)?", es: "¿Función de CPS II?" }, answer: { pt: "Síntese de pirimidinas (citosólica), não confundir com a CPS I da ureia.", es: "Síntesis de pirimidinas." }, difficulty: "dificil" },
    { id: 53, question: { pt: "Qual aminoácido é o principal precursor da síntese de Porfirinas (Heme)?", es: "¿Precursor del Hemo?" }, answer: { pt: "Glicina.", es: "Glicina." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que caracteriza a síndrome de Lesch-Nyhan?", es: "¿Síndrome de Lesch-Nyhan?" }, answer: { pt: "Deficiência da HGPRT (via de salvação de purinas), causando gota juvenil e automutilação.", es: "Deficiencia de HGPRT." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual o papel do Tetraidrofolato (THF)?", es: "¿Papel del THF?" }, answer: { pt: "Transportador de unidades de um carbono (metil, formil, metileno).", es: "Transportador de unidades de carbono." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é a transdesaminação?", es: "¿Qué es la transdesaminación?" }, answer: { pt: "Processo combinado de transaminação (AST/ALT) e desaminação oxidativa (GDH).", es: "Combinación de trans y desaminación." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Como a leucina regula a síntese proteica?", es: "¿Cómo regula la síntesis?" }, answer: { pt: "Ativa a via mTORC1.", es: "Activa la vía mTORC1." }, difficulty: "dificil" },
    { id: 58, question: { pt: "Qual o destino do esqueleto de carbono da Leucina?", es: "¿Destino de la Leucina?" }, answer: { pt: "Convertida em Acetil-CoA e Acetoacetato (puramente cetogênica).", es: "Acetil-CoA y Acetoacetato." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Qual aminoácido doa o segundo nitrogênio para a molécula de Ureia?", es: "¿Quién da el segundo nitrógeno?" }, answer: { pt: "Aspartato.", es: "Aspartato." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Como o Lactato e a Alanina se relacionam no metabolismo muscular?", es: "¿Lactato vs Alanina?" }, answer: { pt: "Ambos são vias de saída de carbono e nitrogênio do músculo para o fígado sob estresse/exercício.", es: "Salida de carbono/nitrógeno al hígado." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_BIOQ2_S4_B1 = FC_BIOQ2_S4_B1;
    window.FC_BIOQ2_S4_B2 = FC_BIOQ2_S4_B2;
}

// Bloco 3: Hormônios e Sinalização Celular
const FC_BIOQ2_S4_B3 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que é um hormônio?", es: "¿Qué es una hormona?" }, answer: { pt: "Mensageiro químico secretado por glândulas no sangue para regular funções em tecidos distantes.", es: "Mensajero químico secretado a la sangre." }, difficulty: "facil" },
    { id: 2, question: { pt: "Qual a diferença entre sinalização endócrina e parácrina?", es: "¿Endocrina vs paracrina?" }, answer: { pt: "Endócrina age à distância via sangue; parácrina age em células vizinhas.", es: "Endocrina via sangre; paracrina en vecinas." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que é sinalização autócrina?", es: "¿Qué es señalización autócrina?" }, answer: { pt: "A célula responde ao hormônio que ela mesma secreta.", es: "La célula responde a su propia señal." }, difficulty: "facil" },
    { id: 4, question: { pt: "Quais são as duas principais classes de hormônios quanto à solubilidade?", es: "¿Dos clases de hormonas?" }, answer: { pt: "Hidrossolúveis (peptídeos/aminas) e lipossolúveis (esteroides/tireoidianos).", es: "Hidrosolubles y liposolubles." }, difficulty: "facil" },
    { id: 5, question: { pt: "Onde se localizam os receptores de hormônios peptídicos?", es: "¿Dónde están los receptores peptídicos?" }, answer: { pt: "Na membrana plasmática.", es: "En la membrana plasmática." }, difficulty: "facil" },
    { id: 6, question: { pt: "Onde se localizam os receptores de hormônios esteroides?", es: "¿Dónde están los receptores esteroides?" }, answer: { pt: "No interior da célula (citoplasma ou núcleo).", es: "En el citoplasma o núcleo." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual a função do AMP cíclico (AMPc)?", es: "¿Función del AMPc?" }, answer: { pt: "Atuar como segundo mensageiro intracelular.", es: "Segundo mensajero intracelular." }, difficulty: "facil" },
    { id: 8, question: { pt: "Qual glândula é o 'mestre' do sistema endócrino?", es: "¿Glándula maestra?" }, answer: { pt: "Hipófise (Pituitária).", es: "Hipófisis." }, difficulty: "facil" },
    { id: 9, question: { pt: "Qual hormônio reduz a glicemia?", es: "¿Qué hormona baja la glucemia?" }, answer: { pt: "Insulina.", es: "Insulina." }, difficulty: "facil" },
    { id: 10, question: { pt: "Qual hormônio aumenta a glicemia no jejum?", es: "¿Qué hormona sube la glucemia?" }, answer: { pt: "Glucagon.", es: "Glucagón." }, difficulty: "facil" },
    { id: 11, question: { pt: "Qual a glândula que produz a insulina e o glucagon?", es: "¿Qué glándula produce insulina?" }, answer: { pt: "Pâncreas (Ilhotas de Langerhans).", es: "Páncreas." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que é o feedback negativo?", es: "¿Qué es el feedback negativo?" }, answer: { pt: "Mecanismo onde o produto final inibe sua própria produção para manter a homeostase.", es: "El producto inhibe su producción." }, difficulty: "facil" },
    { id: 13, question: { pt: "Qual o principal hormônio do estresse?", es: "¿Hormona del estrés?" }, answer: { pt: "Cortisol.", es: "Cortisol." }, difficulty: "facil" },
    { id: 14, question: { pt: "Onde são produzidas a adrenalina e a noradrenalina?", es: "¿Dónde se producen adrenalina?" }, answer: { pt: "Na medula da glândula suprarrenal.", es: "Médula suprarrenal." }, difficulty: "facil" },
    { id: 15, question: { pt: "Qual a função dos hormônios tireoidianos (T3 e T4)?", es: "¿Función de T3 y T4?" }, answer: { pt: "Regular o metabolismo basal do organismo.", es: "Regular el metabolismo basal." }, difficulty: "facil" },
    { id: 16, question: { pt: "Qual elemento químico é essencial para os hormônios da tireoide?", es: "¿Elemento esencial para la tiroides?" }, answer: { pt: "Iodo.", es: "Yodo." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é a diabetes mellitus tipo 1?", es: "¿Qué es la diabetes tipo 1?" }, answer: { pt: "Deficiência absoluta de insulina por destruição das células beta do pâncreas.", es: "Falta absoluta de insulina." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que caracteriza a diabetes mellitus tipo 2?", es: "¿Qué es la diabetes tipo 2?" }, answer: { pt: "Resistência à ação da insulina nos tecidos periféricos.", es: "Resistencia a la insulina." }, difficulty: "facil" },
    { id: 19, question: { pt: "Qual hormônio estimula a contração uterina no parto?", es: "¿Hormona del parto?" }, answer: { pt: "Ocitocina.", es: "Oxitocina." }, difficulty: "facil" },
    { id: 20, question: { pt: "Qual hormônio regula o cálcio no sangue aumentando-o?", es: "¿Hormona que sube el calcio?" }, answer: { pt: "PTH (Paratormônio).", es: "PTH." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Como a insulina sinaliza dentro da célula?", es: "¿Cómo señaliza la insulina?" }, answer: { pt: "Através de um receptor com atividade Tirosina Quinase.", es: "Receptor Tirosina Quinasa." }, difficulty: "medio" },
    { id: 22, question: { pt: "Qual a função da Proteína G na sinalização celular?", es: "¿Función de la Proteína G?" }, answer: { pt: "Atuar como transdutor de sinal entre o receptor de membrana e a enzima efetora (ex: Adenilato Ciclase).", es: "Transductor de señal." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que faz a Adenilato Ciclase?", es: "¿Qué hace la Adenilato Ciclasa?" }, answer: { pt: "Converte ATP em AMP cíclico (AMPc).", es: "Convierte ATP en AMPc." }, difficulty: "medio" },
    { id: 24, question: { pt: "Qual o papel da Proteína Quinase A (PKA)?", es: "¿Papel de la PKA?" }, answer: { pt: "Enzima ativada pelo AMPc que fosforila proteínas-alvo, alterando sua atividade.", es: "Fosforila proteínas vía AMPc." }, difficulty: "medio" },
    { id: 25, question: { pt: "Como o glucagon aumenta a glicemia?", es: "¿Cómo el glucagón sube la glucemia?" }, answer: { pt: "Estimula a glicogenólise e a gliconeogênese no fígado via sinalização por AMPc.", es: "Sube glucemia vía AMPc." }, difficulty: "medio" },
    { id: 26, question: { pt: "O que é a via do Inositol Trifosfato (IP3) e Diacilglicerol (DAG)?", es: "¿Vía del IP3 y DAG?" }, answer: { pt: "Via de sinalização que utiliza a Fosfolipase C para liberar cálcio intracelular e ativar a PKC.", es: "Usa Fosfolipasa C y Calcio." }, difficulty: "medio" },
    { id: 27, question: { pt: "Qual a função da Calmodulina?", es: "¿Função da Calmodulina?" }, answer: { pt: "Proteína que se liga ao cálcio e modula a atividade de várias enzimas.", es: "Proteína que une calcio." }, difficulty: "medio" },
    { id: 28, question: { pt: "O que faz a Fosfodiesterase (PDE)?", es: "¿Qué hace la Fosfodiesterasa?" }, answer: { pt: "Degrada o AMPc ou GMPc, terminando o sinal intracelular.", es: "Degrada el AMPc." }, difficulty: "medio" },
    { id: 29, question: { pt: "Como os hormônios esteroides alteram a função celular?", es: "¿Cómo actúan los esteroides?" }, answer: { pt: "Ligam-se a receptores intracelulares que atuam como fatores de transcrição no núcleo.", es: "Actúan como factores de transcripción." }, difficulty: "medio" },
    { id: 30, question: { pt: "Qual a diferença entre receptores ionotrópicos e metabotrópicos?", es: "¿Ionotrópicos vs metabotrópicos?" }, answer: { pt: "Ionotrópicos são canais iônicos; metabotrópicos usam segundos mensageiros (Proteína G).", es: "Canales vs segundos mensajeros." }, difficulty: "medio" },
    { id: 31, question: { pt: "Qual o papel do óxido nítrico (NO) na sinalização vascular?", es: "¿Papel del NO?" }, answer: { pt: "Ativa a Guanilato Ciclase para produzir GMPc, causando relaxamento muscular (vasodilatação).", es: "Produce GMPc y vasodilatación." }, difficulty: "medio" },
    { id: 32, question: { pt: "O que é o sistema de cascata de sinalização?", es: "¿Qué es una cascada de señalización?" }, answer: { pt: "Amplificação do sinal original onde uma molécula ativa várias outras sucessivamente.", es: "Amplificación del señal." }, difficulty: "medio" },
    { id: 33, question: { pt: "Qual a função da Leptina?", es: "¿Función de la Leptina?" }, answer: { pt: "Hormônio produzido pelo tecido adiposo que regula a saciedade no hipotálamo.", es: "Regula la saciedad." }, difficulty: "medio" },
    { id: 34, question: { pt: "Qual a função da Grelina?", es: "¿Función de la Grelina?" }, answer: { pt: "Hormônio produzido no estômago que estimula a fome.", es: "Estimula el hambre." }, difficulty: "medio" },
    { id: 35, question: { pt: "Como o cortisol atua no metabolismo?", es: "¿Acción del cortisol?" }, answer: { pt: "Estimula a gliconeogênese, a proteólise e a lipólise (hormônio catabólico).", es: "Estimula la gluconeogénesis." }, difficulty: "medio" },
    { id: 36, question: { pt: "O que é a SHBG (Sex Hormone-Binding Globulin)?", es: "¿Qué es la SHBG?" }, answer: { pt: "Proteína plasmática que transporta hormônios sexuais no sangue.", es: "Transporta hormonas sexuales." }, difficulty: "medio" },
    { id: 37, question: { pt: "Qual a função da Aldosterona?", es: "¿Función de la Aldosterona?" }, answer: { pt: "Aumentar a reabsorção de sódio e água nos rins, regulando a pressão arterial.", es: "Reabsorbe sodio y agua." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que é o eixo Hipotálamo-Hipófise-Adrenal (HHA)?", es: "¿Eje HHA?" }, answer: { pt: "Sistema de regulação da resposta ao estresse envolvendo CRH, ACTH e Cortisol.", es: "Regulación del estrés." }, difficulty: "medio" },
    { id: 39, question: { pt: "Como a cafeína afeta a sinalização celular?", es: "¿Cómo afecta la cafeína?" }, answer: { pt: "Inibe a fosfodiesterase, mantendo os níveis de AMPc elevados por mais tempo.", es: "Inhibe la fosfodiesterasa." }, difficulty: "medio" },
    { id: 40, question: { pt: "Qual o papel das proteínas adaptadoras (ex: SH2, PTB) na sinalização?", es: "¿Papel de proteínas adaptadoras?" }, answer: { pt: "Reconhecer resíduos fosforilados e recrutar outras proteínas para o complexo de sinalização.", es: "Reclutan proteínas al complejo." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a estrutura do receptor de insulina.", es: "¿Estructura del receptor de insulina?" }, answer: { pt: "Dímero composto por duas subunidades alfa (extracelulares) e duas beta (transmembrana).", es: "Dímero alfa2-beta2." }, difficulty: "dificil" },
    { id: 42, question: { pt: "O que é a autofosforilação do receptor de insulina?", es: "¿Qué es la autofosforilación?" }, answer: { pt: "O receptor fosforila seus próprios resíduos de tirosina após a ligação da insulina.", es: "Fosforila sus propias tirosinas." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Qual a função da proteína IRS-1 (Insulin Receptor Substrate)?", es: "¿Função da IRS-1?" }, answer: { pt: "Atuar como plataforma de ancoragem para proteínas com domínios SH2 (como PI3K).", es: "Plataforma de anclaje." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Descreva a via PI3K/Akt na sinalização da insulina.", es: "¿Vía PI3K/Akt?" }, answer: { pt: "Via responsável pela translocação do transportador GLUT4 para a membrana e síntese de glicogênio.", es: "Transloca GLUT4 a la membrana." }, difficulty: "dificil" },
    { id: 45, question: { pt: "Como a sinalização da insulina inibe a gliconeogênese?", es: "¿Cómo inhibe la gluconeogénesis?" }, answer: { pt: "Via Akt, que inibe o fator de transcrição FOXO1, reduzindo a expressão de enzimas-chave.", es: "Inhibe el factor FOXO1." }, difficulty: "dificil" },
    { id: 46, question: { pt: "O que são as Proteínas G monoméricas (ex: Ras)?", es: "¿Proteínas G monoméricas?" }, answer: { pt: "Pequenas GTPases que regulam crescimento celular e diferenciação (via MAP-quinases).", es: "Pequeñas GTPasas (Ras)." }, difficulty: "dificil" },
    { id: 47, question: { pt: "Qual a causa molecular da Cólera em relação à Proteína G?", es: "¿Cólera y Proteína G?" }, answer: { pt: "A toxina colérica mantém a subunidade Gs alfa ativa permanentemente, elevando o AMPc.", es: "Mantiene Gs alfa activa." }, difficulty: "dificil" },
    { id: 48, question: { pt: "Qual a causa molecular da Coqueluche em relação à Proteína G?", es: "¿Coqueluche y Proteína G?" }, answer: { pt: "A toxina pertussis inibe a subunidade Gi alfa, impedindo a inibição da adenilato ciclase.", es: "Inhibe Gi alfa." }, difficulty: "dificil" },
    { id: 49, question: { pt: "O que é dessensibilização do receptor?", es: "¿Qué es desensibilización?" }, answer: { pt: "Diminuição da resposta celular a um estímulo persistente (ex: fosforilação por GRKs e ligação de arrestina).", es: "Baja respuesta a señal continua." }, difficulty: "dificil" },
    { id: 50, question: { pt: "Descreva os domínios de um receptor nuclear.", es: "¿Dominios de receptor nuclear?" }, answer: { pt: "Domínio de ligação ao ligante, domínio de ligação ao DNA (dedos de zinco) e domínio de ativação transcricional.", es: "Ligando, DNA y Transcripción." }, difficulty: "dificil" },
    { id: 51, question: { pt: "O que são os elementos de resposta hormonal (HRE)?", es: "¿Qué son los HRE?" }, answer: { pt: "Sequências específicas de DNA onde os receptores nucleares se ligam.", es: "Secuencias de DNA para receptores." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Como o hormônio tireoidiano (T3) atua de forma não-genômica?", es: "¿Acción no genómica de T3?" }, answer: { pt: "Através de receptores de membrana ou mitocondriais que ativam quinases rapidamente.", es: "Vía receptores de membrana." }, difficulty: "dificil" },
    { id: 53, question: { pt: "Qual a função da proteína fosfatase 1 (PP1) na sinalização da insulina?", es: "¿Função da PP1?" }, answer: { pt: "Desfosforilar e ativar a glicogênio sintetase, promovendo a síntese de glicogênio.", es: "Activa la glucógeno sintetasa." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é o sistema JAK-STAT?", es: "¿Sistema JAK-STAT?" }, answer: { pt: "Via de sinalização usada por citocinas e GH que ativa diretamente a transcrição gênica.", es: "Vía de citocinas y GH." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual a função das proteínas SOCS (Suppressors of Cytokine Signaling)?", es: "¿Função das SOCS?" }, answer: { pt: "Mecanismo de feedback negativo que inibe a via JAK-STAT.", es: "Inhiben vía JAK-STAT." }, difficulty: "dificil" },
    { id: 56, question: { pt: "Como a ANP (Peptídeo Natriurético Atrial) sinaliza?", es: "¿Cómo señaliza el ANP?" }, answer: { pt: "Através de um receptor com atividade Guanilato Ciclase intrínseca.", es: "Receptor Guanilato Ciclasa." }, difficulty: "dificil" },
    { id: 57, question: { pt: "O que é o crosstalk entre vias de sinalização?", es: "¿Qué es crosstalk?" }, answer: { pt: "Interação entre diferentes vias onde um sinal pode ativar ou inibir outro.", es: "Interacción entre vías." }, difficulty: "dificil" },
    { id: 58, question: { pt: "Qual o papel dos microRNAs (miRNAs) na regulação hormonal?", es: "¿Papel de miRNAs?" }, answer: { pt: "Regulação pós-transcricional silenciando mRNAs específicos de hormônios ou receptores.", es: "Silenciamiento de mRNAs." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Como a resistência à insulina no músculo se relaciona com o acúmulo de lipídios?", es: "¿Resistencia e lípidos?" }, answer: { pt: "Diacilglicerol (DAG) ativa PKC-teta, que fosforila o IRS-1 em resíduos de serina (inibitório).", es: "DAG activa PKC que inhibe IRS-1." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Qual a função do coativador PGC-1 alfa?", es: "¿Função do PGC-1 alfa?" }, answer: { pt: "Principal regulador da biogênese mitocondrial e do metabolismo oxidativo.", es: "Regula biogénesis mitocondrial." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_BIOQ2_S4_B1 = FC_BIOQ2_S4_B1;
    window.FC_BIOQ2_S4_B2 = FC_BIOQ2_S4_B2;
    window.FC_BIOQ2_S4_B3 = FC_BIOQ2_S4_B3;
}

// Bloco 4: Integração do Metabolismo
const FC_BIOQ2_S4_B4 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que é homeostase glicêmica?", es: "¿Qué es la homeostasis glucémica?" }, answer: { pt: "Manutenção dos níveis de glicose no sangue em uma faixa estreita (70-100 mg/dL).", es: "Mantener glucosa en niveles normales." }, difficulty: "facil" },
    { id: 2, question: { pt: "Quais são os principais órgãos que regulam o metabolismo?", es: "¿Principales órganos metabólicos?" }, answer: { pt: "Fígado, Músculo, Tecido Adiposo e Cérebro.", es: "Hígado, Músculo, Grasa y Cerebro." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que acontece no estado alimentado (pós-prandial)?", es: "¿Estado alimentado?" }, answer: { pt: "Aumento da insulina, síntese de glicogênio, gordura e proteínas.", es: "Sube insulina, síntese de reservas." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que acontece no estado de jejum?", es: "¿Estado de ayuno?" }, answer: { pt: "Aumento do glucagon, quebra de glicogênio (glicogenólise) e lipólise.", es: "Sube glucagón, moviliza reservas." }, difficulty: "facil" },
    { id: 5, question: { pt: "Qual o principal combustível do cérebro?", es: "¿Combustible del cerebro?" }, answer: { pt: "Glicose (e corpos cetônicos em jejum prolongado).", es: "Glucosa." }, difficulty: "facil" },
    { id: 6, question: { pt: "O que é o glicogênio?", es: "¿Qué es el glucógeno?" }, answer: { pt: "Polímero de glicose que serve como reserva de energia rápida.", es: "Reserva de glucosa." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual a diferença entre o glicogênio hepático e o muscular?", es: "¿Glucógeno hígado vs músculo?" }, answer: { pt: "O hepático mantém a glicemia; o muscular é usado apenas pelo próprio músculo.", es: "Hígado para sangre; músculo para sí mismo." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é a gliconeogênese?", es: "¿Qué es la gluconeogénesis?" }, answer: { pt: "Produção de glicose a partir de precursores não-carboidratos (ex: lactato, aminoácidos).", es: "Síntesis de glucosa." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é a glicólise?", es: "¿Qué es la glucólisis?" }, answer: { pt: "Quebra da glicose para gerar energia (ATP) e piruvato.", es: "Ruptura de glucosa." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que é o Ciclo de Krebs?", es: "¿Qué es el Ciclo de Krebs?" }, answer: { pt: "Via final comum para a oxidação de carboidratos, lipídios e proteínas.", es: "Vía final de oxidación." }, difficulty: "facil" },
    { id: 11, question: { pt: "A insulina é um hormônio anabólico ou catabólico?", es: "¿Insulina: anabólica o catabólica?" }, answer: { pt: "Anabólico (estimula a construção de moléculas).", es: "Anabólica." }, difficulty: "facil" },
    { id: 12, question: { pt: "O glucagon é um hormônio anabólico ou catabólico?", es: "¿Glucagón: anabólico o catabólico?" }, answer: { pt: "Catabólico (estimula a quebra de moléculas).", es: "Catabólica." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que é a lipogênese?", es: "¿Qué es la lipogénesis?" }, answer: { pt: "Síntese de novos ácidos graxos e triacilgliceróis.", es: "Síntesis de grasas." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que é a lipólise?", es: "¿Qué es la lipólisis?" }, answer: { pt: "Quebra de triacilgliceróis em ácidos graxos e glicerol.", es: "Ruptura de grasas." }, difficulty: "facil" },
    { id: 15, question: { pt: "Qual a função do tecido adiposo branco?", es: "¿Función de grasa blanca?" }, answer: { pt: "Armazenar energia na forma de gordura.", es: "Almacenar energía." }, difficulty: "facil" },
    { id: 16, question: { pt: "Qual a função do tecido adiposo marrom?", es: "¿Función de grasa marrón?" }, answer: { pt: "Gerar calor (termogênese).", es: "Generar calor." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é o ATP?", es: "¿Qué es el ATP?" }, answer: { pt: "A principal moeda energética da célula.", es: "Moneda energética." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que acontece com o excesso de aminoácidos?", es: "¿Exceso de aminoácidos?" }, answer: { pt: "Eles não são armazenados; o nitrogênio vira ureia e o carbono vira energia ou gordura.", es: "Se excretan o se usan." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que é o IMC?", es: "¿Qué es el IMC?" }, answer: { pt: "Índice de Massa Corporal (peso/altura²), usado para avaliar estado nutricional.", es: "Índice de Masa Corporal." }, difficulty: "facil" },
    { id: 20, question: { pt: "A atividade física aumenta qual processo metabólico?", es: "¿Actividad física sube qué?" }, answer: { pt: "Oxidação de combustíveis para gerar ATP (respiração celular).", es: "Oxidación para ATP." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "O que é a flexibilidade metabólica?", es: "¿Qué es flexibilidad metabólica?" }, answer: { pt: "Capacidade da célula de alternar eficientemente entre carboidratos e lipídios como fonte de energia.", es: "Alternar entre sustratos." }, difficulty: "medio" },
    { id: 22, question: { pt: "Qual o papel da AMPK (Adenosina Monofosfato Quinase)?", es: "¿Papel de la AMPK?" }, answer: { pt: "Sensor de energia que ativa vias de geração de ATP e inibe vias de consumo quando o ATP está baixo.", es: "Sensor de energía." }, difficulty: "medio" },
    { id: 23, question: { pt: "Descreva o Ciclo de Cori.", es: "¿Qué es el Ciclo de Cori?" }, answer: { pt: "Lactato muscular vai ao fígado, vira glicose e retorna ao músculo.", es: "Lactato -> Glucosa -> Músculo." }, difficulty: "medio" },
    { id: 24, question: { pt: "Como o fígado ajuda a manter a glicemia no jejum noturno?", es: "¿Glicemia en ayuno nocturno?" }, answer: { pt: "Principalmente via glicogenólise hepática.", es: "Vía glucogenólisis." }, difficulty: "medio" },
    { id: 25, question: { pt: "O que é a gliconeogênese renal e quando ela é importante?", es: "¿Gluconeogénesis renal?" }, answer: { pt: "Produção de glicose pelos rins; torna-se significativa em jejum prolongado (até 40%).", es: "Glucosa por los riñones." }, difficulty: "medio" },
    { id: 26, question: { pt: "Qual o efeito da adrenalina no metabolismo muscular?", es: "¿Adrenalina en músculo?" }, answer: { pt: "Estimula a quebra rápida de glicogênio para fornecer energia para a contração.", es: "Glucogenólisis muscular." }, difficulty: "medio" },
    { id: 27, question: { pt: "O que é a cetose fisiológica?", es: "¿Qué es cetosis fisiológica?" }, answer: { pt: "Aumento moderado de corpos cetônicos no sangue em jejum ou dieta low-carb.", es: "Cuerpos cetónicos en ayuno." }, difficulty: "medio" },
    { id: 28, question: { pt: "Qual a diferença entre cetose e cetoacidose diabética?", es: "¿Cetosis vs cetoacidosis?" }, answer: { pt: "A cetoacidose é patológica, com níveis altíssimos de cetonas e queda do pH sanguíneo.", es: "Cetoacidosis es patológica." }, difficulty: "medio" },
    { id: 29, question: { pt: "Como a insulina regula a glicólise no fígado?", es: "¿Insulina y glucólisis?" }, answer: { pt: "Ativa a PFK-1 através da síntese de Frutose-2,6-bisfosfato.", es: "Vía Frutosa-2,6-bisfosfato." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que é a frutose-2,6-bisfosfato?", es: "¿Qué es la F-2,6-BP?" }, answer: { pt: "O mais potente ativador da glicólise e inibidor da gliconeogênese.", es: "Regulador glucolítico." }, difficulty: "medio" },
    { id: 31, question: { pt: "Qual a função do ciclo da glicose-alanina no jejum?", es: "¿Função da alanina no jejum?" }, answer: { pt: "Transportar esqueletos de carbono para a gliconeogênese hepática e nitrogênio para a ureia.", es: "Transporte de carbono/nitrógeno." }, difficulty: "medio" },
    { id: 32, question: { pt: "Como o músculo cardíaco obtém energia preferencialmente?", es: "¿Energía del corazón?" }, answer: { pt: "Oxidação de ácidos graxos (~70%).", es: "Oxidación de grasas." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que acontece com o metabolismo no DM2 (Diabetes Tipo 2)?", es: "¿Metabolismo en DM2?" }, answer: { pt: "Fígado produz glicose mesmo com glicemia alta e tecidos captam menos glicose.", es: "Exceso de glucosa hepática." }, difficulty: "medio" },
    { id: 34, question: { pt: "Qual o papel do adipócito como célula endócrina?", es: "¿Adipocito endocrino?" }, answer: { pt: "Secreta adipocinas (leptina, adiponectina) que regulam o metabolismo sistêmico.", es: "Secreta adipocinas." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que é a síndrome metabólica?", es: "¿Qué es el síndrome metabólico?" }, answer: { pt: "Conjunto de fatores (obesidade, HAS, dislipidemia, resistência à insulina) que aumentam risco cardiovascular.", es: "Riesgo cardiovascular múltiple." }, difficulty: "medio" },
    { id: 36, question: { pt: "Como o álcool afeta o metabolismo hepático?", es: "¿Alcohol en el hígado?" }, answer: { pt: "Aumenta a razão NADH/NAD+, inibindo a gliconeogênese e estimulando a lipogênese (esteatose).", es: "Altera NADH/NAD+." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é a 'fome de nitrogênio'?", es: "¿Hambre de nitrógeno?" }, answer: { pt: "Necessidade de aminoácidos para síntese de proteínas essenciais em estados de catabolismo intenso.", es: "Necesidad de aminoácidos." }, difficulty: "medio" },
    { id: 38, question: { pt: "Qual a função da creatina quinase (CK)?", es: "¿Función de la CK?" }, answer: { pt: "Transferir fosfato da fosfocreatina para o ADP, regenerando ATP rapidamente no músculo.", es: "Regenera ATP muscular." }, difficulty: "medio" },
    { id: 39, question: { pt: "Como o cérebro se adapta ao jejum longo?", es: "¿Cerebro en ayuno largo?" }, answer: { pt: "Passa a utilizar corpos cetônicos para suprir até 70% de suas necessidades energéticas.", es: "Usa cuerpos cetónicos." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é o efeito térmico dos alimentos?", es: "¿Efecto térmico de alimentos?" }, answer: { pt: "Energia gasta pelo corpo para digerir, absorver e processar os nutrientes.", es: "Gasto por digestión." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a regulação da Piruvato Desidrogenase (PDH) pela carga energética.", es: "¿Regulación de PDH?" }, answer: { pt: "Inibida por ATP, Acetil-CoA e NADH; ativada por ADP e Piruvato.", es: "Inhibida por energía alta." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Como a Acetil-CoA regula a piruvato carboxilase?", es: "¿Acetil-CoA y piruvato carboxilasa?" }, answer: { pt: "Atua como ativador obrigatório, desviando piruvato para a gliconeogênese.", es: "Activador de gluconeogénesis." }, difficulty: "dificil" },
    { id: 43, question: { pt: "O que é a sinalização retrógrada mitocondrial?", es: "¿Señalización retrógrada?" }, answer: { pt: "Comunicação da mitocôndria com o núcleo para ajustar a expressão gênica metabólica.", es: "Comunicación mitocondria-núcleo." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Descreva o mecanismo da 'Diabetes Starvation' (Jejum Diabetogênico).", es: "¿Diabetes por ayuno?" }, answer: { pt: "Resistência à insulina induzida pelo jejum para preservar a glicose para o cérebro.", es: "Resistencia por ayuno." }, difficulty: "dificil" },
    { id: 45, question: { pt: "Como o Malonil-CoA coordena o metabolismo de gorduras?", es: "¿Papel del Malonil-CoA?" }, answer: { pt: "Inibe a entrada de ácidos graxos na mitocôndria (via CPT1) quando a síntese está ativa.", es: "Inhibe oxidación si hay síntesis." }, difficulty: "dificil" },
    { id: 46, question: { pt: "O que é a via do poliol e sua relevância na hiperglicemia?", es: "¿Vía del poliol?" }, answer: { pt: "Conversão de glicose em sorbitol; causa dano osmótico em tecidos diabéticos (catarata, neuropatia).", es: "Glucosa -> Sorbitol." }, difficulty: "dificil" },
    { id: 47, question: { pt: "Como a hipóxia altera o metabolismo celular (Efeito Pasteur)?", es: "¿Efecto Pasteur?" }, answer: { pt: "Aumento da glicólise anaeróbica para compensar a falta de fosforilação oxidativa.", es: "Sube glucólisis por hipoxia." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que é o efeito Warburg em células tumorais?", es: "¿Efecto Warburg?" }, answer: { pt: "Preferência por glicólise aeróbica (fermentação láctica mesmo com O2) para suportar o crescimento.", es: "Glucólisis aeróbica en cáncer." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Qual a função da proteína p53 no metabolismo?", es: "¿p53 metabólica?" }, answer: { pt: "Estimula a respiração mitocondrial e inibe a glicólise, agindo como supressor tumoral metabólico.", es: "Regula respiración celular." }, difficulty: "dificil" },
    { id: 50, question: { pt: "Como a Sirtuína 1 (SIRT1) regula o metabolismo?", es: "¿Papel de SIRT1?" }, answer: { pt: "Desacetilase dependente de NAD+ que ativa vias catabólicas e longevidade em resposta ao jejum.", es: "Activa vías catabólicas." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Descreva o papel do FGF21 (Fator de Crescimento de Fibroblastos 21).", es: "¿Papel de FGF21?" }, answer: { pt: "Hormônio hepático que estimula a oxidação de gorduras e a cetogênese no jejum.", es: "Estimula cetogénesis." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Como a inflamação crônica no tecido adiposo causa resistência à insulina?", es: "¿Inflamación y resistencia?" }, answer: { pt: "TNF-alfa e IL-6 ativam quinases (JNK, IKK) que fosforilam o IRS-1 em serina.", es: "Citosinas inhiben IRS-1." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é a glicação não-enzimática de proteínas (AGEs)?", es: "¿Qué son los AGEs?" }, answer: { pt: "Ligação da glicose a proteínas (ex: HbA1c), causando danos estruturais em diabéticos.", es: "Daño proteico por glucosa." }, difficulty: "dificil" },
    { id: 54, question: { pt: "Qual o papel do receptor PPAR-gama?", es: "¿Papel de PPAR-gama?" }, answer: { pt: "Regulador mestre da adipogênese e sensibilidade à insulina (alvo das tiazolidinedionas).", es: "Regula adipogénesis." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Como o glucagon e a adrenalina diferem na regulação da glicólise muscular?", es: "¿Glucagón vs Adrenalina no músculo?" }, answer: { pt: "O glucagon NÃO afeta o músculo (falta de receptor); a adrenalina estimula fortemente a glicogenólise.", es: "Músculo no responde al glucagón." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é o turnover proteico e como ele é regulado no trauma?", es: "¿Turnover proteico?" }, answer: { pt: "Equilíbrio entre síntese e degradação; no trauma, a degradação supera a síntese (catabolismo).", es: "Balance síntesis/degradación." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Descreva a 'fome oculta' no contexto metabólico.", es: "¿Hambre oculta?" }, answer: { pt: "Deficiência de micronutrientes (vitaminas/minerais) mesmo com ingestão calórica adequada.", es: "Falta de micronutrientes." }, difficulty: "dificil" },
    { id: 58, question: { pt: "Como o corpo evita a hipoglicemia durante o exercício intenso?", es: "¿Evitar hipoglucemia en ejercicio?" }, answer: { pt: "Supressão da insulina e aumento de glucagon/adrenalina/GH/cortisol.", es: "Hormonas contra-insulares." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Qual a função da Proteína de Transferência de Triglicerídeos Microssomais (MTP)?", es: "¿Función de MTP?" }, answer: { pt: "Essencial para a montagem de quilomícrons e VLDL (ausente na abetalipoproteinemia).", es: "Ensamblaje de lipoproteínas." }, difficulty: "dificil" },
    { id: 60, question: { pt: "O que é a termogênese adaptativa?", es: "¿Termogénesis adaptativa?" }, answer: { pt: "Mudanças no gasto energético basal em resposta a alterações na ingestão calórica ou temperatura.", es: "Ajuste del gasto energético." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_BIOQ2_S4_B1 = FC_BIOQ2_S4_B1;
    window.FC_BIOQ2_S4_B2 = FC_BIOQ2_S4_B2;
    window.FC_BIOQ2_S4_B3 = FC_BIOQ2_S4_B3;
    window.FC_BIOQ2_S4_B4 = FC_BIOQ2_S4_B4;
}

// Bloco 5: Metabolismo de Nucleotídeos
const FC_BIOQ2_S4_B5 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que é um nucleotídeo?", es: "¿Qué es un nucleótido?" }, answer: { pt: "Composto formado por uma base nitrogenada, uma pentose e um grupo fosfato.", es: "Base nitrogenada, pentosa y fosfato." }, difficulty: "facil" },
    { id: 2, question: { pt: "Quais são as bases purinas?", es: "¿Cuáles son las purinas?" }, answer: { pt: "Adenina (A) e Guanina (G).", es: "Adenina y Guanina." }, difficulty: "facil" },
    { id: 3, question: { pt: "Quais são as bases pirimidinas?", es: "¿Cuáles son las pirimidinas?" }, answer: { pt: "Citosina (C), Timina (T) e Uracila (U).", es: "Citosina, Timina y Uracilo." }, difficulty: "facil" },
    { id: 4, question: { pt: "Qual a diferença entre nucleotídeo e nucleosídeo?", es: "¿Nucleótido vs nucleósido?" }, answer: { pt: "O nucleosídeo não possui o grupo fosfato.", es: "El nucleósido no tiene fosfato." }, difficulty: "facil" },
    { id: 5, question: { pt: "Qual açúcar compõe o DNA?", es: "¿Qué azúcar tiene el DNA?" }, answer: { pt: "Desoxirribose.", es: "Desoxirribosa." }, difficulty: "facil" },
    { id: 6, question: { pt: "Qual açúcar compõe o RNA?", es: "¿Qué azúcar tiene el RNA?" }, answer: { pt: "Ribose.", es: "Ribosa." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual base é exclusiva do DNA?", es: "¿Qué base es solo del DNA?" }, answer: { pt: "Timina.", es: "Timina." }, difficulty: "facil" },
    { id: 8, question: { pt: "Qual base é exclusiva do RNA?", es: "¿Qué base es solo del RNA?" }, answer: { pt: "Uracila.", es: "Uracilo." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é a síntese 'de novo' de nucleotídeos?", es: "¿Qué es síntesis 'de novo'?" }, answer: { pt: "Síntese a partir de precursores simples como aminoácidos e CO2.", es: "Síntesis desde precursores simples." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que são as vias de salvação (salvage)?", es: "¿Qué son vías de salvamento?" }, answer: { pt: "Reciclagem de bases livres provenientes da dieta ou degradação interna.", es: "Reciclaje de bases nitrogenadas." }, difficulty: "facil" },
    { id: 11, question: { pt: "O que é o PRPP?", es: "¿Qué es el PRPP?" }, answer: { pt: "Fosforribosil pirofosfato, doador da pentose para a síntese de nucleotídeos.", es: "Donador de la pentosa (PRPP)." }, difficulty: "facil" },
    { id: 12, question: { pt: "Qual o produto final da degradação de purinas em humanos?", es: "¿Producto final de purinas?" }, answer: { pt: "Ácido úrico.", es: "Ácido úrico." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que causa a Gota?", es: "¿Qué causa la Gota?" }, answer: { pt: "Acúmulo de cristais de urato de sódio nas articulações devido à hiperuricemia.", es: "Acúmulo de ácido úrico." }, difficulty: "facil" },
    { id: 14, question: { pt: "Qual a função do ATP além da energia?", es: "¿Función del ATP?" }, answer: { pt: "Precursor da síntese de RNA e componente de coenzimas como NAD e FAD.", es: "Precursor de RNA y coenzimas." }, difficulty: "facil" },
    { id: 15, question: { pt: "O que é um nucleotídeo cíclico?", es: "¿Qué es nucleótido cíclico?" }, answer: { pt: "Molécula de sinalização como AMPc ou GMPc.", es: "Señalizadores (AMPc/GMPc)." }, difficulty: "facil" },
    { id: 16, question: { pt: "Quais aminoácidos doam nitrogênio para as purinas?", es: "¿Aminoácidos para purinas?" }, answer: { pt: "Aspartato, Glicina e Glutamina.", es: "Asp, Gly, Gln." }, difficulty: "facil" },
    { id: 17, question: { pt: "Onde ocorre a síntese de nucleotídeos?", es: "¿Onde ocorre a síntese?" }, answer: { pt: "Principalmente no citosol.", es: "En el citosol." }, difficulty: "facil" },
    { id: 18, question: { pt: "Qual a função do GTP na célula?", es: "¿Función del GTP?" }, answer: { pt: "Energia para síntese proteica e sinalização via Proteína G.", es: "Síntesis proteica y señalización." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que é o DNA polimerase?", es: "¿Qué es DNA polimerasa?" }, answer: { pt: "Enzima que sintetiza novas fitas de DNA usando dNTPs.", es: "Sintetiza DNA." }, difficulty: "facil" },
    { id: 20, question: { pt: "A cafeína é estruturalmente semelhante a qual base?", es: "¿Cafeína y qué base?" }, answer: { pt: "Adenina (é uma xantina/purina).", es: "Adenina." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Qual o primeiro nucleotídeo de purina formado na via 'de novo'?", es: "¿Primer nucleótido de purina?" }, answer: { pt: "IMP (Inosina Monofosfato).", es: "IMP." }, difficulty: "medio" },
    { id: 22, question: { pt: "Qual a enzima marcapasso da síntese de purinas?", es: "¿Enzima limitante de purinas?" }, answer: { pt: "Glutamina-PRPP Amidotransferase.", es: "Glutamina-PRPP Amidotransferasa." }, difficulty: "medio" },
    { id: 23, question: { pt: "Como a síntese de purinas é regulada?", es: "¿Regulación de purinas?" }, answer: { pt: "Inibição por feedback pelos produtos finais (AMP, GMP e IMP).", es: "Inhibición por AMP, GMP, IMP." }, difficulty: "medio" },
    { id: 24, question: { pt: "Qual a diferença fundamental na síntese de purinas vs pirimidinas?", es: "¿Diferencia purinas vs pirimidinas?" }, answer: { pt: "Nas purinas, o anel é construído sobre o açúcar; nas pirimidinas, o anel é feito antes.", es: "Purinas: anillo sobre azúcar." }, difficulty: "medio" },
    { id: 25, question: { pt: "Qual o primeiro nucleotídeo de pirimidina formado?", es: "¿Primer nucleótido pirimidina?" }, answer: { pt: "OMP (Orotidina Monofosfato), que vira UMP.", es: "OMP." }, difficulty: "medio" },
    { id: 26, question: { pt: "Qual enzima converte ribonucleotídeos em desoxirribonucleotídeos?", es: "¿Qué enzima hace desoxirribonucleótidos?" }, answer: { pt: "Ribonucleotídeo Redutase.", es: "Ribonucleótido Reductasa." }, difficulty: "medio" },
    { id: 27, question: { pt: "Qual o papel do NADPH na síntese de DNA?", es: "¿Papel del NADPH en DNA?" }, answer: { pt: "Fornecer elétrons para a Ribonucleotídeo Redutase via Tioredoxina.", es: "Reduce a la reductasa." }, difficulty: "medio" },
    { id: 28, question: { pt: "Como o Alopurinol ajuda no tratamento da gota?", es: "¿Cómo actúa el Alopurinol?" }, answer: { pt: "Inibe a enzima Xantina Oxidase, reduzindo a produção de ácido úrico.", es: "Inhibe Xantina Oxidasa." }, difficulty: "medio" },
    { id: 29, question: { pt: "Qual enzima é responsável pela via de salvação de Hipoxantina e Guanina?", es: "¿Enzima de salvamento HG?" }, answer: { pt: "HGPRT (Hipoxantina-Guanina Fosforribosiltransferase).", es: "HGPRT." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que é a Acidúria Orótica?", es: "¿Qué es Aciduria Orótica?" }, answer: { pt: "Deficiência enzimática na via de síntese de pirimidinas, causando anemia e excreção de ácido orótico.", es: "Falla en síntesis de pirimidinas." }, difficulty: "medio" },
    { id: 31, question: { pt: "Como o Metotrexato afeta o metabolismo de nucleotídeos?", es: "¿Metotrexato y nucleótidos?" }, answer: { pt: "Inibe a Diidrofolato Redutase, esgotando o THF necessário para a síntese de timina e purinas.", es: "Inhibe síntesis de THF." }, difficulty: "medio" },
    { id: 32, question: { pt: "Qual a função da enzima Timidilato Sintetase?", es: "¿Função da Timidilato Sintetase?" }, answer: { pt: "Converter dUMP em dTMP (única via para Timina).", es: "Produce dTMP." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que é o 5-Fluorouracil (5-FU)?", es: "¿Qué es el 5-FU?" }, answer: { pt: "Um quimioterápico que inibe irreversivelmente a Timidilato Sintetase.", es: "Inhibe Timidilato Sintetasa." }, difficulty: "medio" },
    { id: 34, question: { pt: "Qual a importância do Ácido Fólico na gestação?", es: "¿Ácido Fólico en gestación?" }, answer: { pt: "Essencial para a síntese de DNA e divisão celular, prevenindo defeitos no tubo neural.", es: "Previene defectos del tubo neural." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que acontece com o excesso de pirimidinas?", es: "¿Excesso de pirimidinas?" }, answer: { pt: "São degradadas em produtos altamente solúveis (CO2, NH4+, beta-alanina), sem causar patologias como a gota.", es: "Productos solubles." }, difficulty: "medio" },
    { id: 36, question: { pt: "Qual o papel da Adenosina na regulação do sono?", es: "¿Adenosina y sueño?" }, answer: { pt: "Acumula-se no cérebro durante a vigília e sinaliza a necessidade de dormir.", es: "Señal de sueño." }, difficulty: "medio" },
    { id: 37, question: { pt: "Como a Hidroxirreia atua no tratamento de doenças mieloproliferativas?", es: "¿Cómo actúa la Hidroxiurea?" }, answer: { pt: "Inibe a Ribonucleotídeo Redutase, bloqueando a síntese de DNA.", es: "Inhibe Ribonucleótido Reductasa." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que é a adenosina desaminase (ADA)?", es: "¿Qué es la ADA?" }, answer: { pt: "Enzima que degrada adenosina; sua deficiência causa SCID (Imunodeficiência Combinada Grave).", es: "Deficiencia causa SCID." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que são análogos de nucleosídeos?", es: "¿Análogos de nucleósidos?" }, answer: { pt: "Drogas (como AZT) que mimetizam nucleosídeos naturais para interromper a replicação viral ou tumoral.", es: "Frenan replicación." }, difficulty: "medio" },
    { id: 40, question: { pt: "Por que a síntese de purinas requer gasto de ATP?", es: "¿Por qué requiere ATP?" }, answer: { pt: "Para ativar o PRPP e fornecer energia para as ligases que constroem o anel.", es: "Para activar precursores." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a reação da CPS II na síntese de pirimidinas.", es: "¿Reacción de la CPS II?" }, answer: { pt: "Sintetiza Carbamoil-fosfato a partir de Glutamina e CO2 no citosol.", es: "Produce Carbamoil-fosfato." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Qual a regulação alostérica da Ribonucleotídeo Redutase?", es: "¿Regulación de la Reductasa?" }, answer: { pt: "Ativada por ATP e inibida por dATP (controle de feedback negativo global).", es: "ATP activa, dATP inhibe." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Como a concentração de ATP e GTP se equilibra na síntese de purinas?", es: "¿Equilibrio ATP/GTP?" }, answer: { pt: "Síntese de AMP requer GTP; síntese de GMP requer ATP (controle cruzado).", es: "Regulación cruzada." }, difficulty: "dificil" },
    { id: 44, question: { pt: "O que é a síndrome de Lesch-Nyhan e qual sua base genética?", es: "¿Síndrome de Lesch-Nyhan?" }, answer: { pt: "Deficiência completa de HGPRT, ligada ao X; causa automutilação e hiperuricemia grave.", es: "Deficiencia total de HGPRT." }, difficulty: "dificil" },
    { id: 45, question: { pt: "Descreva o papel da enzima CAD na síntese de pirimidinas.", es: "¿Papel de la enzima CAD?" }, answer: { pt: "Complexo multienzimático que realiza as 3 primeiras etapas (CPS II, ATCase, Diidroorotase).", es: "Complejo de 3 enzimas." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Como a deficiência de ADA causa morte de linfócitos?", es: "¿ADA y linfocitos?" }, answer: { pt: "Acúmulo de dATP, que inibe a Ribonucleotídeo Redutase e impede a síntese de DNA.", es: "Exceso de dATP inhibe DNA." }, difficulty: "dificil" },
    { id: 47, question: { pt: "Qual o mecanismo de ação do Micofenolato de Mofetila?", es: "¿Mecanismo del Micofenolato?" }, answer: { pt: "Inibe a IMP desidrogenase, bloqueando a síntese de GMP em linfócitos (imunossupressor).", es: "Inhibe síntesis de GMP." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que é o sítio de especificidade da Ribonucleotídeo Redutase?", es: "¿Sitio de especificidad?" }, answer: { pt: "Sítio que regula qual tipo de dNTP será produzido dependendo do nucleotídeo ligado.", es: "Regula balance de dNTPs." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Qual o papel do THF na conversão de dUMP em dTMP?", es: "¿Papel del THF en dTMP?" }, answer: { pt: "O N5,N10-metileno-THF doa um grupo metil e elétrons (vira DHF).", es: "Donador de metilo." }, difficulty: "dificil" },
    { id: 50, question: { pt: "Como a regulação por pirimidinas difere entre bactérias e humanos?", es: "¿Diferencia en pirimidinas?" }, answer: { pt: "Bactérias regulam via ATCase; humanos regulam via CPS II.", es: "Bact: ATCase. Hum: CPS II." }, difficulty: "dificil" },
    { id: 51, question: { pt: "O que caracteriza a hipoxantina estruturalmente?", es: "¿Qué es la hipoxantina?" }, answer: { pt: "É a base nitrogenada do nucleotídeo IMP (purina sem grupos amina ou ceto adicionais).", es: "Base del IMP." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Qual a função da Xantina Oxidase?", es: "¿Função da Xantina Oxidase?" }, answer: { pt: "Converter Hipoxantina em Xantina e Xantina em Ácido Úrico.", es: "Produce ácido úrico." }, difficulty: "dificil" },
    { id: 53, question: { pt: "Como os análogos de purina como a 6-Mercaptopurina agem?", es: "¿Acción de 6-MP?" }, answer: { pt: "Inibem a primeira etapa da síntese 'de novo' e a conversão de IMP em AMP/GMP.", es: "Inhibe síntesis de purinas." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é o 'trap' de adenina na deficiência de frutose?", es: "¿Trampa de adenina?" }, answer: { pt: "Acúmulo de frutose-1-P consome Pi, levando à degradação excessiva de ATP em ácido úrico.", es: "Degradación de ATP a urato." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual a importância da Fosforribosilmutase?", es: "¿Fosforribosilmutasa?" }, answer: { pt: "Converte Ribose-1-P em Ribose-5-P para ser usada pelo PRPP.", es: "Prepara ribosa para PRPP." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é o domínio de dedos de zinco em proteínas reguladoras?", es: "¿Dedos de zinc?" }, answer: { pt: "Motivo estrutural que permite a ligação estável de proteínas ao DNA.", es: "Unión estable al DNA." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Como ocorre a degradação da Citosina?", es: "¿Degradación de Citosina?" }, answer: { pt: "Desaminação para Uracila e posterior redução a beta-alanina.", es: "Se reduce a beta-alanina." }, difficulty: "dificil" },
    { id: 58, question: { pt: "Qual a relação entre dUTPase e integridade do DNA?", es: "¿dUTPasa y DNA?" }, answer: { pt: "Hidrolisa dUTP para evitar que a Uracila seja incorporada por engano no DNA.", es: "Evita uracilo en DNA." }, difficulty: "dificil" },
    { id: 59, question: { pt: "O que é o coeficiente de sedimentação de Svedberg (S) nos ribossomos?", es: "¿Coeficiente S?" }, answer: { pt: "Medida da velocidade de sedimentação que reflete massa e forma da partícula.", es: "Medida de sedimentación." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Como a vitamina B12 e o folato se inter-relacionam na síntese de timidilato?", es: "¿B12, Folato y dTMP?" }, answer: { pt: "B12 regenera o metil-THF; sem ela, o folato fica 'preso' e falta para a síntese de dTMP.", es: "B12 regenera el Folato." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_BIOQ2_S4_B1 = FC_BIOQ2_S4_B1;
    window.FC_BIOQ2_S4_B2 = FC_BIOQ2_S4_B2;
    window.FC_BIOQ2_S4_B3 = FC_BIOQ2_S4_B3;
    window.FC_BIOQ2_S4_B4 = FC_BIOQ2_S4_B4;
    window.FC_BIOQ2_S4_B5 = FC_BIOQ2_S4_B5;
}
