// Flashcards — Fisiologia II — S4
// Bloco 1: Sistema Endócrino

const FC_FISIO2_S4_B1 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "Qual a principal glândula que regula o metabolismo basal?", es: "¿Qué glándula regula el metabolismo basal?" }, answer: { pt: "Glândula Tireoide.", es: "Glándula Tiroides." }, difficulty: "facil" },
    { id: 2, question: { pt: "Onde é produzida a insulina?", es: "¿Dónde se produce la insulina?" }, answer: { pt: "Nas células beta das ilhotas de Langerhans, no pâncreas.", es: "En las células beta del páncreas." }, difficulty: "facil" },
    { id: 3, question: { pt: "Onde é produzido o glucagon?", es: "¿Dónde se produce el glucagón?" }, answer: { pt: "Nas células alfa das ilhotas de Langerhans, no pâncreas.", es: "En las células alfa del páncreas." }, difficulty: "facil" },
    { id: 4, question: { pt: "Qual hormônio é conhecido como o hormônio do crescimento?", es: "¿Hormona del crecimiento?" }, answer: { pt: "GH (Somatotropina).", es: "GH." }, difficulty: "facil" },
    { id: 5, question: { pt: "Onde é produzida a melatonina?", es: "¿Dónde se produce la melatonina?" }, answer: { pt: "Na glândula pineal.", es: "En la glándula pineal." }, difficulty: "facil" },
    { id: 6, question: { pt: "Qual a função da ADH (Vasopressina)?", es: "¿Función de la ADH?" }, answer: { pt: "Aumentar a reabsorção de água nos rins, concentrando a urina.", es: "Reabsorber agua en los riñones." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual hormônio estimula a ejeção de leite e as contrações uterinas?", es: "¿Qué hormona estimula la eyección de leche?" }, answer: { pt: "Ocitocina.", es: "Oxitocina." }, difficulty: "facil" },
    { id: 8, question: { pt: "Onde são armazenados a ADH e a Ocitocina?", es: "¿Dónde se almacenan ADH y Oxitocina?" }, answer: { pt: "Na neuro-hipófise (hipófise posterior).", es: "En la neurohipófisis." }, difficulty: "facil" },
    { id: 9, question: { pt: "Qual hormônio regula os níveis de cálcio aumentando-os no sangue?", es: "¿Hormona que sube el calcio?" }, answer: { pt: "PTH (Paratormônio).", es: "PTH." }, difficulty: "facil" },
    { id: 10, question: { pt: "Qual hormônio reduz os níveis de cálcio no sangue?", es: "¿Hormona que baja el calcio?" }, answer: { pt: "Calcitonina.", es: "Calcitonina." }, difficulty: "facil" },
    { id: 11, question: { pt: "Onde é produzida a adrenalina?", es: "¿Dónde se produce la adrenalina?" }, answer: { pt: "Na medula da glândula suprarrenal.", es: "Médula suprarrenal." }, difficulty: "facil" },
    { id: 12, question: { pt: "Onde é produzido o cortisol?", es: "¿Dónde se produce el cortisol?" }, answer: { pt: "No córtex da glândula suprarrenal.", es: "Corteza suprarrenal." }, difficulty: "facil" },
    { id: 13, question: { pt: "Qual a principal função do cortisol?", es: "¿Función del cortisol?" }, answer: { pt: "Resposta ao estresse e regulação do metabolismo de glicose.", es: "Respuesta al estrés." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que é o bócio?", es: "¿Qué es el bocio?" }, answer: { pt: "Aumento volumétrico da glândula tireoide.", es: "Aumento de la tiroides." }, difficulty: "facil" },
    { id: 15, question: { pt: "Qual hormônio estimula a produção de espermatozoides e o desenvolvimento folicular?", es: "¿Hormona que estimula folículos?" }, answer: { pt: "FSH (Hormônio Folículo Estimulante).", es: "FSH." }, difficulty: "facil" },
    { id: 16, question: { pt: "Qual hormônio estimula a produção de testosterona e a ovulação?", es: "¿Hormona de la ovulación?" }, answer: { pt: "LH (Hormônio Luteinizante).", es: "LH." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é o feedback positivo?", es: "¿Qué es feedback positivo?" }, answer: { pt: "Mecanismo que amplifica um estímulo inicial (ex: ocitocina no parto).", es: "Amplifica el estímulo." }, difficulty: "facil" },
    { id: 18, question: { pt: "Qual hormônio é produzido pelo coração para reduzir a pressão arterial?", es: "¿Hormona del corazón para la presión?" }, answer: { pt: "ANP (Peptídeo Natriurético Atrial).", es: "ANP." }, difficulty: "facil" },
    { id: 19, question: { pt: "Qual a glândula que controla o ritmo circadiano?", es: "¿Glándula del ritmo circadiano?" }, answer: { pt: "Glândula Pineal.", es: "Glándula Pineal." }, difficulty: "facil" },
    { id: 20, question: { pt: "A prolactina serve para quê?", es: "¿Para qué sirve la prolactina?" }, answer: { pt: "Estimular a produção de leite nas glândulas mamárias.", es: "Estimular producción de leche." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Como o hipotálamo se comunica com a adeno-hipófise?", es: "¿Comunicación hipotálamo-adenohipófisis?" }, answer: { pt: "Através do sistema porta-hipofisário (comunicação vascular).", es: "Sistema porta-hipofisario." }, difficulty: "medio" },
    { id: 22, question: { pt: "Como o hipotálamo se comunica com a neuro-hipófise?", es: "¿Comunicación hipotálamo-neurohipófisis?" }, answer: { pt: "Através de axônios neuronais (comunicação neural).", es: "Vía neuronal." }, difficulty: "medio" },
    { id: 23, question: { pt: "Qual o efeito da Somatostatina no pâncreas?", es: "¿Efecto de la somatostatina?" }, answer: { pt: "Inibe a secreção de insulina e glucagon.", es: "Inhibe insulina y glucagón." }, difficulty: "medio" },
    { id: 24, question: { pt: "Qual a função da Aldosterona e onde é produzida?", es: "¿Función de la aldosterona?" }, answer: { pt: "Reabsorção de sódio e água; produzida na zona glomerulosa do córtex suprarrenal.", es: "Reabsorción de sodio." }, difficulty: "medio" },
    { id: 25, question: { pt: "O que é a Diabetes Insipidus?", es: "¿Qué es la diabetes insípida?" }, answer: { pt: "Deficiência de ADH ou resistência renal à sua ação, causando poliúria intensa.", es: "Falta o falla de ADH." }, difficulty: "medio" },
    { id: 26, question: { pt: "Qual o papel do Iodo na síntese de T3 e T4?", es: "¿Papel del Yodo?" }, answer: { pt: "É incorporado à tireoglobulina para formar as moléculas de hormônio tireoidiano.", es: "Se une a la tiroglobulina." }, difficulty: "medio" },
    { id: 27, question: { pt: "Como o PTH aumenta o cálcio sanguíneo?", es: "¿Cómo el PTH sube el calcio?" }, answer: { pt: "Ativando osteoclastos, aumentando a reabsorção renal e a absorção intestinal (via Vit D).", es: "Activa osteoclastos y riñones." }, difficulty: "medio" },
    { id: 28, question: { pt: "Qual a função da Vitamina D (Calcitriol) no metabolismo do cálcio?", es: "¿Función de la Vitamina D?" }, answer: { pt: "Aumentar a absorção intestinal de cálcio e fosfato.", es: "Absorción intestinal de calcio." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que caracteriza a Síndrome de Cushing?", es: "¿Qué es el síndrome de Cushing?" }, answer: { pt: "Excesso crônico de glicocorticoides (cortisol).", es: "Exceso de cortisol." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que caracteriza a Doença de Addison?", es: "¿Qué es la enfermedad de Addison?" }, answer: { pt: "Insuficiência suprarrenal primária (falta de cortisol e aldosterona).", es: "Falla suprarrenal." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que é o Gigantismo e qual sua causa?", es: "¿Qué es el gigantismo?" }, answer: { pt: "Excesso de GH na infância, antes do fechamento das epífises ósseas.", es: "Exceso de GH en niños." }, difficulty: "medio" },
    { id: 32, question: { pt: "O que é a Acromegalia?", es: "¿Qué es la acromegalia?" }, answer: { pt: "Excesso de GH no adulto, causando crescimento de extremidades e partes moles.", es: "Exceso de GH en adultos." }, difficulty: "medio" },
    { id: 33, question: { pt: "Como a insulina facilita a entrada de glicose na célula?", es: "¿Cómo actúa la insulina?" }, answer: { pt: "Promovendo a translocação de transportadores GLUT4 para a membrana plasmática.", es: "Transloca GLUT4." }, difficulty: "medio" },
    { id: 34, question: { pt: "Qual o efeito metabólico das catecolaminas (adrenalina)?", es: "¿Efecto de la adrenalina?" }, answer: { pt: "Aumento da glicogenólise e lipólise para fornecer energia rápida.", es: "Glucogenólisis y lipólisis." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que é o transporte de T3 e T4 no sangue?", es: "¿Transporte de T3 y T4?" }, answer: { pt: "Ligados principalmente à TBG (Globulina Ligadora de Tiroxina).", es: "Unidos a la TBG." }, difficulty: "medio" },
    { id: 36, question: { pt: "Qual o papel da Dopamina na regulação da Prolactina?", es: "¿Dopamina y prolactina?" }, answer: { pt: "A dopamina inibe a secreção de prolactina pela hipófise.", es: "Inhibe la prolactina." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é o efeito de Wolff-Chaikoff?", es: "¿Efecto Wolff-Chaikoff?" }, answer: { pt: "Redução temporária da síntese de hormônios tireoidianos após ingestão excessiva de iodo.", es: "Inhibición por exceso de yodo." }, difficulty: "medio" },
    { id: 38, question: { pt: "Como o glucagon atua no fígado?", es: "¿Glucagón en el hígado?" }, answer: { pt: "Estimula a glicogenólise e a gliconeogênese via aumento de AMPc.", es: "Produce glucosa." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é a zona fasciculada da suprarrenal?", es: "¿Zona fasciculada?" }, answer: { pt: "Camada do córtex responsável pela produção de glicocorticoides (cortisol).", es: "Produce cortisol." }, difficulty: "medio" },
    { id: 40, question: { pt: "Qual a função do GnRH?", es: "¿Función del GnRH?" }, answer: { pt: "Estimular a adeno-hipófise a secretar as gonadotrofinas (FSH e LH).", es: "Estimula FSH y LH." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva o mecanismo de ação dos receptores nucleares tireoidianos.", es: "¿Receptores tiroideos?" }, answer: { pt: "Ligam-se ao DNA e regulam a transcrição de genes que aumentam o metabolismo.", es: "Regulan transcripción genética." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Como o sistema Renina-Angiotensina-Aldosterona (SRAA) regula a volemia?", es: "¿Sistema SRAA?" }, answer: { pt: "A angiotensina II estimula a aldosterona, que retém sódio e água, elevando a pressão.", es: "Retiene sodio y agua." }, difficulty: "dificil" },
    { id: 43, question: { pt: "O que é a síndrome de Conn?", es: "¿Qué es el síndrome de Conn?" }, answer: { pt: "Hiperaldosteronismo primário, geralmente causado por um adenoma suprarrenal.", es: "Exceso de aldosterona." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Qual o papel do receptor V2 na ação da ADH?", es: "¿Receptor V2 de ADH?" }, answer: { pt: "Localizado no túbulo coletor; ativa aquaporinas para reabsorver água.", es: "Activa acuaporinas." }, difficulty: "dificil" },
    { id: 45, question: { pt: "Como o GH exerce seus efeitos de crescimento?", es: "¿Cómo actúa el GH?" }, answer: { pt: "Estimulando o fígado a produzir IGF-1 (Somatomedina C).", es: "Vía IGF-1." }, difficulty: "dificil" },
    { id: 46, question: { pt: "O que é a sinalização por receptor acoplado à proteína Gq?", es: "¿Señalización vía Gq?" }, answer: { pt: "Ativa a fosfolipase C, liberando IP3 e DAG, aumentando o cálcio intracelular.", es: "Libera calcio e IP3." }, difficulty: "dificil" },
    { id: 47, question: { pt: "Qual a diferença entre receptores alfa e beta adrenérgicos?", es: "¿Alfa vs Beta adrenérgicos?" }, answer: { pt: "Alfa geralmente causam vasoconstrição; Beta causam vasodilatação ou estimulação cardíaca.", es: "Diferente respuesta tisular." }, difficulty: "dificil" },
    { id: 48, question: { pt: "Descreva a biosíntese das catecolaminas.", es: "¿Biosíntesis de catecolaminas?" }, answer: { pt: "Tirosina -> DOPA -> Dopamina -> Noradrenalina -> Adrenalina.", es: "Vía de la Tirosina." }, difficulty: "dificil" },
    { id: 49, question: { pt: "O que é a desiodase tipo 1 e tipo 2?", es: "¿Desiodasas?" }, answer: { pt: "Enzimas que convertem o T4 (pro-hormônio) em T3 (forma ativa) nos tecidos.", es: "Convierten T4 en T3." }, difficulty: "dificil" },
    { id: 50, question: { pt: "Como o cortisol inibe a inflamação?", es: "¿Cortisol e inflamación?" }, answer: { pt: "Inibindo a fosfolipase A2 e reduzindo a produção de eicosanoides (prostaglandinas).", es: "Inhibe fosfolipasa A2." }, difficulty: "dificil" },
    { id: 51, question: { pt: "O que caracteriza a Síndrome de Nelson?", es: "¿Qué es la síndrome de Nelson?" }, answer: { pt: "Crescimento de um adenoma hipofisário após adrenalectomia bilateral.", es: "Adenoma tras adrenalectomía." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Qual a função da proteína Gs na regulação do glucagon?", es: "¿Proteína Gs y glucagón?" }, answer: { pt: "Ativa a adenilato ciclase, aumentando o AMPc e ativando a PKA.", es: "Sube AMPc." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é o feocromocitoma?", es: "¿Qué es el feocromocitoma?" }, answer: { pt: "Tumor da medula suprarrenal que secreta excesso de catecolaminas.", es: "Tumor de catecolaminas." }, difficulty: "dificil" },
    { id: 54, question: { pt: "Como a hiperprolactinemia causa infertilidade?", es: "¿Prolactina e infertilidad?" }, answer: { pt: "Inibindo a secreção pulsátil de GnRH, o que reduz FSH e LH.", es: "Inhibe GnRH." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual o papel do receptor de PTH (PTHR1) no osso?", es: "¿Receptor de PTH?" }, answer: { pt: "Acoplado à proteína Gs; estimula a via do AMPc nos osteoblastos (que ativam osteoclastos).", es: "Vía AMPc en hueso." }, difficulty: "dificil" },
    { id: 56, question: { pt: "Como o PTH atua no rim em relação ao fosfato?", es: "¿PTH y fosfato?" }, answer: { pt: "Inibe a reabsorção de fosfato no túbulo proximal (fosfatúria).", es: "Inhibe reabsorción de fosfato." }, difficulty: "dificil" },
    { id: 57, question: { pt: "O que é o sistema de transporte de hormônios esteroides?", es: "¿Transporte de esteroides?" }, answer: { pt: "Circulam ligados a proteínas como CBG (cortisol) ou SHBG (sexuais).", es: "Unidos a proteínas." }, difficulty: "dificil" },
    { id: 58, question: { pt: "Descreva a zona reticular da suprarrenal.", es: "¿Zona reticular?" }, answer: { pt: "Camada mais interna do córtex; produz andrógenos fracos (DHEA).", es: "Produce andrógenos." }, difficulty: "dificil" },
    { id: 59, question: { pt: "O que é o efeito incretina?", es: "¿Efeito incretina?" }, answer: { pt: "Aumento da secreção de insulina em resposta à glicose oral vs endovenosa (via GLP-1 e GIP).", es: "Mayor insulina vía oral." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Como a calcitonina inibe os osteoclastos?", es: "¿Calcitonina y osteoclastos?" }, answer: { pt: "Liga-se diretamente a receptores nos osteoclastos, reduzindo sua atividade absortiva.", es: "Frena a los osteoclastos." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_FISIO2_S4_B1 = FC_FISIO2_S4_B1;
}

// Bloco 2: Sistema Reprodutor
const FC_FISIO2_S4_B2 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "Qual a principal função do testículo?", es: "¿Función del testículo?" }, answer: { pt: "Produção de espermatozoides e testosterona.", es: "Producción de esperma y testosterona." }, difficulty: "facil" },
    { id: 2, question: { pt: "Qual a principal função do ovário?", es: "¿Función del ovario?" }, answer: { pt: "Produção de óvulos e hormônios (estrogênio e progesterona).", es: "Producción de óvulos y hormonas." }, difficulty: "facil" },
    { id: 3, question: { pt: "Onde ocorre a fertilização (fecundação)?", es: "¿Dónde ocurre la fecundación?" }, answer: { pt: "Nas tubas uterinas (trompas de Falópio).", es: "En las trompas de Falopio." }, difficulty: "facil" },
    { id: 4, question: { pt: "Qual o principal hormônio sexual masculino?", es: "¿Hormona sexual masculina?" }, answer: { pt: "Testosterona.", es: "Testosterona." }, difficulty: "facil" },
    { id: 5, question: { pt: "Quais os dois principais hormônios sexuais femininos?", es: "¿Hormonas sexuales femeninas?" }, answer: { pt: "Estrogênio e Progesterona.", es: "Estrógeno y Progesterona." }, difficulty: "facil" },
    { id: 6, question: { pt: "O que é o ciclo menstrual?", es: "¿Qué es el ciclo menstrual?" }, answer: { pt: "Série de mudanças mensais no corpo feminino para preparar para a gravidez.", es: "Ciclo de preparación para el embarazo." }, difficulty: "facil" },
    { id: 7, question: { pt: "O que é a ovulação?", es: "¿Qué es la ovulación?" }, answer: { pt: "Liberação do óvulo pelo ovário.", es: "Liberación del óvulo." }, difficulty: "facil" },
    { id: 8, question: { pt: "Qual hormônio causa o pico que leva à ovulação?", es: "¿Hormona que causa ovulación?" }, answer: { pt: "LH (Hormônio Luteinizante).", es: "LH." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é a menopausa?", es: "¿Qué es la menopausia?" }, answer: { pt: "Fim permanente dos ciclos menstruais e da fertilidade feminina.", es: "Fin de la fertilidad femenina." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que é a espermatogênese?", es: "¿Qué es espermatogénesis?" }, answer: { pt: "Processo de formação dos espermatozoides.", es: "Formación de espermatozoides." }, difficulty: "facil" },
    { id: 11, question: { pt: "Onde os espermatozoides amadurecem?", es: "¿Dónde maduran los espermatozoides?" }, answer: { pt: "No epidídimo.", es: "En el epidídimo." }, difficulty: "facil" },
    { id: 12, question: { pt: "Qual a função da próstata?", es: "¿Función de la próstata?" }, answer: { pt: "Produzir o fluido seminal que nutre e protege os espermatozoides.", es: "Produce fluido seminal." }, difficulty: "facil" },
    { id: 13, question: { pt: "Quanto tempo dura em média um ciclo menstrual?", es: "¿Cuánto dura el ciclo menstrual?" }, answer: { pt: "28 dias.", es: "28 días." }, difficulty: "facil" },
    { id: 14, question: { pt: "O que é o endométrio?", es: "¿Qué es el endometrio?" }, answer: { pt: "Camada interna do útero que descama durante a menstruação.", es: "Capa interna del útero." }, difficulty: "facil" },
    { id: 15, question: { pt: "Qual hormônio mantém o endométrio para a gravidez?", es: "¿Hormona que mantiene el endometrio?" }, answer: { pt: "Progesterona.", es: "Progesterona." }, difficulty: "facil" },
    { id: 16, question: { pt: "O que é o corpo lúteo?", es: "¿Qué es el cuerpo lúteo?" }, answer: { pt: "Estrutura do ovário que sobra após a ovulação e secreta progesterona.", es: "Estructura que secreta progesterona." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é o sêmen?", es: "¿Qué es el semen?" }, answer: { pt: "Mistura de espermatozoides e secreções das glândulas sexuais acessórias.", es: "Esperma y secreciones." }, difficulty: "facil" },
    { id: 18, question: { pt: "Qual a função do escroto?", es: "¿Función del escroto?" }, answer: { pt: "Manter os testículos em uma temperatura inferior à do corpo.", es: "Regular temperatura testicular." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que é a ereção?", es: "¿Qué es la erección?" }, answer: { pt: "Enchimento dos corpos cavernosos do pênis com sangue.", es: "Llenado de sangre en el pene." }, difficulty: "facil" },
    { id: 20, question: { pt: "Qual hormônio estimula o desenvolvimento dos caracteres sexuais secundários?", es: "¿Hormona de caracteres secundarios?" }, answer: { pt: "Testosterona (homens) e Estrogênio (mulheres).", es: "Testosterona y Estrógeno." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Qual a função das células de Leydig?", es: "¿Función de células de Leydig?" }, answer: { pt: "Produzir testosterona em resposta ao LH.", es: "Producen testosterona." }, difficulty: "medio" },
    { id: 22, question: { pt: "Qual a função das células de Sertoli?", es: "¿Función de células de Sertoli?" }, answer: { pt: "Nutrir e proteger os espermatozoides em desenvolvimento (barreira hematotesticular).", es: "Nutren espermatozoides." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que é a fase folicular do ciclo ovariano?", es: "¿Fase folicular?" }, answer: { pt: "Período de crescimento do folículo estimulado pelo FSH antes da ovulação.", es: "Crecimiento del folículo." }, difficulty: "medio" },
    { id: 24, question: { pt: "O que é a fase lútea do ciclo ovariano?", es: "¿Fase lútea?" }, answer: { pt: "Período após a ovulação dominado pela secreção de progesterona pelo corpo lúteo.", es: "Fase de progesterona." }, difficulty: "medio" },
    { id: 25, question: { pt: "Como a pílula anticoncepcional previne a gravidez?", es: "¿Cómo actúa la píldora?" }, answer: { pt: "Inibindo a secreção de FSH e LH, o que impede a ovulação.", es: "Inhibe la ovulación." }, difficulty: "medio" },
    { id: 26, question: { pt: "O que é o hormônio hCG?", es: "¿Qué es la hCG?" }, answer: { pt: "Gonadotrofina Coriônica Humana; mantém o corpo lúteo no início da gravidez.", es: "Mantiene el cuerpo lúteo." }, difficulty: "medio" },
    { id: 27, question: { pt: "Qual o papel do óxido nítrico na ereção peniana?", es: "¿Papel del NO en erección?" }, answer: { pt: "Relaxamento da musculatura lisa das artérias cavernosas, permitindo o fluxo sanguíneo.", es: "Relaja arterias del pene." }, difficulty: "medio" },
    { id: 28, question: { pt: "O que é a capacitação espermática?", es: "¿Capacitación espermática?" }, answer: { pt: "Mudanças funcionais que o espermatozoide sofre no trato feminino para poder fecundar.", es: "Cambios para fecundar." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que é a reação acrossômica?", es: "¿Reacción acrosómica?" }, answer: { pt: "Liberação de enzimas pelo espermatozoide para perfurar a zona pelúcida do óvulo.", es: "Liberación de enzimas." }, difficulty: "medio" },
    { id: 30, question: { pt: "Qual a função da inibina?", es: "¿Función de la inhibina?" }, answer: { pt: "Hormônio que inibe seletivamente a secreção de FSH.", es: "Inhibe el FSH." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que causa a menstruação?", es: "¿Qué causa la menstruación?" }, answer: { pt: "Queda nos níveis de estrogênio e progesterona devido à regressão do corpo lúteo.", es: "Baja de hormonas." }, difficulty: "medio" },
    { id: 32, question: { pt: "Qual a importância da barreira hematotesticular?", es: "¿Barrera hematotesticular?" }, answer: { pt: "Impedir que o sistema imune ataque os espermatozoides (que são geneticamente diferentes).", es: "Protege espermatozoides." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que é a fase proliferativa do ciclo uterino?", es: "¿Fase proliferativa?" }, answer: { pt: "Reconstituição do endométrio sob influência do estrogênio.", es: "Regeneración del endometrio." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é a fase secretora do ciclo uterino?", es: "¿Fase secretora?" }, answer: { pt: "Endométrio torna-se vascularizado e glandular sob influência da progesterona.", es: "Preparación para implante." }, difficulty: "medio" },
    { id: 35, question: { pt: "Qual a função da ocitocina no reflexo de ejeção de leite?", es: "¿Oxitocina y leche?" }, answer: { pt: "Contração das células mioepiteliais dos alvéolos mamários.", es: "Contracción de alvéolos." }, difficulty: "medio" },
    { id: 36, question: { pt: "Qual a função da prolactina?", es: "¿Función de la prolactina?" }, answer: { pt: "Estimular a síntese de leite (lactogênese).", es: "Síntesis de leche." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é a espermiogênese?", es: "¿Qué es espermiogénesis?" }, answer: { pt: "Etapa final da espermatogênese onde a espermátide vira espermatozoide.", es: "Espermátide -> esperma." }, difficulty: "medio" },
    { id: 38, question: { pt: "Qual o papel do feedback positivo do estrogênio no ciclo?", es: "¿Feedback positivo estrogénico?" }, answer: { pt: "Ocorre no final da fase folicular, desencadeando o pico de LH.", es: "Desencadena pico de LH." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é o bloqueio da poliespermia?", es: "¿Bloqueo de poliespermia?" }, answer: { pt: "Reação cortical que impede a entrada de mais de um espermatozoide no óvulo.", es: "Evita entrada de más esperma." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é a AMH (Hormônio Anti-Mülleriano)?", es: "¿Qué es AMH?" }, answer: { pt: "Hormônio que causa regressão dos ductos de Müller no feto masculino.", es: "Regresión de ductos de Müller." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a via de sinalização da Testosterona.", es: "¿Señalización testosterona?" }, answer: { pt: "Receptor androgênico intracelular que atua como fator de transcrição.", es: "Factor de transcripción." }, difficulty: "dificil" },
    { id: 42, question: { pt: "O que é a Di-hidrotestosterona (DHT)?", es: "¿Qué es la DHT?" }, answer: { pt: "Forma mais ativa da testosterona, convertida pela enzima 5-alfa-redutase.", es: "Forma activa de testosterona." }, difficulty: "dificil" },
    { id: 43, question: { pt: "O que é a aromatização?", es: "¿Qué es aromatización?" }, answer: { pt: "Conversão de andrógenos em estrógenos pela enzima aromatase.", es: "Andrógenos -> Estrógenos." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Como o FSH atua no testículo?", es: "¿FSH en testículo?" }, answer: { pt: "Liga-se às células de Sertoli para estimular a espermatogênese e síntese de ABP.", es: "Estimula Sertoli." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que é a Proteína Ligadora de Andrógenos (ABP)?", es: "¿Qué es ABP?" }, answer: { pt: "Proteína que mantém altas concentrações de testosterona dentro dos túbulos seminíferos.", es: "Mantiene testosterona alta." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Descreva a regulação pulsátil do GnRH.", es: "¿GnRH pulsátil?" }, answer: { pt: "Essencial para a função reprodutiva; secreção contínua causa dessensibilização da hipófise.", es: "Secreción por pulsos." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é a Atresia Folicular?", es: "¿Atresia folicular?" }, answer: { pt: "Morte programada dos folículos que não foram selecionados para a ovulação.", es: "Muerte de folículos." }, difficulty: "dificil" },
    { id: 48, question: { pt: "Qual a função do estrogênio na fase folicular?", es: "¿Estrógeno en fase folicular?" }, answer: { pt: "Estimula o crescimento endometrial e aumenta a sensibilidade da hipófise ao GnRH.", es: "Crecimiento endometrial." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Como a progesterona prepara o endométrio para a nidação?", es: "¿Progesterona y nidadación?" }, answer: { pt: "Aumenta a secreção de glicogênio e reduz a contratilidade uterina.", es: "Sube glucógeno, baja contracción." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é a Teoria das Duas Células para a síntese de estrogênio?", es: "¿Teoría de las dos células?" }, answer: { pt: "Células da Teca produzem andrógenos (via LH) e Células da Granulosa convertem em estrogênio (via FSH).", es: "Teca (LH) y Granulosa (FSH)." }, difficulty: "dificil" },
    { id: 51, question: { pt: "O que acontece com o corpo lúteo se não houver fecundação?", es: "¿Corpo lúteo sem fecundação?" }, answer: { pt: "Degenera em Corpo Albicans em cerca de 12-14 dias.", es: "Se vuelve Corpus Albicans." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Como o sildenafil (Viagra) facilita a ereção?", es: "¿Cómo actúa el sildenafil?" }, answer: { pt: "Inibindo a fosfodiesterase 5 (PDE5), mantendo os níveis de GMPc elevados.", es: "Inhibe PDE5." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é a amenorreia hipotalâmica?", es: "¿Amenorrea hipotalámica?" }, answer: { pt: "Interrupção da menstruação por falha no GnRH (ex: estresse, exercício extremo, baixo peso).", es: "Falla GnRH por estrés." }, difficulty: "dificil" },
    { id: 54, question: { pt: "Qual o papel da Kisspeptina na reprodução?", es: "¿Kisspeptina?" }, answer: { pt: "Neuropeptídeo hipotalâmico que regula a liberação de GnRH.", es: "Regula el GnRH." }, difficulty: "dificil" },
    { id: 55, question: { pt: "O que é a Síndrome de Ovários Policísticos (SOP) metabolicamente?", es: "¿SOP metabólicamente?" }, answer: { pt: "Hiperandrogenismo e resistência à insulina.", es: "Exceso de andrógenos." }, difficulty: "dificil" },
    { id: 56, question: { pt: "Como a placenta assume a produção de hormônios na gravidez?", es: "¿Placenta y hormonas?" }, answer: { pt: "A partir do 2º trimestre, a placenta substitui o corpo lúteo na produção de progesterona/estrogênio.", es: "Produce progesterona/estrógeno." }, difficulty: "dificil" },
    { id: 57, question: { pt: "O que é o lactogênio placentário humano (hPL)?", es: "¿Qué es hPL?" }, answer: { pt: "Hormônio que garante o suprimento de glicose para o feto aumentando a resistência à insulina materna.", es: "Sube glucosa fetal." }, difficulty: "dificil" },
    { id: 58, question: { pt: "Descreva a regulação da síntese de testosterona pelo feedback negativo.", es: "¿Feedback testosterona?" }, answer: { pt: "A testosterona inibe a secreção de GnRH (hipotálamo) e LH (hipófise).", es: "Inhibe GnRH y LH." }, difficulty: "dificil" },
    { id: 59, question: { pt: "O que é o reflexo de Ferguson?", es: "¿Reflexo de Ferguson?" }, answer: { pt: "Ciclo de feedback positivo onde a distensão cervical aumenta a liberação de ocitocina.", es: "Feedback distensión-oxitocina." }, difficulty: "dificil" },
    { id: 60, question: { pt: "Como os anabolizantes esteroides causam infertilidade masculina?", es: "¿Anabolizantes e infertilidad?" }, answer: { pt: "Inibem o eixo HPT, reduzindo o LH/FSH e a produção de testosterona intratesticular.", es: "Inhiben eje HPT." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_FISIO2_S4_B1 = FC_FISIO2_S4_B1;
    window.FC_FISIO2_S4_B2 = FC_FISIO2_S4_B2;
}

// Bloco 3: Sistema Nervoso Central
const FC_FISIO2_S4_B3 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "Qual a unidade funcional do sistema nervoso?", es: "¿Unidad funcional del sistema nervioso?" }, answer: { pt: "O neurônio.", es: "La neurona." }, difficulty: "facil" },
    { id: 2, question: { pt: "O que compõe o Sistema Nervoso Central (SNC)?", es: "¿Qué compone el SNC?" }, answer: { pt: "Encéfalo e medula espinhal.", es: "Encéfalo y médula espinal." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que é uma sinapse?", es: "¿Qué es una sinapsis?" }, answer: { pt: "Local de comunicação entre dois neurônios ou entre um neurônio e uma célula efetora.", es: "Comunicación entre neuronas." }, difficulty: "facil" },
    { id: 4, question: { pt: "Qual a função da bainha de mielina?", es: "¿Función de la mielina?" }, answer: { pt: "Aumentar a velocidade de condução do impulso nervoso.", es: "Aumentar velocidad del impulso." }, difficulty: "facil" },
    { id: 5, question: { pt: "O que são neurotransmissores?", es: "¿Qué son neurotransmisores?" }, answer: { pt: "Substâncias químicas que transmitem sinais através da sinapse.", es: "Mensajeros químicos sinápticos." }, difficulty: "facil" },
    { id: 6, question: { pt: "Qual o principal neurotransmissor excitatório do SNC?", es: "¿Principal excitador del SNC?" }, answer: { pt: "Glutamato.", es: "Glutamato." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual o principal neurotransmissor inibitório do SNC?", es: "¿Principal inhibidor del SNC?" }, answer: { pt: "GABA (Ácido Gama-Aminobutírico).", es: "GABA." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é o potencial de repouso de um neurônio?", es: "¿Potencial de reposo?" }, answer: { pt: "Diferença de carga elétrica através da membrana quando o neurônio não está estimulado (~ -70mV).", es: "Carga eléctrica en reposo." }, difficulty: "facil" },
    { id: 9, question: { pt: "O que é o potencial de ação?", es: "¿Qué es el potencial de acción?" }, answer: { pt: "Inversão rápida e temporária da polaridade da membrana (despolarização).", es: "Inversión de polaridad." }, difficulty: "facil" },
    { id: 10, question: { pt: "Qual íon entra na célula durante a despolarização?", es: "¿Qué ión entra en despolarización?" }, answer: { pt: "Sódio (Na+).", es: "Sodio." }, difficulty: "facil" },
    { id: 11, question: { pt: "Qual íon sai da célula durante a repolarização?", es: "¿Qué ión sale en repolarización?" }, answer: { pt: "Potássio (K+).", es: "Potasio." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que é o reflexo patelar?", es: "¿Qué es el reflejo patelar?" }, answer: { pt: "Reflexo medular simples de estiramento (monossináptico).", es: "Reflejo de estiramiento." }, difficulty: "facil" },
    { id: 13, question: { pt: "Qual a função do cerebelo?", es: "¿Función del cerebelo?" }, answer: { pt: "Coordenação motora, equilíbrio e postura.", es: "Coordinación y equilibrio." }, difficulty: "facil" },
    { id: 14, question: { pt: "Onde se localiza o centro respiratório?", es: "¿Centro respiratorio?" }, answer: { pt: "No tronco encefálico (bulbo e ponte).", es: "Tronco encefálico." }, difficulty: "facil" },
    { id: 15, question: { pt: "Qual a função do hipotálamo no SNC?", es: "¿Función del hipotálamo?" }, answer: { pt: "Regulação da homeostase (temperatura, fome, sede) e controle endócrino.", es: "Regulación de homeostasis." }, difficulty: "facil" },
    { id: 16, question: { pt: "O que é a barreira hematoencefálica?", es: "¿Barrera hematoencefálica?" }, answer: { pt: "Estrutura que protege o cérebro de substâncias tóxicas circulantes no sangue.", es: "Protección cerebral." }, difficulty: "facil" },
    { id: 17, question: { pt: "Qual lobo cerebral é responsável pela visão?", es: "¿Lóbulo de la visión?" }, answer: { pt: "Lobo Occipital.", es: "Lóbulo Occipital." }, difficulty: "facil" },
    { id: 18, question: { pt: "Qual lobo cerebral está associado a funções executivas e motoras?", es: "¿Lóbulo ejecutivo?" }, answer: { pt: "Lobo Frontal.", es: "Lóbulo Frontal." }, difficulty: "facil" },
    { id: 19, question: { pt: "O que são as meninges?", es: "¿Qué son las meninges?" }, answer: { pt: "Membranas que envolvem e protegem o SNC (dura-máter, aracnoide e pia-máter).", es: "Membranas protectoras." }, difficulty: "facil" },
    { id: 20, question: { pt: "Qual a função do líquido cefalorraquidiano (LCR)?", es: "¿Función del LCR?" }, answer: { pt: "Amortecer choques mecânicos e nutrir o tecido nervoso.", es: "Amortiguación y nutrición." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "O que é a condução saltatória?", es: "¿Conducción saltatoria?" }, answer: { pt: "Impulso nervoso que 'pula' de um nó de Ranvier para outro em fibras mielinizadas.", es: "Impulso entre nodos de Ranvier." }, difficulty: "medio" },
    { id: 22, question: { pt: "Qual a função da bomba de Sódio-Potássio (Na+/K+-ATPase) no neurônio?", es: "¿Función de la bomba Na/K?" }, answer: { pt: "Manter os gradientes de concentração iônica e o potencial de repouso.", es: "Mantiene el potencial de reposo." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que é um Potencial Pós-Sináptico Excitatório (PPSE)?", es: "¿Qué es un PPSE?" }, answer: { pt: "Despolarização local da membrana pós-sináptica.", es: "Despolarización local." }, difficulty: "medio" },
    { id: 24, question: { pt: "O que é um Potencial Pós-Sináptico Inibitório (PPSI)?", es: "¿Qué es un PPSI?" }, answer: { pt: "Hiperpolarização local da membrana pós-sináptica.", es: "Hiperpolarización local." }, difficulty: "medio" },
    { id: 25, question: { pt: "Qual a função do sistema límbico?", es: "¿Sistema límbico?" }, answer: { pt: "Processamento de emoções e memória.", es: "Emociones y memoria." }, difficulty: "medio" },
    { id: 26, question: { pt: "O que é a área de Broca?", es: "¿Área de Broca?" }, answer: { pt: "Área responsável pela produção da fala (articulação).", es: "Producción del habla." }, difficulty: "medio" },
    { id: 27, question: { pt: "O que é a área de Wernicke?", es: "¿Área de Wernicke?" }, answer: { pt: "Área responsável pela compreensão da linguagem.", es: "Comprensión del lenguaje." }, difficulty: "medio" },
    { id: 28, question: { pt: "Qual a função dos gânglios da base?", es: "¿Ganglios de la base?" }, answer: { pt: "Regulação do planejamento e execução de movimentos voluntários.", es: "Regulación del movimiento." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que é a neuroplasticidade?", es: "¿Neuroplasticidad?" }, answer: { pt: "Capacidade do sistema nervoso de mudar sua estrutura e função em resposta a estímulos.", es: "Cambios por estímulos." }, difficulty: "medio" },
    { id: 30, question: { pt: "Qual o papel do tálamo?", es: "¿Papel del tálamo?" }, answer: { pt: "Estação de retransmissão para quase todas as informações sensoriais que vão ao córtex.", es: "Estación sensorial." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que é o Sistema Ativador Reticular Ascendente (SARA)?", es: "¿SARA?" }, answer: { pt: "Sistema responsável pela manutenção do estado de vigília e alerta.", es: "Estado de alerta." }, difficulty: "medio" },
    { id: 32, question: { pt: "Como o sistema nervoso autônomo parassimpático afeta o coração?", es: "¿Parimpático en el corazón?" }, answer: { pt: "Diminui a frequência cardíaca (bradicardia) via nervo vago.", es: "Baja la frecuencia." }, difficulty: "medio" },
    { id: 33, question: { pt: "Como o sistema nervoso autônomo simpático afeta o coração?", es: "¿Simpático en el corazón?" }, answer: { pt: "Aumenta a frequência cardíaca e a força de contração.", es: "Sube la frecuencia." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é a somatopia (homúnculo de Penfield)?", es: "¿Somatotropía?" }, answer: { pt: "Mapeamento das partes do corpo em áreas específicas do córtex somatossensorial ou motor.", es: "Mapa corporal cortical." }, difficulty: "medio" },
    { id: 35, question: { pt: "Qual a função das células da glia (astrócitos)?", es: "¿Función de astrocitos?" }, answer: { pt: "Suporte metabólico, regulação do ambiente extracelular e formação da barreira hematoencefálica.", es: "Soporte y protección." }, difficulty: "medio" },
    { id: 36, question: { pt: "O que é a sinapse elétrica?", es: "¿Sinapsis eléctrica?" }, answer: { pt: "Comunicação direta via junções comunicantes (gap junctions), permitindo fluxo de íons.", es: "Vía gap junctions." }, difficulty: "medio" },
    { id: 37, question: { pt: "Qual o papel da acetilcolinesterase?", es: "¿Acetilcolinesterasa?" }, answer: { pt: "Degradar a acetilcolina na fenda sináptica para encerrar o sinal.", es: "Degrada acetilcolina." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que é a memória de curto prazo vs longo prazo?", es: "¿Memoria corto vs largo plazo?" }, answer: { pt: "Curto prazo: armazenamento temporário (segundos/minutos); Longo prazo: armazenamento duradouro (consolidação).", es: "Temporal vs duradera." }, difficulty: "medio" },
    { id: 39, question: { pt: "Qual a função do hipocampo?", es: "¿Función del hipocampo?" }, answer: { pt: "Consolidação de memórias declarativas e navegação espacial.", es: "Consolidación de memoria." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é o limiar de excitabilidade?", es: "¿Umbral de excitabilidad?" }, answer: { pt: "Nível crítico de despolarização necessário para disparar um potencial de ação.", es: "Nivel para disparar señal." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a Potenciação de Longa Duração (LTP).", es: "¿Qué es LTP?" }, answer: { pt: "Aumento persistente da força sináptica após estimulação repetida, base celular do aprendizado.", es: "Fortalecimiento sináptico." }, difficulty: "dificil" },
    { id: 42, question: { pt: "Como os receptores NMDA participam da plasticidade sináptica?", es: "¿Receptores NMDA?" }, answer: { pt: "Permitem a entrada de cálcio quando a membrana está despolarizada e o glutamato está presente.", es: "Entrada de calcio." }, difficulty: "dificil" },
    { id: 43, question: { pt: "O que é a via nigroestriatal e sua relação com o Parkinson?", es: "¿Vía nigroestriatal?" }, answer: { pt: "Via dopaminérgica da substância negra para o estriado; sua degeneração causa tremores e rigidez.", es: "Dopamina y Parkinson." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Descreva a função da bomba de prótons nas vesículas sinápticas.", es: "¿Bomba de protones sináptica?" }, answer: { pt: "Cria um gradiente eletroquímico para permitir o transporte de neurotransmissores para dentro da vesícula.", es: "Carga de vesículas." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que é a somação temporal e espacial?", es: "¿Sumación temporal y espacial?" }, answer: { pt: "Integração de múltiplos estímulos sinápticos no tempo ou de diferentes locais para atingir o limiar.", es: "Integración de estímulos." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Qual o papel das proteínas SNARE na sinapse?", es: "¿Proteínas SNARE?" }, answer: { pt: "Mediar a fusão da vesícula sináptica com a membrana plasmática para liberação do neurotransmissor.", es: "Fusión de vesículas." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é a modulação retrógrada por endocanabinoides?", es: "¿Modulación retrógrada?" }, answer: { pt: "Sinalização do neurônio pós-sináptico para o pré-sináptico para reduzir a liberação de neurotransmissor.", es: "Señal post a pre." }, difficulty: "dificil" },
    { id: 48, question: { pt: "Como o sono REM difere do NREM fisiologicamente?", es: "¿REM vs NREM?" }, answer: { pt: "REM tem atividade cerebral alta, sonhos intensos e atonia muscular; NREM tem ondas lentas.", es: "Actividad vs descanso." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Qual a função da amígdala no processamento do medo?", es: "¿Amígdala y miedo?" }, answer: { pt: "Atribuir significado emocional aos estímulos e coordenar a resposta de luta ou fuga.", es: "Procesa el miedo." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é a depressão de longa duração (LTD)?", es: "¿Qué es LTD?" }, answer: { pt: "Diminuição persistente da eficácia sináptica, processo oposto à LTP.", es: "Debilidad sináptica." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Como a toxina botulínica afeta a sinapse?", es: "¿Toxina botulínica?" }, answer: { pt: "Cliva proteínas SNARE, impedindo a liberação de acetilcolina e causando paralisia flácida.", es: "Inhibe acetilcolina." }, difficulty: "dificil" },
    { id: 52, question: { pt: "O que é o reflexo de retirada e o reflexo extensor cruzado?", es: "¿Reflejo extensor cruzado?" }, answer: { pt: "Retirada do membro de um estímulo doloroso enquanto o outro membro estende para manter equilíbrio.", es: "Retirada y equilibrio." }, difficulty: "dificil" },
    { id: 53, question: { pt: "Descreva a função do líquon na proteção contra o efeito de Monro-Kellie.", es: "¿Doctrina de Monro-Kellie?" }, answer: { pt: "Ajuste de volume de LCR e sangue para compensar aumentos de massa intracraniana.", es: "Ajuste de presión intracraneal." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é a penumbra isquêmica no AVC?", es: "¿Penumbra isquémica?" }, answer: { pt: "Área de tecido cerebral ao redor do núcleo do infarto que ainda é viável se o fluxo for restaurado.", es: "Tejido cerebral rescatable." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual o papel do núcleo supraquiasmático?", es: "¿Núcleo supraquiasmático?" }, answer: { pt: "Principal marcapasso do ritmo circadiano no hipotálamo, recebendo info da luz.", es: "Reloj biológico." }, difficulty: "dificil" },
    { id: 56, question: { pt: "Como o sistema glinfático atua durante o sono?", es: "¿Sistema glinfático?" }, answer: { pt: "Limpeza de resíduos metabólicos do SNC (como beta-amiloide) através do fluxo de LCR.", es: "Limpieza cerebral nocturna." }, difficulty: "dificil" },
    { id: 57, question: { pt: "O que é a excitotoxicidade por glutamato?", es: "¿Excitotoxicidad?" }, answer: { pt: "Morte neuronal causada por excesso de estímulo excitatório e entrada massiva de cálcio.", es: "Muerte por exceso de estímulo." }, difficulty: "dificil" },
    { id: 58, question: { pt: "Descreva a via de sinalização do receptor metabotrópico de GABA (GABA-B).", es: "¿Receptor GABA-B?" }, answer: { pt: "Acoplado à proteína Gi, abre canais de potássio ou inibe canais de cálcio (inibição lenta).", es: "Inhibición vía Gi." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Qual a função dos órgãos circunventriculares?", es: "¿Órganos circunventriculares?" }, answer: { pt: "Áreas do cérebro sem barreira hematoencefálica que monitoram o sangue diretamente.", es: "Cerebro sin barrera." }, difficulty: "dificil" },
    { id: 60, question: { pt: "O que é o fenômeno da 'mancha cega' na retina?", es: "¿Mancha ciega?" }, answer: { pt: "Ponto de saída do nervo óptico onde não existem fotorreceptores.", es: "Salida del nervo óptico." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_FISIO2_S4_B1 = FC_FISIO2_S4_B1;
    window.FC_FISIO2_S4_B2 = FC_FISIO2_S4_B2;
    window.FC_FISIO2_S4_B3 = FC_FISIO2_S4_B3;
}

// Bloco 4: Sentidos Especiais
const FC_FISIO2_S4_B4 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "Quais são os cinco sentidos especiais principais?", es: "¿Cinco sentidos especiales?" }, answer: { pt: "Visão, Audição, Olfato, Paladar e Equilíbrio.", es: "Visión, Audición, Olfato, Gusto y Equilibrio." }, difficulty: "facil" },
    { id: 2, question: { pt: "Qual a função da retina?", es: "¿Función de la retina?" }, answer: { pt: "Converter a luz em impulsos nervosos através de fotorreceptores.", es: "Convertir luz en señales nerviosas." }, difficulty: "facil" },
    { id: 3, question: { pt: "O que são os cones e para que servem?", es: "¿Qué son los conos?" }, answer: { pt: "Fotorreceptores responsáveis pela visão de cores e acuidade visual.", es: "Visión de colores." }, difficulty: "facil" },
    { id: 4, question: { pt: "O que são os bastonetes e para que servem?", es: "¿Qué son los bastoncillos?" }, answer: { pt: "Fotorreceptores sensíveis à luz, responsáveis pela visão noturna e periférica.", es: "Visión nocturna." }, difficulty: "facil" },
    { id: 5, question: { pt: "Onde se localiza o tímpano?", es: "¿Dónde está el tímpano?" }, answer: { pt: "Entre o ouvido externo e o ouvido médio.", es: "Entre el oído externo y medio." }, difficulty: "facil" },
    { id: 6, question: { pt: "Quais são os três ossículos do ouvido médio?", es: "¿Tres huesecillos del oído?" }, answer: { pt: "Martelo, Bigorna e Estribo.", es: "Martillo, Yunque y Estribo." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual a função da cóclea?", es: "¿Función de la cóclea?" }, answer: { pt: "Transdução de ondas sonoras em sinais elétricos (audição).", es: "Audición." }, difficulty: "facil" },
    { id: 8, question: { pt: "Onde se localizam os receptores do equilíbrio?", es: "¿Dónde están los receptores del equilibrio?" }, answer: { pt: "No vestíbulo e canais semicirculares do ouvido interno.", es: "Oído interno (vestíbulo)." }, difficulty: "facil" },
    { id: 9, question: { pt: "Qual nervo transmite a informação visual?", es: "¿Nervio de la visión?" }, answer: { pt: "Nervo Óptico (II par craniano).", es: "Nervio Óptico." }, difficulty: "facil" },
    { id: 10, question: { pt: "Qual nervo transmite a informação auditiva e de equilíbrio?", es: "¿Nervio de audición?" }, answer: { pt: "Nervo Vestibulococlear (VIII par craniano).", es: "Nervio Vestibulococlear." }, difficulty: "facil" },
    { id: 11, question: { pt: "O que é a íris?", es: "¿Qué es el iris?" }, answer: { pt: "Parte colorida do olho que regula a entrada de luz alterando o diâmetro da pupila.", es: "Parte coloreada del ojo." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que é o cristalino?", es: "¿Qué es el cristalino?" }, answer: { pt: "Lente biconvexa do olho que realiza a acomodação visual.", es: "Lente del ojo." }, difficulty: "facil" },
    { id: 13, question: { pt: "Quais são as sensações primárias do paladar?", es: "¿Sensaciones del gusto?" }, answer: { pt: "Doce, Salgado, Ácido, Amargo e Umami.", es: "Dulce, Salado, Ácido, Amargo, Umami." }, difficulty: "facil" },
    { id: 14, question: { pt: "Onde se localizam os receptores do olfato?", es: "¿Dónde están los receptores del olfato?" }, answer: { pt: "No epitélio olfatório, no teto das cavidades nasais.", es: "Epitelio olfatorio." }, difficulty: "facil" },
    { id: 15, question: { pt: "O que é a pupila?", es: "¿Qué es la pupila?" }, answer: { pt: "Orifício central da íris por onde a luz entra no olho.", es: "Orificio del iris." }, difficulty: "facil" },
    { id: 16, question: { pt: "Qual a função da córnea?", es: "¿Función de la córnea?" }, answer: { pt: "Principal superfície de refração da luz que entra no olho.", es: "Refracción de la luz." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que é a esclera?", es: "¿Qué es la esclera?" }, answer: { pt: "Camada externa branca e resistente do olho.", es: "Parte blanca del ojo." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que é o cerúmen e qual sua função?", es: "¿Cera del oído?" }, answer: { pt: "Cera produzida no canal auditivo para proteger contra poeira e microrganismos.", es: "Protección del oído." }, difficulty: "facil" },
    { id: 19, question: { pt: "Qual a importância da visão binocular?", es: "¿Visión binocular?" }, answer: { pt: "Permitir a percepção de profundidade (estereopsia).", es: "Percepción de profundidad." }, difficulty: "facil" },
    { id: 20, question: { pt: "O que é a fadiga olfatória?", es: "¿Fatiga olfatoria?" }, answer: { pt: "Adaptação rápida a um cheiro constante, deixando de percebê-lo.", es: "Adaptación al olor." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Como ocorre a acomodação visual para objetos próximos?", es: "¿Acomodación visual?" }, answer: { pt: "Contração do músculo ciliar, tornando o cristalino mais curvo/convexo.", es: "Cristalino más curvo." }, difficulty: "medio" },
    { id: 22, question: { pt: "O que é a miopia?", es: "¿Qué es la miopía?" }, answer: { pt: "Dificuldade de enxergar de longe; imagem se forma antes da retina.", es: "Imagen antes de retina." }, difficulty: "medio" },
    { id: 23, question: { pt: "O que é a hipermetropia?", es: "¿Qué es la hipermetropía?" }, answer: { pt: "Dificuldade de enxergar de perto; imagem se forma depois da retina.", es: "Imagen tras la retina." }, difficulty: "medio" },
    { id: 24, question: { pt: "O que é a presbiopia?", es: "¿Qué es la presbicia?" }, answer: { pt: "Perda da elasticidade do cristalino com a idade ('vista cansada').", es: "Pérdida de elasticidad." }, difficulty: "medio" },
    { id: 25, question: { pt: "Como as ondas sonoras são transmitidas do tímpano para a cóclea?", es: "¿Transmisión del sonido?" }, answer: { pt: "Através da vibração dos ossículos que pressionam a janela oval.", es: "Vibración de huesecillos." }, difficulty: "medio" },
    { id: 26, question: { pt: "Qual a função do Órgão de Corti?", es: "¿Función del Órgano de Corti?" }, answer: { pt: "Conter as células ciliadas que geram impulsos nervosos auditivos.", es: "Células ciliadas auditivas." }, difficulty: "medio" },
    { id: 27, question: { pt: "O que é a tonotopia na cóclea?", es: "¿Tonotopía coclear?" }, answer: { pt: "Mapeamento de frequências sonoras: base detecta sons agudos, ápice sons graves.", es: "Mapa de frecuencias." }, difficulty: "medio" },
    { id: 28, question: { pt: "Como os canais semicirculares detectam a rotação da cabeça?", es: "¿Detección de rotación?" }, answer: { pt: "Movimento da endolinfa que desloca a cúpula nas ampolas.", es: "Movimiento de endolinfa." }, difficulty: "medio" },
    { id: 29, question: { pt: "O que são otólitos e para que servem?", es: "¿Otólitos?" }, answer: { pt: "Cristais de carbonato de cálcio que detectam aceleração linear e gravidade.", es: "Aceleración linear." }, difficulty: "medio" },
    { id: 30, question: { pt: "Como as células receptoras do paladar sinalizam?", es: "¿Señalización del gusto?" }, answer: { pt: "Sal e Ácido via canais iônicos; Doce, Amargo e Umami via Proteína G (Gustducina).", es: "Canales vs Proteína G." }, difficulty: "medio" },
    { id: 31, question: { pt: "Qual a função das células basais no epitélio olfatório?", es: "¿Células basales olfatorias?" }, answer: { pt: "Células-tronco que regeneram os neurônios olfatórios (raro no SNC).", es: "Regeneración neuronal." }, difficulty: "medio" },
    { id: 32, question: { pt: "O que é o daltonismo?", es: "¿Daltonismo?" }, answer: { pt: "Deficiência genética em um ou mais tipos de cones (geralmente verde ou vermelho).", es: "Falla en los conos." }, difficulty: "medio" },
    { id: 33, question: { pt: "Qual o papel do humor aquoso?", es: "¿Humor acuoso?" }, answer: { pt: "Nutrir a córnea e o cristalino e manter a pressão intraocular.", es: "Nutrición y presión ocular." }, difficulty: "medio" },
    { id: 34, question: { pt: "O que é o glaucoma?", es: "¿Glaucoma?" }, answer: { pt: "Aumento da pressão intraocular que pode danificar o nervo óptico.", es: "Aumento de presión ocular." }, difficulty: "medio" },
    { id: 35, question: { pt: "O que são as células horizontais e amácrinas na retina?", es: "¿Células horizontales?" }, answer: { pt: "Células que realizam o processamento lateral da imagem (contraste e movimento).", es: "Procesamiento lateral." }, difficulty: "medio" },
    { id: 36, question: { pt: "Qual a função da trompa de Eustáquio (tuba auditiva)?", es: "¿Trompa de Eustaquio?" }, answer: { pt: "Igualar a pressão do ouvido médio com a pressão atmosférica.", es: "Igualar presiones." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é a percepção umami?", es: "¿Sabor Umami?" }, answer: { pt: "Sabor 'delicioso' associado ao glutamato monossódico (proteínas).", es: "Sabor a glutamato." }, difficulty: "medio" },
    { id: 38, question: { pt: "Como o cérebro diferencia a intensidade do som?", es: "¿Intensidad del sonido?" }, answer: { pt: "Pela frequência de disparos dos neurônios auditivos e número de células ativadas.", es: "Frecuencia de señales." }, difficulty: "medio" },
    { id: 39, question: { pt: "O que é o nistagmo?", es: "¿Nistagmo?" }, answer: { pt: "Movimento involuntário e rítmico dos olhos relacionado a distúrbios de equilíbrio.", es: "Movimiento ocular rítmico." }, difficulty: "medio" },
    { id: 40, question: { pt: "Qual o papel do bulbo olfatório?", es: "¿Bulbo olfatorio?" }, answer: { pt: "Processar e filtrar as informações olfatórias antes de enviá-las ao córtex.", es: "Procesa olores." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva o ciclo visual do retinol.", es: "¿Ciclo del retinol?" }, answer: { pt: "Isomerização do 11-cis-retinal em todo-trans-retinal pela luz, ativando a rodopsina.", es: "Activación de rodopsina." }, difficulty: "dificil" },
    { id: 42, question: { pt: "O que é a fototransdução (corrente de escuro)?", es: "¿Fototransducción?" }, answer: { pt: "No escuro, fotorreceptores estão despolarizados; a luz causa hiperpolarização (fecha canais de Na+).", es: "Luz hiperpolariza." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Qual a função da fosfodiesterase (PDE) na retina?", es: "¿PDE en la retina?" }, answer: { pt: "Degradar o GMPc em resposta à luz, fechando os canais iônicos.", es: "Degrada GMPc por luz." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Descreva a via visual no quiasma óptico.", es: "¿Quiasma óptico?" }, answer: { pt: "As fibras das metades nasais das retinas cruzam para o lado oposto.", es: "Cruce de fibras nasales." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que é o reflexo fotomotor?", es: "¿Reflejo fotomotor?" }, answer: { pt: "Constrição pupilar bilateral em resposta à luz em um dos olhos (miose).", es: "Contracción de pupilas." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Como as células ciliadas internas da cóclea se despolarizam?", es: "¿Despolarización auditiva?" }, answer: { pt: "Abertura mecânica de canais de Potássio (K+) no topo dos estereocílios (endolinfa é rica em K+).", es: "Entrada de Potasio." }, difficulty: "dificil" },
    { id: 47, question: { pt: "O que é a surdez de condução vs surdez neurossensorial?", es: "¿Sordera de conducción?" }, answer: { pt: "Condução: problema no ouvido externo/médio; Neurossensorial: problema na cóclea ou nervo.", es: "Mecánica vs Nerviosa." }, difficulty: "dificil" },
    { id: 48, question: { pt: "Qual a função das células ciliadas externas da cóclea?", es: "¿Células ciliadas externas?" }, answer: { pt: "Atuar como amplificadores cocleares através da proteína prestina.", es: "Amplificadores cocleares." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Como o cérebro localiza a fonte sonora horizontalmente?", es: "¿Localización del sonido?" }, answer: { pt: "Comparando a diferença de tempo e intensidade entre os dois ouvidos.", es: "Diferencia de tiempo." }, difficulty: "dificil" },
    { id: 50, question: { pt: "Descreva o reflexo vestíbulo-ocular (RVO).", es: "¿Reflejo vestíbulo-ocular?" }, answer: { pt: "Mantém a imagem estável na retina movendo os olhos em direção oposta ao movimento da cabeça.", es: "Estabiliza la visión." }, difficulty: "dificil" },
    { id: 51, question: { pt: "O que é a cinetose (enjoo de movimento)?", es: "¿Cinetosis?" }, answer: { pt: "Conflito sensorial entre as informações visuais e vestibulares.", es: "Conflicto visual-vestibular." }, difficulty: "dificil" },
    { id: 52, question: { pt: "Qual a importância da fovea centralis?", es: "¿Fóvea central?" }, answer: { pt: "Área de maior acuidade visual, contendo apenas cones densamente compactados.", es: "Máxima agudeza visual." }, difficulty: "dificil" },
    { id: 53, question: { pt: "O que é o campo receptivo 'centro-periferia' das células ganglionares?", es: "¿Campo receptivo retiniano?" }, answer: { pt: "Mecanismo de contraste onde a luz no centro estimula e na periferia inibe (ou vice-versa).", es: "Detección de contrastes." }, difficulty: "dificil" },
    { id: 54, question: { pt: "Como o olfato está ligado ao sistema límbico?", es: "¿Olfato y sistema límbico?" }, answer: { pt: "As vias olfatórias projetam-se diretamente para a amígdala e hipocampo (memória emocional).", es: "Memoria y emociones." }, difficulty: "dificil" },
    { id: 55, question: { pt: "O que é a anosmia?", es: "¿Anosmia?" }, answer: { pt: "Perda total do sentido do olfato.", es: "Pérdida del olfato." }, difficulty: "dificil" },
    { id: 56, question: { pt: "Qual o papel do córtex entorrinal no olfato?", es: "¿Córtex entorrinal?" }, answer: { pt: "Interface entre o processamento olfatório e a formação de memórias no hipocampo.", es: "Interface olfatorio-memoria." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Como as toxinas amargas são detectadas?", es: "¿Detección de amargos?" }, answer: { pt: "Receptores T2R acoplados à proteína G, com alta sensibilidade para proteção contra venenos.", es: "Receptores T2R." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que é o fenômeno da 'surdez tonal' (amusia)?", es: "¿Amusia?" }, answer: { pt: "Incapacidade de processar ou reproduzir tons musicais, apesar da audição normal.", es: "Falla en procesar música." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Descreva a função da via eferente auditiva.", es: "¿Vía eferente auditiva?" }, answer: { pt: "O cérebro modula a sensibilidade coclear para focar em sons específicos ou proteger contra ruídos.", es: "Modulación cerebral coclear." }, difficulty: "dificil" },
    { id: 60, question: { pt: "O que é a agnosia visual?", es: "¿Agnosia visual?" }, answer: { pt: "Incapacidade de reconhecer objetos ou rostos apesar da visão intacta (lesão em áreas associativas).", es: "Falla en reconocimiento." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_FISIO2_S4_B1 = FC_FISIO2_S4_B1;
    window.FC_FISIO2_S4_B2 = FC_FISIO2_S4_B2;
    window.FC_FISIO2_S4_B3 = FC_FISIO2_S4_B3;
    window.FC_FISIO2_S4_B4 = FC_FISIO2_S4_B4;
}

// Bloco 5: Integração Sensório-Motora
const FC_FISIO2_S4_B5 = [
    // FÁCIL (20 cards)
    { id: 1, question: { pt: "O que é o sistema somatossensorial?", es: "¿Sistema somatosensorial?" }, answer: { pt: "Sistema que processa sensações do corpo como tato, dor e temperatura.", es: "Procesa tacto, dolor y calor." }, difficulty: "facil" },
    { id: 2, question: { pt: "O que é a propriocepção?", es: "¿Qué es la propiocepción?" }, answer: { pt: "Sentido da posição e movimento das partes do corpo.", es: "Sentido de posición corporal." }, difficulty: "facil" },
    { id: 3, question: { pt: "Qual a função do fuso neuromuscular?", es: "¿Función del huso muscular?" }, answer: { pt: "Detectar o comprimento e a velocidade de estiramento do músculo.", es: "Detecta estiramiento muscular." }, difficulty: "facil" },
    { id: 4, question: { pt: "Qual a função do órgão tendinoso de Golgi (OTG)?", es: "¿Función del OTG?" }, answer: { pt: "Detectar a tensão exercida sobre o tendão durante a contração muscular.", es: "Detecta tensión en tendones." }, difficulty: "facil" },
    { id: 5, question: { pt: "O que é um dermátomo?", es: "¿Qué es un dermatoma?" }, answer: { pt: "Área da pele suprida por um único nervo espinhal.", es: "Área de piel por un nervio." }, difficulty: "facil" },
    { id: 6, question: { pt: "Qual área do cérebro é o centro primário do tato?", es: "¿Centro primario del tacto?" }, answer: { pt: "Córtex Somatossensorial Primário (Giro Pós-central).", es: "Córtex somatosensorial." }, difficulty: "facil" },
    { id: 7, question: { pt: "Qual área do cérebro inicia o movimento voluntário?", es: "¿Inicia el movimiento voluntario?" }, answer: { pt: "Córtex Motor Primário (Giro Pré-central).", es: "Córtex motor primario." }, difficulty: "facil" },
    { id: 8, question: { pt: "O que é uma unidade motora?", es: "¿Unidad motora?" }, answer: { pt: "Um motoneurônio alfa e todas as fibras musculares que ele inerva.", es: "Neurona y fibras que inerva." }, difficulty: "facil" },
    { id: 9, question: { pt: "Qual a função da medula espinhal na motricidade?", es: "¿Médula y motricidad?" }, answer: { pt: "Integrar reflexos e conduzir sinais entre o cérebro e os músculos.", es: "Integra reflejos." }, difficulty: "facil" },
    { id: 10, question: { pt: "O que é o tônus muscular?", es: "¿Qué es el tono muscular?" }, answer: { pt: "Estado de contração leve e constante do músculo em repouso.", es: "Contracción leve en reposo." }, difficulty: "facil" },
    { id: 11, question: { pt: "O que são mecanorreceptores?", es: "¿Mecanorreceptores?" }, answer: { pt: "Receptores sensíveis a estímulos físicos como pressão e vibração.", es: "Sensibles a presión física." }, difficulty: "facil" },
    { id: 12, question: { pt: "O que são termorreceptores?", es: "¿Termorreceptores?" }, answer: { pt: "Receptores que detectam variações de temperatura.", es: "Detectan temperatura." }, difficulty: "facil" },
    { id: 13, question: { pt: "O que são nociceptores?", es: "¿Nociceptores?" }, answer: { pt: "Receptores que detectam estímulos nocivos que causam dor.", es: "Detectan el dolor." }, difficulty: "facil" },
    { id: 14, question: { pt: "Qual o papel do tronco encefálico no equilíbrio?", es: "¿Tronco encefálico y equilibrio?" }, answer: { pt: "Integrar sinais vestibulares, visuais e proprioceptivos para manter a postura.", es: "Mantiene la postura." }, difficulty: "facil" },
    { id: 15, question: { pt: "O que é a via piramidal (corticoespinhal)?", es: "¿Vía piramidal?" }, answer: { pt: "Principal via nervosa para o controle do movimento voluntário fino.", es: "Control motor voluntario." }, difficulty: "facil" },
    { id: 16, question: { pt: "O que é a decussação das pirâmides?", es: "¿Decusación de pirámides?" }, answer: { pt: "Cruzamento das fibras motoras para o lado oposto no bulbo.", es: "Cruce de fibras motoras." }, difficulty: "facil" },
    { id: 17, question: { pt: "O que acontece em uma lesão de motoneurônio inferior?", es: "¿Lesión de motoneurona inferior?" }, answer: { pt: "Paralisia flácida, atrofia e perda de reflexos.", es: "Parálisis flácida." }, difficulty: "facil" },
    { id: 18, question: { pt: "O que acontece em uma lesão de motoneurônio superior?", es: "¿Lesión de motoneurona superior?" }, answer: { pt: "Paralisia espástica, hiperreflexia e sinal de Babinski.", es: "Parálisis espástica." }, difficulty: "facil" },
    { id: 19, question: { pt: "Qual a função do cerebelo no movimento?", es: "¿Cerebelo en el movimiento?" }, answer: { pt: "Corrigir erros de movimento em tempo real (comparador).", es: "Corrige movimientos." }, difficulty: "facil" },
    { id: 20, question: { pt: "O que é o reflexo de flexão?", es: "¿Reflejo de flexión?" }, answer: { pt: "Retirada automática de um membro de um estímulo doloroso.", es: "Retirada ante dolor." }, difficulty: "facil" },

    // MÉDIO (20 cards)
    { id: 21, question: { pt: "Qual a diferença entre fibras motoras Alfa e Gama?", es: "¿Motoneuronas Alfa vs Gama?" }, answer: { pt: "Alfa inervam fibras extrafusais (contração); Gama inervam fibras intrafusais (ajuste do fuso).", es: "Contracción vs Ajuste." }, difficulty: "medio" },
    { id: 22, question: { pt: "O que é a coativação Alfa-Gama?", es: "¿Coactivación Alfa-Gama?" }, answer: { pt: "Contração simultânea que mantém a sensibilidade do fuso durante o encurtamento muscular.", es: "Mantiene sensibilidad del huso." }, difficulty: "medio" },
    { id: 23, question: { pt: "Como o Órgão Tendinoso de Golgi protege o músculo?", es: "¿Cómo protege el OTG?" }, answer: { pt: "Causa relaxamento reflexo (inibição autógena) quando a tensão é excessiva.", es: "Relajación por tensión." }, difficulty: "medio" },
    { id: 24, question: { pt: "Descreva a via da coluna dorsal-lemnisco medial.", es: "¿Vía columna dorsal?" }, answer: { pt: "Transmite tato fino, vibração e propriocepção consciente; cruza no bulbo.", es: "Tacto fino y vibración." }, difficulty: "medio" },
    { id: 25, question: { pt: "Descreva a via anterolateral (espinotalâmica).", es: "¿Vía espinotalámica?" }, answer: { pt: "Transmite dor e temperatura; cruza imediatamente na medula.", es: "Dolor y temperatura." }, difficulty: "medio" },
    { id: 26, question: { pt: "O que é a dor referida?", es: "¿Qué es el dolor referido?" }, answer: { pt: "Percepção de dor visceral em uma área somática (ex: dor no braço no infarto).", es: "Dolor visceral sentido en piel." }, difficulty: "medio" },
    { id: 27, question: { pt: "Qual o papel do córtex pré-motor?", es: "¿Papel del córtex premotor?" }, answer: { pt: "Planejamento de movimentos complexos e coordenação bilateral.", es: "Planeamiento motor." }, difficulty: "medio" },
    { id: 28, question: { pt: "Qual a função da área motora suplementar (AMS)?", es: "¿Área motora suplementaria?" }, answer: { pt: "Planejamento de sequências de movimentos internos (ex: tocar piano).", es: "Secuencias complejas." }, difficulty: "medio" },
    { id: 29, question: { pt: "Como os gânglios da base facilitam o movimento?", es: "¿Ganglios de la base y movimiento?" }, answer: { pt: "Através da via direta (estimula o córtex) e via indireta (inibe movimentos indesejados).", es: "Vía directa e indirecta." }, difficulty: "medio" },
    { id: 30, question: { pt: "O que é o tremor de intenção?", es: "¿Tremor de intención?" }, answer: { pt: "Tremor que aparece durante o movimento voluntário, típico de lesão cerebelar.", es: "Típico de lesión cerebelar." }, difficulty: "medio" },
    { id: 31, question: { pt: "O que é a dismetria?", es: "¿Qué es la dismetría?" }, answer: { pt: "Incapacidade de controlar a amplitude do movimento (passar do alvo), sinal cerebelar.", es: "Falla en medir distancia." }, difficulty: "medio" },
    { id: 32, question: { pt: "O que é a propriocepção inconsciente e quem a processa?", es: "¿Propiocepción inconsciente?" }, answer: { pt: "Informação sobre o estado muscular enviada ao cerebelo via tratos espinocerebelares.", es: "Va al cerebelo." }, difficulty: "medio" },
    { id: 33, question: { pt: "O que é a adaptação dos receptores sensoriais?", es: "¿Adaptación sensorial?" }, answer: { pt: "Diminuição da resposta do receptor a um estímulo constante (Fásicos adaptam rápido; Tônicos devagar).", es: "Baja respuesta a estímulo fijo." }, difficulty: "medio" },
    { id: 34, question: { pt: "Qual a função dos corpúsculos de Pacini?", es: "¿Corpúsculos de Pacini?" }, answer: { pt: "Detectar vibrações de alta frequência e pressão profunda.", es: "Vibración rápida." }, difficulty: "medio" },
    { id: 35, question: { pt: "Qual a função dos corpúsculos de Meissner?", es: "¿Corpúsculos de Meissner?" }, answer: { pt: "Detectar tato leve e discriminação de texturas em áreas sem pelos.", es: "Tacto leve." }, difficulty: "medio" },
    { id: 36, question: { pt: "O que é o sistema motor extrapiramidal?", es: "¿Sistema extrapiramidal?" }, answer: { pt: "Vias que regulam o tônus, postura e movimentos automáticos (ex: rubroespinhal).", es: "Movimientos automáticos." }, difficulty: "medio" },
    { id: 37, question: { pt: "O que é a espasticidade?", es: "¿Qué es la espasticidad?" }, answer: { pt: "Aumento do tônus muscular dependente da velocidade de estiramento (lesão de via motora superior).", es: "Tono muscular alto." }, difficulty: "medio" },
    { id: 38, question: { pt: "O que é o choque medular?", es: "¿Choque medular?" }, answer: { pt: "Perda temporária de todas as funções reflexas abaixo de uma lesão medular aguda.", es: "Pérdida de reflejos tras trauma." }, difficulty: "medio" },
    { id: 39, question: { pt: "Qual o papel do núcleo rubro?", es: "¿Papel del núcleo rojo?" }, answer: { pt: "Controle de movimentos dos grandes músculos distais dos membros.", es: "Control motor distal." }, difficulty: "medio" },
    { id: 40, question: { pt: "O que é a discinesia?", es: "¿Qué es la discinesia?" }, answer: { pt: "Movimentos anormais e involuntários, frequentemente por disfunção dos gânglios da base.", es: "Movimientos involuntarios." }, difficulty: "medio" },

    // DIFÍCIL (20 cards)
    { id: 41, question: { pt: "Descreva a Teoria das Comportas (Gate Control) da dor.", es: "¿Teoría de las compuertas?" }, answer: { pt: "Fibras táteis (A-beta) ativam interneurônios que inibem a transmissão da dor (fibras C) na medula.", es: "Tacto inhibe dolor." }, difficulty: "dificil" },
    { id: 42, question: { pt: "O que é a hiperalgesia primária e secundária?", es: "¿Hiperalgesia?" }, answer: { pt: "Primária: aumento da sensibilidade no local da lesão; Secundária: em tecidos vizinhos normais.", es: "Sensibilidad aumentada." }, difficulty: "dificil" },
    { id: 43, question: { pt: "Qual a função da via espinotalâmica lateral vs anterior?", es: "¿Espinotalámica Lat vs Ant?" }, answer: { pt: "Lateral: dor e temperatura; Anterior: tato grosseiro e pressão.", es: "Dolor vs Tacto grueso." }, difficulty: "dificil" },
    { id: 44, question: { pt: "Como o cerebelo realiza o 'aprendizado motor'?", es: "¿Aprendizaje cerebelar?" }, answer: { pt: "Através da modulação das sinapses entre fibras paralelas e células de Purkinje pelas fibras trepadeiras.", es: "Células de Purkinje." }, difficulty: "dificil" },
    { id: 45, question: { pt: "O que é a Síndrome de Brown-Séquard?", es: "¿Síndrome de Brown-Séquard?" }, answer: { pt: "Hemissecção da medula: perda motora/proprioceptiva ipsilateral e perda de dor/temp contralateral.", es: "Lesión de media médula." }, difficulty: "dificil" },
    { id: 46, question: { pt: "Descreva a via das células de Purkinje no cerebelo.", es: "¿Células de Purkinje?" }, answer: { pt: "São as únicas eferências do córtex cerebelar e são sempre inibitórias (GABA).", es: "Eferencias inibitorias." }, difficulty: "dificil" },
    { id: 47, question: { pt: "Qual o papel da Substância P no corno dorsal da medula?", es: "¿Sustancia P?" }, answer: { pt: "Neurotransmissor que facilita a transmissão de sinais de dor intensa ou crônica.", es: "Transmite dolor intenso." }, difficulty: "dificil" },
    { id: 48, question: { pt: "O que é a sensibilização central?", es: "¿Sensibilización central?" }, answer: { pt: "Aumento da excitabilidade dos neurônios medulares, levando a alodinia e dor crônica.", es: "Hipersensibilidad medular." }, difficulty: "dificil" },
    { id: 49, question: { pt: "Como a dopamina modula a via direta e indireta?", es: "¿Dopamina y vías motoras?" }, answer: { pt: "Estimula a via direta (receptores D1) e inibe a via indireta (receptores D2), facilitando o movimento.", es: "Facilita movimiento." }, difficulty: "dificil" },
    { id: 50, question: { pt: "O que é a rigidez em 'roda dentada'?", es: "¿Rigidez en rueda dentada?" }, answer: { pt: "Rigidez muscular com interrupções rítmicas durante o movimento passivo, comum no Parkinson.", es: "Signo de Parkinson." }, difficulty: "dificil" },
    { id: 51, question: { pt: "Qual a função dos tratos vestibuloespinhais?", es: "¿Tratos vestibuloespinales?" }, answer: { pt: "Manter o equilíbrio e a postura ativando músculos extensores (antigravitários).", es: "Postura y equilibrio." }, difficulty: "dificil" },
    { id: 52, question: { pt: "O que é a inibição recíproca?", es: "¿Inhibición recíproca?" }, answer: { pt: "Relaxamento reflexo do músculo antagonista enquanto o agonista se contrai.", es: "Relaja el antagonista." }, difficulty: "dificil" },
    { id: 53, question: { pt: "Descreva o fenômeno de 'ponto e círculo' (discriminação de dois pontos).", es: "¿Discriminación de dos puntos?" }, answer: { pt: "Capacidade de distinguir dois estímulos táteis próximos; maior em pontas de dedos devido a campos pequenos.", es: "Resolución táctil." }, difficulty: "dificil" },
    { id: 54, question: { pt: "O que é a ataxia?", es: "¿Qué es la ataxia?" }, answer: { pt: "Incoordenação dos movimentos voluntários e do equilíbrio por disfunção cerebelar ou proprioceptiva.", es: "Incoordinación motora." }, difficulty: "dificil" },
    { id: 55, question: { pt: "Qual a função do sistema opioide endógeno na dor?", es: "¿Opioides endógenos?" }, answer: { pt: "Ativar vias descendentes inibitórias que bloqueiam a dor na medula (Substância cinzenta periaquedutal).", es: "Inhibición del dolor." }, difficulty: "dificil" },
    { id: 56, question: { pt: "O que é a alodinia?", es: "¿Qué es la alodinia?" }, answer: { pt: "Percepção de dor frente a um estímulo que normalmente não é doloroso (ex: toque leve em queimadura).", es: "Dolor por estímulo inocuo." }, difficulty: "dificil" },
    { id: 57, question: { pt: "Qual o papel do núcleo ventral póstero-lateral (VPL) do tálamo?", es: "¿Núcleo VPL?" }, answer: { pt: "Principal núcleo de retransmissão sensorial para o corpo (viaja para o córtex S1).", es: "Relevo sensorial del cuerpo." }, difficulty: "dificil" },
    { id: 58, question: { pt: "O que é o princípio do tamanho de Henneman?", es: "¿Principio de Henneman?" }, answer: { pt: "Unidades motoras menores são recrutadas primeiro para garantir controle fino.", es: "Reclutamiento por tamaño." }, difficulty: "dificil" },
    { id: 59, question: { pt: "Como a toxina tetânica causa paralisia espástica?", es: "¿Tétanos y parálisis?" }, answer: { pt: "Bloqueia a liberação de GABA/Glicina em interneurônios inibitórios da medula.", es: "Bloqueo de inhibición." }, difficulty: "dificil" },
    { id: 60, question: { pt: "O que caracteriza a heminegligência espacial?", es: "¿Heminegligencia?" }, answer: { pt: "Incapacidade de perceber estímulos em um lado do espaço, geralmente por lesão no lobo parietal direito.", es: "Ignorar medio campo visual." }, difficulty: "dificil" }
];

if (typeof window !== 'undefined') {
    window.FC_FISIO2_S4_B1 = FC_FISIO2_S4_B1;
    window.FC_FISIO2_S4_B2 = FC_FISIO2_S4_B2;
    window.FC_FISIO2_S4_B3 = FC_FISIO2_S4_B3;
    window.FC_FISIO2_S4_B4 = FC_FISIO2_S4_B4;
    window.FC_FISIO2_S4_B5 = FC_FISIO2_S4_B5;
}
