window.RESUMOS_ANATOMY1 = {
    50: { title: "Introdução à Anatomia", content: `
<div class="resumo-header-main"><h2>🔬 Os Fundamentos da Anatomia</h2><p>Terminologia, posição anatômica e os planos de secção que organizam o estudo do corpo humano.</p></div>
<div class="resumo-section"><h3>🧍 Posição Anatômica Universal</h3><div class="resumo-accordion open"><div class="resumo-accordion-header"><h4>A posição de referência (Clique)</h4><span class="resumo-accordion-arrow">▼</span></div><div class="resumo-accordion-body"><p>Paciente em pé, olhando para frente, membros superiores ao lado do corpo com <strong>palmas voltadas para frente</strong> (supinação). TODOS os termos anatômicos se referem a esta posição, independente de como o paciente está deitado na mesa.</p></div></div></div>
<div class="resumo-section"><h3>✂️ Os Planos de Secção</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">↕️</div><div class="flip-label">Plano Sagital</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Divide o corpo em porções <strong>Direita e Esquerda</strong>. O plano sagital mediano passa exatamente pelo meio. Ex: RM de coluna vertebral.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">↔️</div><div class="flip-label">Plano Coronal (Frontal)</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Divide em porções <strong>Anterior e Posterior</strong>. Paralelo à fronte. Ex: corte coronal do cérebro mostra os ventrículos laterais.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🔲</div><div class="flip-label">Plano Transversal (Axial)</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Divide em porções <strong>Superior e Inferior</strong>. Perpendicular ao eixo longo do corpo. Ex: TC de abdome — cortes "fatias" horizontais.</div></div></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Em uma TC de tórax, os cortes mostram o coração, pulmões e aorta em fatia horizontal. Qual plano de secção é utilizado?</div><div class="resumo-quiz-answer"><strong>Plano Transversal (Axial).</strong> A TC é realizada com cortes no plano transversal/axial por padrão, dividindo o corpo em porções superior e inferior a cada fatia.</div></div></div>` },

    51: { title: "Posição Anatômica e Planos", content: `
<div class="resumo-header-main"><h2>📐 Termos de Posição e Direção</h2><p>A língua universal que permite que médicos de qualquer país descrevam a mesma estrutura sem ambiguidade.</p></div>
<div class="resumo-section"><h3>🗺️ Os Pares de Termos Opostos</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Superior / Inferior:</strong> Mais próximo da cabeça vs mais próximo dos pés. Ex: O joelho é <em>inferior</em> ao quadril.</div>
<div class="resumo-timeline-item"><strong>Anterior (Ventral) / Posterior (Dorsal):</strong> Mais à frente vs mais atrás. Ex: O esterno é <em>anterior</em> à coluna vertebral.</div>
<div class="resumo-timeline-item"><strong>Medial / Lateral:</strong> Mais perto da linha média vs mais longe. Ex: O nariz é <em>medial</em> aos olhos.</div>
<div class="resumo-timeline-item"><strong>Proximal / Distal:</strong> Mais perto da raiz do membro vs mais longe. Ex: O cotovelo é <em>proximal</em> ao punho.</div>
<div class="resumo-timeline-item"><strong>Superficial / Profundo:</strong> Mais perto da superfície vs mais interno. Ex: A pele é <em>superficial</em> ao músculo.</div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Descreva a relação entre o Rádio e a Ulna usando os termos anatômicos corretos (em posição anatômica).</div><div class="resumo-quiz-answer">O <strong>Rádio é lateral</strong> à Ulna (fica no lado do polegar, que está lateralizado na posição anatômica com palmas para frente). A <strong>Ulna é medial</strong> ao Rádio (fica do lado do dedo mínimo). Ambos são ossos <em>paralelos</em> e <em>no mesmo plano</em>, portanto nenhum é proximal ou distal em relação ao outro.</div></div></div>` },

    52: { title: "Termos de Relação e Movimento", content: `
<div class="resumo-header-main"><h2>🤸 Os Movimentos do Corpo Humano</h2><p>Cada articulação tem seus movimentos específicos. Saber nomear o movimento é essencial na avaliação clínica.</p></div>
<div class="resumo-section"><h3>🔄 Movimentos Fundamentais</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">📐</div><div class="flip-label">Flexão / Extensão</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back"><strong>Flexão:</strong> diminui o ângulo da articulação (dobrar o cotovelo). <strong>Extensão:</strong> aumenta o ângulo (esticar o cotovelo). Exceção: o tornozelo — dorsiflexão (pé para cima) e flexão plantar (pé para baixo).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">↔️</div><div class="flip-label">Abdução / Adução</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back"><strong>Abdução:</strong> afasta da linha média (levantar o braço lateralmente). <strong>Adução:</strong> aproxima da linha média (baixar o braço). Para os dedos, a referência é o dedo médio (3º).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🔁</div><div class="flip-label">Rotação e Circundução</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back"><strong>Rotação Medial:</strong> gira em direção à linha média. <strong>Rotação Lateral:</strong> gira para fora. <strong>Circundução:</strong> combinação de todos (movimento cônico — ombro e quadril).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🖐️</div><div class="flip-label">Pronação / Supinação</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Exclusivo do antebraço. <strong>Supinação:</strong> palma para cima (posição anatômica — "segura a sopa"). <strong>Pronação:</strong> palma para baixo. O rádio cruza sobre a ulna na pronação.</div></div></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um paciente não consegue realizar supinação do antebraço direito após fratura. Qual osso provavelmente está fraturado e qual músculo principal realiza esse movimento?</div><div class="resumo-quiz-answer">Provavelmente o <strong>Rádio</strong> está fraturado (ele é o osso que roda sobre a ulna durante a supinação). O principal músculo da supinação é o <strong>Músculo Supinador</strong> (inervado pelo nervo radial profundo), auxiliado pelo <strong>Bíceps Braquial</strong> (especialmente com o cotovelo fletido).</div></div></div>` },

    53: { title: "Osteologia: Conceitos Básicos", content: `
<div class="resumo-header-main"><h2>🦴 O Tecido Ósseo: Muito Mais que Pedra</h2><p>O osso é um tecido vivo, vascularizado, que se remodela constantemente e responde a forças mecânicas.</p></div>
<div class="resumo-section"><h3>🏗️ Classificação dos Ossos por Forma</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Longos:</strong> Diáfise + 2 Epífises. Ex: Fêmur, Úmero. Crescimento em comprimento pela placa epifisária (cartilagem de crescimento). Principal local de produção de células sanguíneas (medula vermelha).</div>
<div class="resumo-timeline-item"><strong>Curtos:</strong> Cúbicos. Ex: Carpo, Tarso. Resistência a compressão.</div>
<div class="resumo-timeline-item"><strong>Planos:</strong> Protetores e para inserção muscular. Ex: Crânio, Escápula, Esterno, Costelas.</div>
<div class="resumo-timeline-item"><strong>Irregulares:</strong> Formas complexas. Ex: Vértebras, Ossos da face.</div>
<div class="resumo-timeline-item"><strong>Sesamoides:</strong> Formados dentro de tendões. Ex: Patela (joelho). Protegem o tendão de forças compressivas.</div>
</div></div>
<div class="resumo-section"><h3>🔬 Remodelação Óssea e Células</h3><div class="resumo-compare">
<div class="resumo-compare-item" style="--compare-color: #ef4444"><h5>Osteoclasto (Destrói)</h5><p>Células gigantes multinucleadas. Reabsorvem osso secretando ácido e enzimas. Derivam de monócitos. Estimulados pelo PTH e RANKL. Inibidos pelos Bifosfonatos (Alendronato — tto de Osteoporose).</p></div>
<div class="resumo-compare-item" style="--compare-color: #10b981"><h5>Osteoblasto (Constrói)</h5><p>Formam novo osso depositando colágeno e minerais. Estimulados por Estrogênio, GH, IGF-1. Marcador: Fosfatase Alcalina (elevada em fraturas e Doença de Paget).</p></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Uma mulher pós-menopausa desenvolve osteoporose. Explique o mecanismo hormonal que leva à perda óssea nessa condição.</div><div class="resumo-quiz-answer">A queda do <strong>estrogênio</strong> após a menopausa remove seu efeito inibitório sobre os <strong>Osteoclastos</strong>. O estrogênio normalmente inibe a produção de RANKL e estimula a apoptose dos osteoclastos. Sem ele, os osteoclastos ficam hiperativados, a reabsorção óssea supera a formação → perda de massa óssea → osteoporose. Tratamento: Bifosfonatos (inibem osteoclastos), Cálcio + Vitamina D.</div></div></div>` },

    54: { title: "Osteologia: Esqueleto Axial", content: `
<div class="resumo-header-main"><h2>🏛️ O Eixo Central do Corpo</h2><p>Crânio, coluna vertebral, costelas e esterno — a estrutura que protege o SNC e os órgãos vitais.</p></div>
<div class="resumo-section"><h3>🦴 A Coluna Vertebral</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Cervical (C1-C7):</strong> 7 vértebras. C1 = Atlas (sustenta o crânio, permite nodding "sim"). C2 = Áxis (tem o dente, permite rotação "não"). C3-C7: típicas com forame transversário (por onde passa a artéria vertebral).</div>
<div class="resumo-timeline-item"><strong>Torácica (T1-T12):</strong> 12 vértebras. Articulam com costelas (fóveas costais no corpo e processo transverso). Corpo em forma de coração.</div>
<div class="resumo-timeline-item"><strong>Lombar (L1-L5):</strong> 5 vértebras. Maiores e mais robustas. Suportam maior peso. Sem forame transversário, sem fóveas costais. Punção lombar entre L3-L4 ou L4-L5 (abaixo de L1, onde termina a medula).</div>
<div class="resumo-timeline-item"><strong>Sacro e Cóccix:</strong> Fusionados. Sacro: 5 vértebras fundidas, forma a parede posterior da pelve. Canal sacral contém raízes da cauda equina.</div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um médico realiza uma punção lombar (raquianestesia) e introduz a agulha entre L4-L5. Por que esse espaço é seguro — ou seja, por que a agulha não vai lesar a medula espinal?</div><div class="resumo-quiz-answer">A medula espinal termina no adulto em <strong>L1-L2</strong> (cone medular). Abaixo disso, o canal vertebral contém apenas as raízes nervosas da <strong>Cauda Equina</strong> flutuando no líquor. Ao inserir a agulha em L4-L5, ela passa entre essas raízes (que se desviam), sem risco de lesão medular direta. O líquor pode ser coletado ou anestésico injetado com segurança.</div></div></div>` },

    55: { title: "Osteologia: Esqueleto Apendicular", content: `
<div class="resumo-header-main"><h2>🦾🦵 Os Membros: Cinturas e Extremidades</h2><p>Escápula, clavícula, úmero, pelve, fêmur — os ossos que permitem locomoção e preensão.</p></div>
<div class="resumo-section"><h3>📌 Pontos de Referência Clínicos Essenciais</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">💉</div><div class="flip-label">Úmero — Injeção IM</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Injeção IM no <strong>deltoide</strong>: face lateral do úmero, 3 dedos abaixo do acrômio. Evitar a região inferior (nervo axilar e artéria braquial profunda no sulco radial).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🩻</div><div class="flip-label">Pelve — Diferenças Sexuais</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Pelve <strong>feminina</strong>: mais larga, ângulo subpúbico > 80° (arco largo), estreito superior oval → parto vaginal. Pelve <strong>masculina</strong>: mais estreita, ângulo < 70°, estreito superior em coração → pelve androide. Importante na obstetrícia e medicina legal.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🦴</div><div class="flip-label">Fêmur — Fratura de Colo</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Fratura do colo do fêmur em idosos osteoporóticos: membro em <strong>rotação lateral + encurtamento</strong>. Risco de necrose avascular da cabeça do fêmur (artéria retinacular comprometida). Tto: artroplastia de quadril.</div></div></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Uma idosa de 80 anos cai da própria altura e não consegue levantar a perna direita. Ela apresenta o membro em rotação externa e encurtamento. Qual a fratura mais provável e qual nervo deve ser avaliado imediatamente?</div><div class="resumo-quiz-answer"><strong>Fratura do Colo do Fêmur</strong> (intracapsular). O membro fica em rotação lateral por ação dos rotadores externos sem oposição. Deve-se avaliar o <strong>Nervo Isquiático</strong> (ciático) e especialmente o <strong>Nervo Fibular Comum</strong> (peroneiro), que pode ser lesado. Avaliar força de dorsiflexão do pé e sensibilidade no dorso do pé.</div></div></div>` },

    56: { title: "Artrologia: Articulações", content: `
<div class="resumo-header-main"><h2>🔩 As Junções do Esqueleto</h2><p>Articulações classificadas por mobilidade e estrutura. A sinovial é a mais importante clinicamente.</p></div>
<div class="resumo-section"><h3>📊 Classificação por Mobilidade</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🧱</div><div class="flip-label">Sinartroses (Imóveis)</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Fibrosas. Sem mobilidade. <strong>Suturas</strong> do crânio adulto (no bebê são fontanelas). <strong>Gonfose</strong>: raiz do dente no alvéolo. <strong>Sindesmose</strong>: ligamento tibio-fibular distal (tornozelo).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🧊</div><div class="flip-label">Anfiartroses (Semimóveis)</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Cartilaginosas. <strong>Sincondrose</strong>: placa epifisária (hialina, temporária — ossifica com maturidade). <strong>Sínfise</strong>: fibrocartilagem. Ex: Sínfise Púbica (abre no parto), Discos Intervertebrais (amortecimento).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🏃</div><div class="flip-label">Diartroses (Sinoviais)</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Máxima mobilidade. Contém cápsula articular + membrana sinovial + líquido sinovial (ácido hialurônico). Cartilagem articular hialina cobre as superfícies. Alvo da Artrite Reumatoide (sinovite) e Osteoartrite (desgaste da cartilagem).</div></div></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um paciente com Artrite Reumatoide tem destruição da articulação metacarpofalangeana. Qual tecido é atacado primariamente pelo processo autoimune e qual enzima é responsável pela destruição da cartilagem?</div><div class="resumo-quiz-answer">A <strong>Membrana Sinovial</strong> é o alvo primário. Linfócitos T autorreativos e macrófagos invadem a sinóvia → formação do <strong>Pannus</strong> (tecido inflamatório invasivo). O pannus secreta <strong>Metaloproteinases de Matriz (MMPs)</strong> — colagenases e estromelisinas — que degradam o colágeno da cartilagem articular e o osso subcondral, causando erosões irreversíveis.</div></div></div>` },

    57: { title: "Introdução à Miologia", content: `
<div class="resumo-header-main"><h2>💪 Os Motores do Corpo: Músculos</h2><p>Tipos de músculo, propriedades e a correlação com patologias neuromusculares.</p></div>
<div class="resumo-section"><h3>🆚 Os Três Tipos de Músculo</h3><div class="resumo-compare">
<div class="resumo-compare-item" style="--compare-color: #ef4444"><h5>Esquelético (Estriado Voluntário)</h5><p>Fibras longas, multinucleadas, estriadas. Controlado pelo SNSomático. Contração rápida e potente. Fadiga rápida (tipo II) ou lenta (tipo I — aeróbico). Lesão: Rabdomiólise (mioglobinúria).</p></div>
<div class="resumo-compare-item" style="--compare-color: #f59e0b"><h5>Cardíaco (Estriado Involuntário)</h5><p>Células ramificadas unidas por <strong>Discos Intercalares</strong> (gap junctions → sincício funcional). Automatismo próprio (SA). Lesão: Infarto do Miocárdio → ↑Troponina I e T (marcador de necrose).</p></div>
</div>
<div class="resumo-compare"><div class="resumo-compare-item" style="--compare-color: #8b5cf6"><h5>Liso (Involuntário)</h5><p>Fusiforme, uninucleado, sem estrias visíveis. Controlado pelo SNA. Parede de órgãos ocos (intestino, bexiga, vasos). Contração lenta e sustentada. Relaxado por Nitratos (vasodilatação coronariana).</p></div></div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Por que um infarto do miocárdio pode ser fatal mesmo que apenas 20% do músculo cardíaco seja necrosado, enquanto uma necrose de 20% do músculo esquelético da coxa raramente mata?</div><div class="resumo-quiz-answer">O miocárdio funciona como um <strong>sincício elétrico</strong> pelos discos intercalares. A necrose de uma região cria zonas de condução anômala → <strong>reentrada elétrica</strong> → Fibrilação Ventricular (o coração para de bombear coordenadamente). Além disso, o coração não pode parar mesmo brevemente. Já o músculo esquelético é formado por fibras independentes — perder 20% de um músculo da coxa apenas reduz a força, sem comprometer a vida.</div></div></div>` },

    58: { title: "Noções de Anatomia Clínica", content: `
<div class="resumo-header-main"><h2>🩺 Anatomia Aplicada: Da Mesa ao Leito</h2><p>Os principais pontos anatômicos de referência usados em procedimentos clínicos e cirúrgicos.</p></div>
<div class="resumo-section"><h3>📍 Pontos de Referência Clínicos Críticos</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Ângulo de Louis (Sternal):</strong> União do manúbrio com o corpo do esterno. Nível de T4-T5. Referência: bifurcação da traqueia, 2º espaço intercostal (ausculta valva aórtica), arco da aorta.</div>
<div class="resumo-timeline-item"><strong>Linha Hemiclavicular:</strong> Dreno de tórax para pneumotórax → 2º EIC na linha hemiclavicular. Para derrame pleural → 5º-6º EIC na linha axilar média.</div>
<div class="resumo-timeline-item"><strong>Triângulo de Hesselbach:</strong> Delimitado por: ligamento inguinal (inferior), artéria epigástrica inferior (lateral), borda do reto abdominal (medial). Hérnia direta passa por dentro; indireta passa por fora (pelo anel interno).</div>
<div class="resumo-timeline-item"><strong>Ponto de McBurney:</strong> 1/3 lateral da linha entre EIAS e umbigo. Ponto de máxima dor na Apendicite Aguda.</div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz Final</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um paciente com trauma torácico por faca apresenta pneumotórax hipertensivo. A drenagem de emergência deve ser feita em qual espaço intercostal, linha de referência, e por que se escolhe a borda superior da costela inferior?</div><div class="resumo-quiz-answer"><strong>2º Espaço Intercostal, Linha Hemiclavicular</strong> (ou 4º-5º EIC na linha axilar anterior para dreno convencional). Escolhe-se a <strong>borda superior da costela inferior</strong> (borda cranial da costela abaixo) porque o <strong>Feixe Neurovascular</strong> (artéria, veia e nervo intercostais) corre no sulco da borda <em>inferior</em> de cada costela. Puncionar pela borda superior evita lacerar esses vasos e causar hemotórax iatrogênico.</div></div></div>` }
};
