window.RESUMOS_BIOSTATS = {
    501: { title: "Estatística Descritiva", content: `
<div class="resumo-header-main"><h2>📊 A Anatomia dos Dados Médicos</h2><p>Classificar variáveis e escolher a medida certa é a base de qualquer análise estatística confiável.</p></div>
<div class="resumo-section"><h3>📏 Tipos de Variáveis</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">📐</div><div class="flip-label">Quantitativa Contínua</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Aceita qualquer valor decimal. Ex: Peso (72,5 kg), Pressão arterial (120,5 mmHg), Temperatura, Glicemia. Analisada por média, DP, teste t, ANOVA.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🔢</div><div class="flip-label">Quantitativa Discreta</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Apenas números inteiros (contagens). Ex: Número de filhos, FC (70 bpm), número de internações. Não existe "2,5 filhos".</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🥇</div><div class="flip-label">Qualitativa Ordinal</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Categorias com hierarquia/ordem. Ex: Grau de dor (0-10), Escala de Glasgow (3-15), Estadiamento de tumor (I, II, III, IV), Classificação NYHA de IC.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🏷️</div><div class="flip-label">Qualitativa Nominal</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Categorias sem hierarquia. Ex: Sexo (M/F), Tipo sanguíneo (A, B, AB, O), Diagnóstico, Cor dos olhos, Sim/Não. Analisada por frequência, qui-quadrado.</div></div></div>
</div></div>
<div class="resumo-section"><h3>🎯 Média, Mediana e Moda</h3><div class="resumo-accordion open"><div class="resumo-accordion-header"><h4>Quando usar cada medida? (Clique)</h4><span class="resumo-accordion-arrow">▼</span></div><div class="resumo-accordion-body"><ul>
<li><strong>Média:</strong> Distribuição simétrica (normal). Sensível a outliers — um valor extremo distorce tudo. Exemplo: 9 pacientes com renda de R$1.000 e 1 com R$100.000 → média de R$10.900 (não representa a maioria).</li>
<li><strong>Mediana:</strong> Distribuição assimétrica ou com outliers. O valor central da distribuição ordenada. Melhor para renda, tempo de sobrevivência, custo hospitalar.</li>
<li><strong>Moda:</strong> Valor mais frequente. Útil para variáveis nominais e para identificar o pico de uma distribuição.</li>
</ul><p><strong>Distribuição Normal (Gaussiana):</strong> Média = Mediana = Moda. Curva em sino simétrica. A maioria dos testes paramétricos exige essa distribuição.</p></div></div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um estudo reporta a "renda mensal dos médicos" com média de R$25.000, mas mediana de R$12.000. O que isso indica sobre a distribuição dos dados — e qual medida é mais representativa?</div><div class="resumo-quiz-answer">A <strong>Mediana é mais representativa</strong>. A grande diferença entre média e mediana indica <strong>assimetria positiva (cauda à direita)</strong> — poucos médicos com renda muito alta (outliers) estão "puxando" a média para cima. A mediana de R$12.000 é o valor que realmente divide o grupo ao meio, sendo mais honesta para representar a realidade da maioria.</div></div></div>` },

    502: { title: "Probabilidade e Distribuições", content: `
<div class="resumo-header-main"><h2>🎲 A Matemática do Acaso na Medicina</h2><p>Distribuição normal, intervalos de confiança e o que realmente significa um p-valor.</p></div>
<div class="resumo-section"><h3>📈 Distribuição Normal e o Desvio Padrão</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Média ± 1 DP:</strong> Contém ~68% dos dados. Ex: Se altura média = 170cm, DP = 10cm → 68% das pessoas têm entre 160-180cm.</div>
<div class="resumo-timeline-item"><strong>Média ± 2 DP:</strong> Contém ~95% dos dados. Base dos valores de referência laboratorial (intervalo de referência = média ± 2DP de uma população saudável).</div>
<div class="resumo-timeline-item"><strong>Média ± 3 DP:</strong> Contém ~99,7% dos dados. Valores acima disso são raríssimos — geralmente patológicos.</div>
</div></div>
<div class="resumo-section"><h3>🎯 Hipótese Nula e p-valor</h3><div class="resumo-compare">
<div class="resumo-compare-item" style="--compare-color: #ef4444"><h5>Erro Tipo I (α — Falso Positivo)</h5><p>Rejeitar H₀ quando ela é verdadeira. "Dizer que o remédio funciona quando não funciona." Controlado pelo nível de significância (α = 0,05 por convenção). Solução: aumentar o α exigido.</p></div>
<div class="resumo-compare-item" style="--compare-color: #3b82f6"><h5>Erro Tipo II (β — Falso Negativo)</h5><p>Aceitar H₀ quando ela é falsa. "Dizer que o remédio não funciona quando funciona." Reduzido aumentando o tamanho amostral. O Poder do Estudo = 1 − β (idealmente ≥ 80%).</p></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um estudo com apenas 20 pacientes não encontra diferença significativa (p=0,12) entre dois antibióticos. Qual erro estatístico pode ter ocorrido e como seria corrigido?</div><div class="resumo-quiz-answer"><strong>Erro Tipo II (β).</strong> A amostra pequena (n=20) não tinha poder estatístico suficiente para detectar uma diferença real se ela existisse. O estudo foi <strong>subpotenciado (underpowered)</strong>. Solução: realizar <strong>cálculo amostral</strong> antes do estudo para determinar o n necessário para ter ≥80% de poder com o tamanho de efeito esperado.</div></div></div>` },

    503: { title: "Inferência Estatística e Testes", content: `
<div class="resumo-header-main"><h2>⚖️ Qual Teste Usar em Cada Situação</h2><p>Paramétrico vs não-paramétrico, comparação de médias vs proporções — o mapa dos testes estatísticos.</p></div>
<div class="resumo-section"><h3>🗺️ Guia de Seleção de Testes</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">📊</div><div class="flip-label">Comparar 2 Médias</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back"><strong>Distribuição normal → Teste t de Student.</strong> Amostras independentes (p.ex.: homens vs mulheres) ou pareadas (antes vs após tratamento). Não-normal ou ordinal → <strong>Mann-Whitney</strong> (independente) ou <strong>Wilcoxon</strong> (pareado).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">📉</div><div class="flip-label">Comparar 3+ Grupos</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back"><strong>Normal → ANOVA (Análise de Variância).</strong> Se significativa, teste post-hoc (Tukey) para saber quais grupos diferem. Não-normal → <strong>Kruskal-Wallis</strong>. Nunca fazer múltiplos testes t — infla o erro tipo I!</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🔣</div><div class="flip-label">Comparar Proporções</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back"><strong>Qui-Quadrado (χ²):</strong> Variáveis nominais, grandes amostras (n≥5 em cada célula). Ex: Taxa de cura no grupo A vs B. <strong>Teste de Fisher:</strong> Quando n é pequeno ou há células com valor esperado < 5.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">📈</div><div class="flip-label">Correlação</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back"><strong>Pearson (r):</strong> Correlação entre duas variáveis contínuas normais. Varia de -1 a +1. <strong>Spearman (ρ):</strong> Versão não-paramétrica, usa ranks. Ambos medem associação, NÃO causalidade!</div></div></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Pesquisador quer comparar a taxa de infecção cirúrgica entre 3 técnicas diferentes (A, B, C) — variável nominal (infectou: sim/não) em 300 pacientes. Qual teste estatístico é mais apropriado?</div><div class="resumo-quiz-answer"><strong>Qui-Quadrado (χ²)</strong> de independência. Estamos comparando proporções (variáveis nominais dicotômicas: sim/não) entre 3 grupos independentes. Se alguma célula da tabela tiver frequência esperada < 5, deve-se usar o Teste Exato de Fisher. Nunca usar teste t ou ANOVA para variáveis nominais.</div></div></div>` },

    504: { title: "Interpretação de Artigos Científicos", content: `
<div class="resumo-header-main"><h2>📰 Leitura Crítica: Separar o Ouro do Lixo</h2><p>Vieses, confundidores, validade interna e externa — as ferramentas para avaliar se um artigo merece mudar sua prática.</p></div>
<div class="resumo-section"><h3>⚠️ Os Principais Vieses em Pesquisa</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Viés de Seleção:</strong> A amostra não representa a população. Ex: Recrutar pacientes só de hospital terciário para um estudo sobre gripe (os casos mais graves, não os típicos).</div>
<div class="resumo-timeline-item"><strong>Viés de Informação/Memória:</strong> Participantes relatam exposições passadas de forma imprecisa. Clássico em caso-controle. Ex: Mães de crianças com malformações "lembram" melhor de medicamentos tomados na gravidez.</div>
<div class="resumo-timeline-item"><strong>Viés de Confundimento:</strong> Uma 3ª variável associada à exposição E ao desfecho distorce a associação. Ex: Café associado a IAM — confundidor: tabagismo (fumantes bebem mais café E têm mais IAM).</div>
<div class="resumo-timeline-item"><strong>Viés de Publicação:</strong> Estudos positivos são mais publicados que negativos. Superestima o efeito de intervenções. Combatido pelo registro prévio de protocolos e funnel plots em metanálises.</div>
</div></div>
<div class="resumo-section"><h3>📏 Intervalo de Confiança (IC 95%)</h3><div class="resumo-accordion open"><div class="resumo-accordion-header"><h4>Como interpretar o IC corretamente (Clique)</h4><span class="resumo-accordion-arrow">▼</span></div><div class="resumo-accordion-body"><p>IC 95% = range de valores onde o parâmetro verdadeiro está com 95% de probabilidade. <strong>Interpretação prática:</strong></p><ul>
<li>Se o IC de um <strong>RR ou OR</strong> cruza o <strong>1</strong> → resultado não significativo (inclui ausência de efeito).</li>
<li>Se o IC de uma <strong>diferença de médias</strong> cruza o <strong>0</strong> → não significativo.</li>
<li>IC <strong>estreito</strong> = estudo preciso (amostra grande). IC <strong>largo</strong> = estudo impreciso (amostra pequena).</li>
</ul></div></div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um ECR sobre novo anti-hipertensivo mostra: Redução média da PA = 8 mmHg, IC 95% [2–14 mmHg], p=0,003. Outro estudo mostra: Redução = 5 mmHg, IC 95% [-1–11 mmHg], p=0,09. Qual estudo demonstrou benefício estatisticamente significativo e por quê?</div><div class="resumo-quiz-answer"><strong>O primeiro estudo</strong> (IC [2–14], p=0,003). O IC não cruza o zero (tanto 2 quanto 14 são positivos), indicando que em qualquer cenário plausível há redução real. O segundo estudo tem IC [-1 a +11]: como cruza o zero, não podemos descartar que o efeito verdadeiro seja nulo ou até negativo — portanto, não significativo (p=0,09 > 0,05 confirma).</div></div></div>` }
};
