window.RESUMOS_ANATOMY2 = {
    100: { title: "Tórax, Abdome e Sistemas", content: `
<div class="resumo-header-main"><h2>🫁 A Caixa Torácica e seus Conteúdos</h2><p>Mediastino, pulmões e coração — topografia essencial para interpretar radiografias e realizar procedimentos.</p></div>
<div class="resumo-section"><h3>🗺️ Divisões do Mediastino</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">⬆️</div><div class="flip-label">Mediastino Superior</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Acima do Ângulo de Louis (T4). Contém: Arco da Aorta, Tronco Braquiocefálico, Veias Braquiocefálicas, Traqueia (antes de bifurcar), Esôfago, Duto Torácico, Nervo Frênico e Vago.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">❤️</div><div class="flip-label">Mediastino Médio</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">O coração dentro do pericárdio fibroso. Raízes dos grandes vasos (Aorta ascendente, Tronco Pulmonar, VCS, VCI). Bifurcação da traqueia (carina) em brônquios principais.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">⬇️</div><div class="flip-label">Mediastino Posterior</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Aorta torácica descendente, Esôfago (distal), Duto Torácico, Veias Ázigos, Nervos Esplâncnicos, Tronco Simpático. Tumores aqui causam disfagia e rouquidão (compressão do nervo laríngeo recorrente).</div></div></div>
</div></div>
<div class="resumo-section"><h3>🩺 As Coronárias e o Infarto</h3><div class="resumo-compare">
<div class="resumo-compare-item" style="--compare-color: #ef4444"><h5>Coronária Esquerda (TCE → DA + CX)</h5><p><strong>DA (Descendente Anterior):</strong> Irriga parede anterior do VE + septo (2/3 anteriores). Oclusão = "widow maker" → infarto anterior maciço, BRE, choque cardiogênico.<br><strong>CX (Circunflexa):</strong> Parede lateral do VE.</p></div>
<div class="resumo-compare-item" style="--compare-color: #3b82f6"><h5>Coronária Direita (CD)</h5><p>Irriga VD + parede inferior do VE + nó SA e nó AV (em 70% das pessoas — dominância direita). Oclusão → Infarto Inferior (supradesnivelamento em DII, DIII, aVF) + BAV e bradicardia.</p></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ ECG de um paciente com dor no peito mostra supradesnivelamento de ST em DII, DIII e aVF, além de bradicardia com BAV de 1º grau. Qual artéria está ocluída e por que há o distúrbio de condução?</div><div class="resumo-quiz-answer"><strong>Coronária Direita (CD).</strong> Ela irriga a parede inferior do VE (derivações inferiores: DII, DIII, aVF). Em ~70% das pessoas, a CD também nutre o <strong>Nó SA e o Nó AV</strong> através de seus ramos. A isquemia desses nós causa bradicardia (Nó SA lento) e BAV (Nó AV com condução comprometida).</div></div></div>` },

    101: { title: "Anatomia Prática dos Membros", content: `
<div class="resumo-header-main"><h2>🦾 Plexo Braquial e Membro Superior</h2><p>A fiação elétrica do braço — lesões, nervos e deformidades clínicas clássicas.</p></div>
<div class="resumo-section"><h3>⚡ Nervos do Plexo Braquial (C5-T1)</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Nervo Axilar (C5-C6):</strong> Passa pelo espaço quadrilateral. Lesão no colo cirúrgico do úmero → paralisia do Deltoide (não abduz o braço acima de 15°) + perda sensitiva no "distintivo do sargento" (face lateral do ombro).</div>
<div class="resumo-timeline-item"><strong>Nervo Radial (C5-T1):</strong> Sulco espiral do úmero. Fratura da diáfise umeral → "Mão Caída" (wrist drop) — sem extensão de punho e dedos. Perda sensitiva no dorso da mão (1º espaço interdigital).</div>
<div class="resumo-timeline-item"><strong>Nervo Mediano (C5-T1):</strong> Túnel do Carpo. Síndrome do Túnel do Carpo → dor e formigamento nos 3,5 dedos laterais, fraqueza da pinça. "Mão de Pregador" na lesão alta. Teste: Phalen e Tinel.</div>
<div class="resumo-timeline-item"><strong>Nervo Ulnar (C8-T1):</strong> Epicôndilo medial. "Mão em Garra" (dedos 4-5 em garra por paralisia dos lumbricais). Perda sensitiva no 1,5 dedo medial. Atrofia da eminência hipotenar.</div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um paciente acorda com o braço dormente após dormir com a cabeça sobre o braço (Saturday Night Palsy). Ele tem "mão caída" e não consegue estender punho ou dedos, mas a extensão do cotovelo está preservada. Qual nervo e qual local exato da lesão?</div><div class="resumo-quiz-answer"><strong>Nervo Radial</strong> comprimido no <strong>Sulco Espiral (Sulco Radial)</strong> do úmero. A extensão do cotovelo é preservada porque o nervo para o Tríceps (músculo extensor do cotovelo) origina-se <em>antes</em> do sulco espiral. A compressão no sulco afeta apenas os ramos distais → extensores do punho e dedos paralisados → wrist drop (mão caída).</div></div></div>` },

    102: { title: "Anatomia Topográfica do Abdome", content: `
<div class="resumo-header-main"><h2>🍽️ O Peritônio e as Vísceras</h2><p>Retroperitoneais vs Intraperitoneais — distinção fundamental em cirurgia e emergências abdominais.</p></div>
<div class="resumo-section"><h3>🗺️ Intra vs Retroperitoneal</h3><div class="resumo-compare">
<div class="resumo-compare-item" style="--compare-color: #3b82f6"><h5>Intraperitoneais (Suspensos por Mesenterio)</h5><p>Estômago, Fígado (exceto área nua), Baço, Jejuno, Íleo, Ceco, Apêndice, Cólon Transverso e Sigmóide, Reto superior, Ovários/Tubas. Podem volvular (girar no pedículo).</p></div>
<div class="resumo-compare-item" style="--compare-color: #ef4444"><h5>Retroperitoneais (SAD PUCKER)</h5><p><strong>S</strong>uprarrenais, <strong>A</strong>orta/VCI, <strong>D</strong>uodeno (2ª-4ª porções), <strong>P</strong>âncreas (exceto cauda), <strong>U</strong>reteres, <strong>C</strong>ólon asc/desc, <strong>K</strong>idneys (rins), <strong>E</strong>sôfago inferior, <strong>R</strong>eto (médio/inferior). Dor lombar em processos retroperitoneais (pancreatite, AAA).</p></div>
</div></div>
<div class="resumo-section"><h3>🩸 Sistema Porta-Hepático</h3><div class="resumo-accordion open"><div class="resumo-accordion-header"><h4>Hipertensão Portal e Varizes (Clique)</h4><span class="resumo-accordion-arrow">▼</span></div><div class="resumo-accordion-body"><p>A Veia Porta drena TGI + Baço → Fígado. Na cirrose, o fígado fibrótico aumenta a resistência → <strong>Hipertensão Portal</strong>. O sangue busca vias colaterais (anastomoses portocava):</p><ul><li><strong>Varizes Esofágicas</strong> (V. Gástrica Esquerda ↔ V. Ázigos) → Hemorragia digestiva alta fatal.</li><li><strong>Cabeça de Medusa</strong> (V. Paraumbilicais ↔ V. Epigástricas) → veias dilatadas no umbigo.</li><li><strong>Hemorroidas</strong> (V. Retal Superior ↔ V. Retal Média/Inferior).</li></ul></div></div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um cirurgião realiza esplenectomia de emergência por trauma. Qual estrutura anatômica ele deve identificar no hilo esplênico para ligar com segurança — e qual órgão adjacente pode ser lesado inadvertidamente?</div><div class="resumo-quiz-answer">No hilo esplênico, o cirurgião deve ligar a <strong>Artéria e Veia Esplênicas</strong> (que correm no ligamento esplêniorreal/lienorreal). O risco adjacente é a <strong>Cauda do Pâncreas</strong>, que chega até o hilo esplênico em ~75% das pessoas. Lesão inadvertida → fístula pancreática ou pancreatite pós-operatória.</div></div></div>` },

    103: { title: "Anatomia Clínica Básica", content: `
<div class="resumo-header-main"><h2>🩺 Anatomia de Superfície e Procedimentos</h2><p>Pontos de referência palpáveis, linhas de orientação e sítios de acesso venoso central.</p></div>
<div class="resumo-section"><h3>💉 Acesso Venoso Central</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🎯</div><div class="flip-label">Veia Jugular Interna</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Abordagem pelo triângulo formado pelas 2 cabeças do Esternocleidomastóideo. Referência: ponta do processo mastoide. Risco: pneumotórax (menor que subclávia), punção carotídea. Preferida por alta taxa de sucesso.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🔵</div><div class="flip-label">Veia Subclávia</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Abaixo da clavícula, no 1/3 médio-lateral. Referência: curvatura da clavícula e 1ª costela. Maior risco de <strong>Pneumotórax</strong> (pulmão adjacente) e hemotórax. Usada quando jugular não é acessível.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🦵</div><div class="flip-label">Veia Femoral</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Triângulo femoral: medial à Artéria Femoral (mnemônico: <strong>NAVEL</strong> — Nervo, Artéria, Veia, vazio, Linfonodo — de lateral para medial). Sem risco de pneumotórax. Maior risco de infecção e trombose. Usada em ressuscitação de emergência.</div></div></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Após inserção de cateter venoso central pela subclávia, o paciente desenvolve súbita dor torácica e queda de saturação. Ausculta revela ausência de murmúrio vesicular no hemitórax ipsilateral. Qual a complicação e qual o tratamento imediato?</div><div class="resumo-quiz-answer"><strong>Pneumotórax Iatrogênico</strong> (ou hipertensivo se houver desvio de mediastino e hipotensão). A agulha de punção perfurou o ápice pulmonar. Tratamento imediato: <strong>Drenagem torácica</strong> no 2º EIC na linha hemiclavicular (agulha de grosso calibre em emergência) ou dreno de tórax no 4º-5º EIC na linha axilar anterior para descompressão definitiva.</div></div></div>` },

    106: { title: "Vascularização e Inervação Sistêmica", content: `
<div class="resumo-header-main"><h2>🩸 Os Grandes Sistemas Vasculares</h2><p>Aorta e seus ramos, sistema venoso profundo — o mapa circulatório que sustenta a vida.</p></div>
<div class="resumo-section"><h3>🗺️ Ramos da Aorta Abdominal</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>Tronco Celíaco (T12):</strong> Irriga o Foregut. Ramos: Gástrica Esquerda, Esplênica, Hepática Comum. "Tripé de Haller".</div>
<div class="resumo-timeline-item"><strong>AMS — Artéria Mesentérica Superior (L1):</strong> Irriga o Midgut (duodeno distal até 2/3 do transverso). Oclusão aguda = isquemia intestinal massiva (dor desproporcional ao exame físico inicial).</div>
<div class="resumo-timeline-item"><strong>Renais (L1-L2):</strong> Direita mais longa (cruza VCI). A esquerda drena para a veia renal esquerda que recebe a veia gonadal esquerda (varicocele esquerda súbita = possível tumor renal!).</div>
<div class="resumo-timeline-item"><strong>AMI — Artéria Mesentérica Inferior (L3):</strong> Irriga o Hindgut (1/3 distal transverso, descendente, sigmoide, reto superior).</div>
<div class="resumo-timeline-item"><strong>Bifurcação Aórtica (L4):</strong> Ilíacas Comuns → Internas (pelve) + Externas (membros inferiores). Aneurisma Aórtico Abdominal (AAA) comum nesse segmento — pulsa na linha média acima do umbigo.</div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Um homem de 65 anos fumante apresenta dor abdominal em cólica após refeições, perda de peso e sopro abdominal periumbilical. Qual síndrome é essa e qual artéria é a principal responsável?</div><div class="resumo-quiz-answer"><strong>Angina Mesentérica (Isquemia Mesentérica Crônica).</strong> Aterosclerose da <strong>Artéria Mesentérica Superior (AMS)</strong> — o principal vaso do intestino delgado. A dor ocorre após refeições porque a digestão aumenta a demanda de fluxo sanguíneo intestinal que a artéria estenótica não consegue suprir (mecanismo análogo à angina de esforço coronariana). O sopro indica estenose hemodinâmica significativa.</div></div></div>` },

    108: { title: "Pelve e Períneo", content: `
<div class="resumo-header-main"><h2>🔵 A Arquitetura da Pelve</h2><p>Assoalho pélvico, órgãos genitais, bexiga e reto — anatomia essencial para ginecologia, urologia e cirurgia colorretal.</p></div>
<div class="resumo-section"><h3>🏗️ O Assoalho Pélvico</h3><div class="resumo-accordion open"><div class="resumo-accordion-header"><h4>Músculos do Diafragma Pélvico (Clique)</h4><span class="resumo-accordion-arrow">▼</span></div><div class="resumo-accordion-body"><p>Formado principalmente pelo <strong>Músculo Levantador do Ânus</strong> (3 partes: puborretal, pubococcígeo, iliococcígeo) + Isquiococcígeo. Funções: sustenta vísceras pélvicas, mantém continência fecal e urinária, auxilia no parto.</p><p>Disfunção: <strong>Prolapso de órgãos pélvicos</strong> (cistocele, retocele, prolapso uterino) por enfraquecimento após partos múltiplos ou envelhecimento. Tto: fisioterapia pélvica (Kegel), cirurgia corretiva.</p></div></div></div>
<div class="resumo-section"><h3>⚠️ Nervos em Risco no Parto</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">⚡</div><div class="flip-label">Nervo Pudendo</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Principal nervo do períneo (S2-S4). Passa pelo Canal de Alcock (na fáscia do obturador). Inerva esfíncter externo anal, uretra, genitais externos. Bloqueio pudendo = anestesia perineal no parto. Lesão → incontinência.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🦵</div><div class="flip-label">Nervo Femoral Cutâneo Lateral</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Passa sob o ligamento inguinal. Compressão pelo útero gravídico ou posicionamento cirúrgico → <strong>Meralgia Parestésica</strong> — dor e formigamento na face lateral da coxa. Sem fraqueza muscular (sensitivo puro).</div></div></div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Durante histerectomia, o cirurgião deve identificar os ureteres para não cloná-los. Em qual ponto anatômico os ureteres cruzam com os vasos uterinos — e qual é o risco se essa relação não for respeitada?</div><div class="resumo-quiz-answer">Os ureteres cruzam <strong>sob</strong> a Artéria Uterina ("água por baixo da ponte") a cerca de 1,5 cm lateral ao colo uterino. Se o ureter for clampeado ou seccionado junto com a artéria uterina → <strong>Ligadura/Transecção Ureteral</strong> → hidronefrose, fístula uretero-vaginal. Por isso diz-se: "O ureter passa por baixo da artéria uterina como a água passa por baixo de uma ponte."</div></div></div>` },

    109: { title: "Cabeça e Pescoço", content: `
<div class="resumo-header-main"><h2>👤 A Complexidade da Cabeça e do Pescoço</h2><p>Nervos cranianos, glândulas, vias aéreas superiores — a anatomia que governa os sentidos e a deglutição.</p></div>
<div class="resumo-section"><h3>⚡ Os 12 Nervos Cranianos — Resumo Funcional</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>I (Olfatório):</strong> Olfato. Lesão = anosmia (trauma frontal).</div>
<div class="resumo-timeline-item"><strong>II (Óptico):</strong> Visão. Neurônio aferente do reflexo fotomotor.</div>
<div class="resumo-timeline-item"><strong>III (Oculomotor):</strong> Músculos oculares (exceto RS e OI), elevador da pálpebra, constritor da pupila. Lesão = ptose + midríase + olho "para baixo e para fora". Aneurisma da comunicante posterior comprime o NC III!</div>
<div class="resumo-timeline-item"><strong>V (Trigêmeo):</strong> Sensitivo da face (3 ramos: oftálmico, maxilar, mandibular). Motor da mastigação. Reflexo corneal (aferente V1).</div>
<div class="resumo-timeline-item"><strong>VII (Facial):</strong> Motor da expressão facial, Gustação (2/3 anteriores da língua), glândulas lacrimal/salivar. Paralisia central (AVC) poupa a fronte. Paralisia periférica (Bell) compromete toda a hemiface.</div>
<div class="resumo-timeline-item"><strong>X (Vago):</strong> Parassimpático de coração, pulmões, TGI. Motor da faringe/laringe. Nervo laríngeo recorrente: esquerdo passa pelo arco aórtico (tumor de pulmão pode compri-lo → rouquidão).</div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Paciente com AVC do hemisfério direito desenvolve fraqueza facial esquerda, mas consegue franzir a testa. Por que a testa é poupada na paralisia facial central?</div><div class="resumo-quiz-answer">O <strong>Músculo Frontal</strong> (franze a testa) tem <strong>representação cortical bilateral</strong> — recebe fibras dos dois hemisférios cerebrais. Portanto, um AVC unilateral (p.ex. AVC cortical direito) não paralisa completamente a fronte, pois o hemisfério contralateral preservado ainda a inerva. Na paralisia de Bell (lesão do NC VII periférico), TODA a hemiface ipsilateral é acometida, inclusive a testa — diagnóstico diferencial crucial.</div></div></div>` },

    110: { title: "Neuroanatomia Funcional", content: `
<div class="resumo-header-main"><h2>🧠 Mapa do Sistema Nervoso Central</h2><p>Lobos cerebrais, vias motoras e sensitivas, sistema límbico — a base para entender os déficits neurológicos.</p></div>
<div class="resumo-section"><h3>🗺️ Lobos Cerebrais e Funções</h3><div class="resumo-flip-grid">
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">🎯</div><div class="flip-label">Lobo Frontal</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Córtex motor primário (giro pré-central), Área de Broca (fala — hemisfério dominante, geralmente esquerdo), funções executivas, personalidade, inibição de comportamento. Lesão: hemiparesia contralateral, afasia de Broca (fala não fluente), desinibição.</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">✋</div><div class="flip-label">Lobo Parietal</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Córtex sensitivo primário (giro pós-central). Integração sensorial. Lesão do parietal dominante (esq): apraxia, agnosia, afasia de Wernicke. Lesão do não-dominante (dir): <strong>Heminegligência</strong> (ignora o lado esquerdo do corpo e espaço).</div></div></div>
<div class="resumo-flip-card"><div class="resumo-flip-inner"><div class="resumo-flip-front"><div class="flip-icon">👁️</div><div class="flip-label">Lobo Occipital</div><div class="flip-hint">Girar</div></div><div class="resumo-flip-back">Córtex visual primário (área calcarina). Cada hemisfério recebe informação do campo visual oposto. Lesão bilateral → <strong>Cegueira Cortical</strong> (reflexo fotomotor preservado!). AVC de artéria cerebral posterior.</div></div></div>
</div></div>
<div class="resumo-section"><h3>🔄 Via Piramidal (Corticospinal)</h3><div class="resumo-timeline">
<div class="resumo-timeline-item"><strong>1º Neurônio (Neurônio Motor Superior — NMS):</strong> Córtex motor → decussa na pirâmide bulbar → desce no funículo lateral da medula. Lesão: espasticidade, hiperreflexia, sinal de Babinski, sem atrofia.</div>
<div class="resumo-timeline-item"><strong>2º Neurônio (Neurônio Motor Inferior — NMI):</strong> Corno anterior da medula → músculo. Lesão: flacidez, hiporreflexia, fasciculações, atrofia muscular.</div>
</div></div>
<div class="resumo-section"><h3>🧪 Quiz</h3><div class="resumo-quiz"><div class="resumo-quiz-question">❓ Paciente pós-AVC tem fraqueza de membro superior e inferior direito, fala não fluente mas compreende bem. Onde está a lesão e qual o nome da afasia?</div><div class="resumo-quiz-answer">Lesão no <strong>Hemisfério Esquerdo</strong> (dominante) comprometendo o <strong>Córtex Motor</strong> (causa hemiplegia direita) e a <strong>Área de Broca</strong> no giro frontal inferior. A <strong>Afasia de Broca</strong> (não fluente / expressiva / de produção): o paciente entende os comandos mas não consegue falar fluentemente — fala telegráfica, com esforço, sem prosódia. A compreensão preservada diferencia da Afasia de Wernicke.</div></div></div>` }
};
